### ISSUE TITLE
EMI keybinds activate even when creative search is active

### ISSUE THREAD

**Issue by artemisSystem** [emilyploszaj/emi#10]
When in the creative inventory search menu (the compass in top right), EMI keybinds are still active, so if you're searching for something and you type "r" or "u", and you happen to be hovering over an item, you'll be thrown out of the search and the recipe view opens up.

**Comment by emilyploszaj** [comment]
This is a good note, I typically play in survival with EMI cheat mode, I'll fix this up.

**Comment by SpyC0der77** [comment]
How do I fix this? It is happening for me in the latest version.
