### ISSUE TITLE
[Repost from #80] Recipe Filling Too Strict

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#100]
_I'm just copying this here so it's not lost in the closed issue #80 ._

A related issue I'm having is with filling certain recipes at all, that seems to be related to NBT data. Below I have a recipe that's fully ready to transfer as seen by EMI knowing and showing that I can "Fill Recipe" yet the button does not do anything when clicked. Clicking on the favorite also does not move any items, it simply opens the recipe viewer for that recipe. If not fully fixable, it would be nice if the recipe filler could do a "fuzzy" sort of transfer where it moves every item it can to the best of it's ability, since it knows that the inventory does have all the ingredients necessary.

Doing a bit of testing with a sword recipe seems to confirm NBT is at fault. When a plain sword is in the inventory, the recipe transfers (except slot 0). When I put Sharpness on the sword the recipe stops transferring completely.

![](https://user-images.githubusercontent.com/72876796/188769117-fd838388-1fe4-4b92-b4d0-08356f049dce.png)

**Comment by inikishev** [comment]
same issue

**Comment by Xoouu** [comment]
It happens with item durability too. In my case I wanted to build a dispenser, but I was using already worn out bows. I was wondering why it didn't fill but now I understand why.
The "fuzzy" search would be a great addition.

**Comment by Chikage0o0** [comment]
I also think so, there should be an option to ignore nbt when matching items。

**Comment by emilyploszaj** [comment]
Okay I had to look into this for a long time but I finally figured out what was causing this. 0.6.0 should abide by the input's matching comparison, I'll close this issue when 0.6.0 gets released, thanks for the patience :sweat:
