### ISSUE TITLE
[1.18.2+] Support for Drink Beer [Unoffical Fork]

### ISSUE THREAD

**Issue by ConqAra** [emilyploszaj/emi#103]
Add support for recipes for [Drink Beer](https://www.curseforge.com/minecraft/mc-mods/drink-beer-unofficial-clockwerk-edition)

[https://github.com/ClockwerkKaiser/DrinkBeer/issues/3](https://github.com/ClockwerkKaiser/DrinkBeer/issues/3)

**Comment by emilyploszaj** [comment]
EMI does not add support for other mods, it's an API for allowing developers to add their own compat.
