### ISSUE TITLE
[Bug] Recipe output resolution unassignable on indeterminate result recipes

### ISSUE THREAD

**Issue by OrionOth** [emilyploszaj/emi#104]
### Bug: EMI does not currently ❤️ recipes with chance outputs
While recipe resolution works well most of the time, enabling default recipes to be set and then viewed in the recipe tree, it seems to break down when subjected to recipes with indeterminate or variable outputs.
![java_yvygTOoinE](https://user-images.githubusercontent.com/17818861/204162790-d7ef61c7-58c8-485e-b5e3-096fa60f6b60.png)

A highly-visible symptom of this is recipe buttons not showing on recipes with random results.
**When attempting to assign output resolution from the recipe tree, it does not work on recipes with variable outputs.**

Example 1 - Determinate Result Recipe:![java_EkqzCuJPSn](https://user-images.githubusercontent.com/17818861/204161870-104d8105-041c-4456-af1a-b1ed243bcf64.png)
Example 2 - Random Result Recipe:![java_cZhju0Nhbg](https://user-images.githubusercontent.com/17818861/204161895-d3ddc6b1-2bed-4a9f-88e6-87da52182813.png)

**Comment by emilyploszaj** [comment]
Chance will now be fully supported in 0.7.0
