### ISSUE TITLE
[Feature Request] Average + minimum required materials for recipes with variable output

### ISSUE THREAD

**Issue by OrionOth** [emilyploszaj/emi#105]
Given that some recipes do not have a set output, and may give more/less items depending on random chance, there isn't a set amount of materials that are required to get a certain result. The desired output may happen on the first try, or it might not occur until the tenth. 
Thus, a probability distribution chart of recipe results would be an excellent feature addition.
Minimum materials would be what we already have: The base amount of materials for a single craft.
Average materials would 1 divided by the chance of the desired result.
Other probabilistic distributions could also be nice, but certainly more effort, and likely rarely used.

This feature request is blocked by #104

**Comment by emilyploszaj** [comment]
Probability in minecraft recipes is really hard to quantify, and combining chance of consumption with chance of production gives you unbounded chance with no minimum or maximum. Also, assumption about how recipes treat chance can get amplified by being more precise in this area. However, EMI will now display average costs for chanced resources, which I believe is an acceptable middleground.
