### ISSUE TITLE
Cheat One/Stack To Cursor does not appear to work

### ISSUE THREAD

**Issue by gamma-delta** [emilyploszaj/emi#11]
Tried it with left and right button, shift + those, and ctrl + those, as well as various keyboard keys.

**Comment by emilyploszaj** [comment]
Do you have cheat mode enabled on a server that has EMI?

**Comment by gamma-delta** [comment]
In singleplayer, yes. Cheat to inventory works fine with the same keybinds.

**Comment by emilyploszaj** [comment]
Peculiar, I attempted to recreate this earlier, and I accidentally bound my *craft to cursor* button when I tried to test, once I resolved that confusion I was able to set the right binds and confirm it works. Did something similar to this happen to you? I should add headers that break up these groups of binds regardless.

**Comment by gamma-delta** [comment]
Well! it's working now. Beats me...

I think it was not working on Blanketcon, so it's possible 1. they were on an old version 2. I messed up

**Comment by gamma-delta** [comment]
I should put this in another issue, but some kind of "when in context" filter for controls would be cool. So you can get the JEI-like behavior of left-click being show recipe when not in cheat mode, and cheat 1 to cursor in cheat mode.

**Comment by emilyploszaj** [comment]
EMI supports this already! You can have duplicate binds :) It sorts input checking so that the more specialized actions, like cheating or filling a recipe, are attempted before more broad actions, like looking up recipes or uses.

**Comment by sedyh** [comment]
For those who are looking for a setup to get items similar to REI/JEI:
![image](https://user-images.githubusercontent.com/19890545/225903362-6a907584-089b-401c-999c-d1b5a18621d1.png)
