### ISSUE TITLE
[BUG] (Fabric 1.19.2) Infinite Reloading/Not Showing Items

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#111]
_Version of EMI : `0.5.0+1.19.2`
Using a modified, Fabulously Optimized modpack_

**BUG :** Version `< 0.5.0+1.19.2` doesn't show items and `EMI 0.5.0+1.19.2` show "EMI Reloading" since I've added new mods on my Minecraft.

**[Latest LOG file](https://pastebin.com/MSVPuJRJ)**

Sorry for taking your time, to wait a reply I will redo my modpack and putting back one by one my mods and see if I find an issue.

**Comment by ghost** [comment]
Little update, in multiplayer I can use EMI but only after going in single-player and using CTRL+O twice. With the dev mode activated, I have those logs :
![image](https://user-images.githubusercontent.com/58150318/206562289-349abeac-9045-4be8-b40a-ab512141e9ff.png)

I see Create mentioned, do you recommend me to make an issue to them ?
_I'm using [Create 0.5.0-796+1.19.2](https://modrinth.com/mod/create-fabric/version/0.5.0g-796+1.19.2)_

**Comment by ghost** [comment]
After some research, I found this :

https://github.com/Fabricators-of-Create/Create/issues/660
https://github.com/newhoryzon/farmers-delight-fabric/issues/115 (← After reading it, it's probably not a Farmer's Delight problem)

**Comment by emilyploszaj** [comment]
That create issue is not causing this "infinite reload". There is some mod in your setup that is preventing the server from sending information to the client, and it's not clear from your large mod list which one it can be. You can verify this is not an EMI issue by checking if the recipe book has recipes available and if your client can see tags in F3.

**Comment by ghost** [comment]
Okay, thanks for enlightening me on that ^^

**Comment by Chikage0o0** [comment]
>← After reading it, it's probably not a Farmer's Delight problem

You can try removing Farmer's Delight, which should solve the problem.

![image](https://user-images.githubusercontent.com/89348590/206673843-abeb6544-9239-44bd-8f0b-f2806bfac5f1.png)

I also checked the source code of Create and there is no obvious problem.

**Comment by LemmaEOF** [comment]
I found the bug! It's the Farmer's Delight Create-compat [chocolate pie filling recipe](https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/resources/data/farmersdelight/recipes/create/filling/chocolate_pie.json) - the fluid tag `c:chocolates` isn't used in Create, it's `c:chocolate` instead, so switching to the proper tag should stop it from getting index out-of-bounds issues!

**Comment by ghost** [comment]
I found out that Chipped (I'm dumb, or it's only for 1.18.2 rn ?) caused me EMI not charging at all.
That one problem solve lmao...

> I found the bug! It's the Farmer's Delight Create-compat [chocolate pie filling recipe](https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/resources/data/farmersdelight/recipes/create/filling/chocolate_pie.json) - the fluid tag `c:chocolates` isn't used in Create, it's `c:chocolate` instead, so switching to the proper tag should stop it from getting index out-of-bounds issues!

_[srcCode Create chocolate](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/generated/resources/data/c/tags/fluids/chocolate.json)_

Nice one ! But does this one little thing that making all this mess ?

**Comment by LemmaEOF** [comment]
Yep! That goes through to [this line](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/compat/emi/recipes/SpoutEmiRecipe.java#L19), which throws if `getMatchingFluidStacks` returns an empty list.

**Comment by ChimeraGaming** [comment]
Yeah I've already read that and Not seeing what's wrong...
