### ISSUE TITLE
[Bug] 1.19.2, 0.5.0: Inventory left click not working

### ISSUE THREAD

**Issue by UltraBlackLinux** [emilyploszaj/emi#112]
Hey there,
after updating to the latest 1.19.2 version of EMI, left click no longer works to pick up items in the inventory. Only right click works.

- [x] I have checked that this issue is caused by EMI
- [x] I have tried EMI on it's own

Any idea what's going on?
Can you fix this!
Thanks!

Edit: just noticed that EMI is stuck on "EMI reloading"

**Comment by emilyploszaj** [comment]
This is a peculiar bug I can't reproduce, this is just vanilla fabric with EMI on 1.19.2? Can you upload your game log?

**Comment by UltraBlackLinux** [comment]
> This is a peculiar bug I can't reproduce, this is just vanilla fabric with EMI on 1.19.2? Can you upload your game log?

https://mclo.gs/DyIvzny - There doesn't seem to be anything in there. This is also a weird kind of bug, because I can only reproduce it ~80% of the time.

**Comment by emilyploszaj** [comment]
Can you reproduce this on fabric? I don't actually do any testing on quilt so this could possibly be something with them?

**Comment by UltraBlackLinux** [comment]
I can't reproduce this issue on fabric, but I can however still observe the "EMI Reloading" issue

**Comment by emilyploszaj** [comment]
Are you launching this with some third party launcher addon? There are print outs from mods that aren't being loaded by quilt and I think this is something they're causing

**Comment by UltraBlackLinux** [comment]
No clue what you mean with third party launcher addon, but I'm using Prism Launcher which should be fine

Also I don't see it, where did you see the improper loading issue?

Edit: https://mclo.gs/DyIvzny#L183 is the mod list, https://mclo.gs/DyIvzny#L124 is a print about what mods are enabled by prismlauncher

**Comment by emilyploszaj** [comment]
Aha, I've figured it out, the server you're connecting to has some mods installed and is sending you some packets that *probably* aren't that important, but what's notable is the server simply isn't sending you recipe and tag information, EMI isn't reloading for a long time as much as it is simply never being given any information. I believe you can verify this by trying to use the vanilla recipe book or view the tags of a block while on this server.

I misread some things and thought you had a non-fabriquilt mod loaded somehow, my mistake on that front.

**Comment by UltraBlackLinux** [comment]
The packets indeed are not important. They are just from one antique minecraft client they still have support for.

The recipe book is just empty, but that is expected for a minigame server, and the f3-menu does show block tags (the ones with the leading #, right?)

In this case I would suggest that EMI just shows all recipes and items instead of waiting for the server to send something. I really like this addon, even more than REI, but the fact that it's so tightly bound to the recipes you have unlocked is kind of annoying.

**Comment by emilyploszaj** [comment]
Ah, you may misunderstand, on client connection to server, the server sends the client a list of all the recipes in the game, and all the tags in the game. If EMI is stuck infinitely reloading, that means it never got this information (some servers or mods tend to not send this information, or break it on accident, for some reason). EMI can't load without this information, it can't display recipes because, as far as the client knows, none exist (as is evident by the empty recipe book). Recipe unlocking is a separate network event that's unrelated to this initial sync.

**Comment by UltraBlackLinux** [comment]
How does REI solve this problem then though? Could you maybe add support for that approach too?

**Comment by emilyploszaj** [comment]
If REI or JEI are working in this scenario, then there may be an issue on EMI's side relating to this logic, but the log doesn't indicate it, I'll look into the issue more.
