### ISSUE TITLE
Screenshot Button Crashing On Config Scale "0"

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#113]
Trying to use the new screenshot-taking button with a crafting recipe and getting a game crash when the GUI Scale option in the config is set to "0". Despite mentioning that 0 uses the default scale, it seems to use, well, 0 scale. I manually tweaked the value to 4, my current scale, and it took a pic no problem.

[EMI_0.5.0_Screenshot_Crash.txt](https://github.com/emilyploszaj/emi/files/10204057/EMI_0.5.0_Screenshot_Crash.txt)

**Comment by emilyploszaj** [comment]
Looks like the PRed implementation ran into issues if your GUI scale was set to auto, committed a fix
