### ISSUE TITLE
Instant crash when viewing recipes with the Infusion Ritual from BetterEnd

### ISSUE THREAD

**Issue by relt-1** [emilyploszaj/emi#114]
## Version:
* 1.19.2
* Fabric 0.14.11
## Mods:
* emi-0.5.0
* better-end-2.1.2
* iris-mc1.19.2-1.4.5
* sodium-fabric-mc1.19.2-0.4.4+build.18
## Description:
* When i press this button, it crashes the game instantly.
![obraz](https://user-images.githubusercontent.com/60782515/206989385-e9a7c479-e219-44dd-ae2b-1bdcb757f027.png)
[crash-2022-12-12_08.44.20-client.txt](https://github.com/emilyploszaj/emi/files/10205604/crash-2022-12-12_08.44.20-client.txt)
## How to reproduce:
* Lookup gold ingot in the search bar
* Right click the item to view recipes
* Select the Infusion Ritual
* The game should freeze for a couple seconds and then close

**Comment by emilyploszaj** [comment]
This is a bug on Better End's side, they depended on a non-API class and it changed.
