### ISSUE TITLE
[BUG] EMI refusing to load recipes on LAN/uPNP worlds

### ISSUE THREAD

**Issue by HexBugOrion** [emilyploszaj/emi#118]
Steps to reproduce:

1: start up a Minecraft world with EMI

2a:host a LAN world

2b: Open a uPNP world with Essential or other uPNP mod

3: EMI stops loading recipes

Version: 0.5.2 (1.19.2)

**Comment by emilyploszaj** [comment]
Is this the case in a normal LAN connection?

**Comment by emilyploszaj** [comment]
I just tested in a LAN scenario between two clients with just EMI and both clients are able to view all recipes, are you sure this is EMI's doing?

**Comment by HexBugOrion** [comment]
Further clarification:
Modlist (-clients):
EMI
Modern Industrialization (a beta ver that had EMI support)
Immersive Aircraft
Essential
MC ver: 1.19.2
OS: macOS Ventura 13.0.1 (M1 Pro)

**Comment by HexBugOrion** [comment]
If need be I'll provide the entire list with versions and more details

**Comment by HexBugOrion** [comment]
> Is this the case in a normal LAN connection?

~~Also this is both LAN and Essential uPNP, tested it with both~~

~~Appears to be an essential-only bug, disabling Essential resulted in things working fine~~

Okay seems to have resolved somehow

**Comment by emilyploszaj** [comment]
These edits aren't clear, is this an essential only bug or is it just fixed somehow?
