### ISSUE TITLE
Applied  Energistics 2 Crafting Terminal not work

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#119]
Its not possible to apply a recipe to a crafting terminal. The +button has a tooltip: "Current workstation does not support recipe"

**Comment by ghost** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6600

**Comment by emilyploszaj** [comment]
This isn't EMI's end, the issue on their end is the correct place, going to close.
