### ISSUE TITLE
[Feature Request] The | OR search.

### ISSUE THREAD

**Issue by SzczurekYT** [emilyploszaj/emi#122]
Hello
EMI is great I love it. Thanks for making it.
But I miss one feature: multiple searches.
What?
In JEI you can type in the search bar for example "iron **|** diamond" and then you get both items that fit the "iron" search and the ones that fit the "diamond" search. Basically the | symbol works like a OR operator - you get items that match the search before | or after the | symbol. And you can chain them so you can type "iron | gold | diamond" and it will work, giving you iron, gold and diamond items. This comes useful in some cases like working with multiple mods at once or comparing armor sets.
Can we get this in EMI too?
Thanks

**Comment by LemmaEOF** [comment]
This already exists within regex mode - type `/iron|diamond/` to get this!

**Comment by emilyploszaj** [comment]
Regex is useful for having or conditionals in a single query, but it's worth considering queries such as `@minecraft iron | @thermal signalum` with the hierarchy of `OR(AND(mod(minecraft), name(iron)), AND(mod(thermal), name(signalum)))`. I've been meaning to add OR spliting in queries, so I'll have this for the next update.

**Comment by SzczurekYT** [comment]
Thank you

**Comment by emilyploszaj** [comment]
This was implemented in 0.6.0
