### ISSUE TITLE
[Crash] Fabric 1.19.2 - Ticking Player

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#126]
Minecraft version: `1.19.2`
Fabric version: `0.14.11`
EMI version: `0.5.3`

EMI is presumably causing a game crash from... hovering over things. I know that's vague, but that's about all I've got. EMI is able to function as normal for ~15 seconds upon joining a world and opening the inventory for the first time, but then soon crashes randomly upon hovering over anything (items, buttons, etc.)

[Crash report](https://gist.github.com/Puffadillo/aaf5cec65ec9ca8ba5aed9dfd48cc7e2)
[Latest log](https://gist.github.com/Puffadillo/317639310ef1f486356bc98cca6aea3d)

**Comment by emilyploszaj** [comment]
This might be hard to believe, but this is actually a vanilla bug. It's reported [here](https://bugs.mojang.com/browse/MC-258939) and I've been in the process of trying to get it resolved. In the meantime, I've taken some steps to try and reduce how much this vanilla issue is interacted with in dev and it will be released in the next update. However, this should be a relatively rare bug, and shouldn't be consistent like this. Is this happening consistently every time?

**Comment by ghost** [comment]
Odd, it's happening consistently with me. I replicated the steps above 4 times in a row. Is there any other helpful information I can provide?

**Comment by emilyploszaj** [comment]
This should've been significantly reduced in 0.6.0, and as it's otherwise a vanilla bug, closing
