### ISSUE TITLE
Feature Request: add information chart with generation data (ore distribution)

### ISSUE THREAD

**Issue by jiwachow** [emilyploszaj/emi#128]
Hey, I like your mod. 
It would be nice to have charts for each block that is generated based on biome/terrain.
One axis of the chart, would be rarity, and the other would be height.
The chart could be cycled, to see different values for different biomes.
For instance gold ore spawns differently in badlands.

**Comment by artemisSystem** [comment]
I think there was an addon that expressed interest in adding this, I forget its name though. You could ask about it in the EMI discord.

**Comment by emilyploszaj** [comment]
Yeah this is outside the scope of EMI proper, but other EMI add-ons could implement it

**Comment by Shibva** [comment]
what addon is this
