### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by SandWoodJones** [emilyploszaj/emi#13]
I'm a modpack dev. I've been studying the wiki and I really have found no way to simply add a recipe. I haven't made a modpack since 1.8 so I'm used to JEI and Crafttweaker and don't really know how to edit data packs or resource packs.
For example, I want to test it out by adding a world interaction recipe for basalt. How would I go about doing that?

**Comment by emilyploszaj** [comment]
I might add support for world interaction recipes to be resource packed into the game, it could be useful for modpack devs. However, the basalt recipe *should* be in vanilla, so I've added it and will be released in the next update.
