### ISSUE TITLE
Lag with ae2?

### ISSUE THREAD

**Issue by Mg138** [emilyploszaj/emi#132]
Spark profile: https://0x0.st/oh3w.sparkpro

We're not sure what's lagging exactly, there are a few factors to consider (we're using a custom cell-type from [ijo-pona-poki](https://github.com/Mg138/ijo-pona-poki). (shameless plug??)

The FPS drops to ~45 whenever we open the terminal, and then climbs a bit back up. But we also have a lot of items in the storage.

**Comment by emilyploszaj** [comment]
As far as I know, AE2 doesn't have EMI support, so I'm not sure how craftables would be recalculated this often? Are you using a third party plugin with AE2 integration? They may have a particularly laggy strategy. Either way, a log and a mod list would be helpful.

**Comment by Mg138** [comment]
The mod list can be found at: https://codeberg.org/madeline/gaycraft/
(We just added a mod that adds support for EMI searching in ae2, the issue was made before this change)

We have EMICompat, we thought that one only added recipe support...?

**Comment by emilyploszaj** [comment]
It seems like EMICompat adds a recipe handler in ae2 terminals. It's not exactly written poorly, but it is using the old API, which can be a bit more performance intensive, and it doesn't do any caching, which is kinda unfortunate, but it's hard to do that properly as a third party plugin. I believe this is more of an issue for them but, besides migrating to the new API which would see slight improvements, they'd probably have to be more invasive to properly cache terminal state, so it may remain unresolved on their end until AE2 adds integration themselves.
