### ISSUE TITLE
[Feature Request] Cheating Mode Options

### ISSUE THREAD

**Issue by greensad** [emilyploszaj/emi#133]
REI includes a few useful QoL features that I feel are sorely missed here:

**"Cheating in Creative"** allows cheating when in creative mode but not in survival mode, this saves a ton of time and energy in flipping back and forth for those who play both creative and survival. 

**"Cheating Style"** allows a toggle between clicking on an item and 'picking it up' with the cursor similar to the creative mode vanilla menu, & simply clicking on the item to add it to the inventory, the ctrl+rmb is a bit of a chore and quite convoluted to do every time on a creative build.

Thanks for your consideration, if these are out of scope I'd love to know more about the intended scope of EMI and how that might differ from projects like REI or JEI so I can make a better informed decision about which I should be using.

**Comment by emilyploszaj** [comment]
"Cheating Style" exists as you'd like it to. You can rebind "cheat to cursor" (or any bind, really) to a mouse button without modifiers if you'd like, and it'll work as described, EMI is designed to layer binds like this prioritizing specialized actions over generic ones (like viewing a recipe).

When it comes to "Cheating in Creative", I'm not exactly sure what utility this serves. How would this save time switching gamemodes? EMI currently lets you cheat as long as you have permission to spawn in items, there is no need to switch to creative.

**Comment by greensad** [comment]
Okay sorry for the trouble, I dug through the config a little more and was able to find it

**Comment by MeeniMc** [comment]
> When it comes to "Cheating in Creative", I'm not exactly sure what utility this serves. How would this save time switching gamemodes? EMI currently lets you cheat as long as you have permission to spawn in items, there is no need to switch to creative.

I'd like a second consideration given to this proposal: I am often playing with cheats enabled (or with op status on multiplayer). However I would rather not cheat items in the game mistakenly, and having to switch to creative before using the cheat-item feature is a good way to prevent unintentional summoning of items. 

Also, when playing a singleplayer instance with multiple worlds (some being creative  worlds, some being survival), the option is enabled per-instance (that is, if I set cheats in a creative world where I certainly want to cheat, it is then set in my survival world as well, where I would rather not cheat).
