### ISSUE TITLE
Incompatibilities with mods that modify the inventory status effect display

### ISSUE THREAD

**Issue by ChrysanthCow** [emilyploszaj/emi#134]
**What happened?**
Within my mod Bovines and Buttercups, I noticed that my effect's icon was only rendering the base potion sprite (the lock) within the inventory screen whilst I had EMI's effect moving set to true.

**Potential Solution**
I'm just going to request moving the effect rendering changes outside of the mixin so others are able to modify the recreated method that you made.

### With moved effects (This should show the vanilla effect that the lockdown is associated with)
![image](https://user-images.githubusercontent.com/81167232/215277815-f4f3cb0f-c7ba-4381-bc14-34138ec249cb.png)

### Without moved effects
![image](https://user-images.githubusercontent.com/81167232/215278205-6edf226e-96e8-496d-881e-fb5448b6428f.png)

**Comment by emilyploszaj** [comment]
EMI effect moving is currently definitely annoying for compat, I've been meaning to try and find a more permanent solution, moving logic outside of the mixin is *technically* a solution but I don't know how permanent this code is and treating it as API and suggesting people mixin to it could be troublesome, I'll try to figure out a better solution.

**Comment by emilyploszaj** [comment]
I've made some changes to how EMI draws effects to reuse vanilla routines in slightly less standard ways, and it appears I've resolved the issue on my end. In addition, I've moved the logic into a specifically named internal method, in case other mods require more specific adjustment.
![image](https://user-images.githubusercontent.com/14813658/215299385-767b398b-de02-464f-bd99-07bcb97bc74f.png)
![image](https://user-images.githubusercontent.com/14813658/215299406-fc124388-374b-4c8a-a819-3058e6e40d89.png)

**Comment by ChrysanthCow** [comment]
Thank you
