### ISSUE TITLE
Create Assembly sequencing not visible

### ISSUE THREAD

**Issue by piebaker** [emilyploszaj/emi#137]
Any create recipe that requires a sequence, ie sturdy sheets, train casings, precision mechanisms, andesite casings do not show in EMI.
They are simply-non selectable :(

**Comment by emilyploszaj** [comment]
This is an issue with create, not EMI.

**Comment by LemmaEOF** [comment]
This is likely the Create/Farmer's Delight bug again. If you have Farmer's Delight installed, please comment on [this pull request](https://github.com/newhoryzon/farmers-delight-fabric/pull/116) that you would like it to be merged.

**Comment by piebaker** [comment]
> This is likely the Create/Farmer's Delight bug again. If you have Farmer's Delight installed, please comment on [this pull request](https://github.com/newhoryzon/farmers-delight-fabric/pull/116) that you would like it to be merged.

Cheers, that's exactly it. Farmers delight+create. Keep getting the run around on issue tracking, each dev saying it's something else, so good to finally find the root issue.
