### ISSUE TITLE
EMI experienced a critical exception while reloading, check log

### ISSUE THREAD

**Issue by Greg-J** [emilyploszaj/emi#139]
I have had no issues with EMI but it seemingly quite working and I'm not sure what the cause is. I get that error when viewing the inventory screen and it produces this log: https://mclo.gs/Zgx9QVV

I'm going through disabling mods and datapacks, but it is so strange to me.

**Comment by emilyploszaj** [comment]
There seems to be a lot of broken recipes in this log, but I don't see anything about EMI. I will note you have both create and farmer's delight, the latter of which has been breaking create for months. However I don't think that's the only problem here.

**Comment by Greg-J** [comment]
I have no idea what happened. I restored an older backup with the exact same modpack and datapack used in the save. So a config setting or file somewhere was what caused it. Which is extremely confusing.

**Comment by emilyploszaj** [comment]
Closing since resolved.
