### ISSUE TITLE
[Request] Compatibility with nbt-crafting

### ISSUE THREAD

**Issue by sisby-folk** [emilyploszaj/emi#14]
[Siphalor/nbt-crafting](https://github.com/Siphalor/nbt-crafting) provides the ability for datapacks to create recipes that require or modify item NBT. This includes adding new smithing/brewing/anvil recipes, or just through the crafting table.

These recipes don't show up in EMI. For whichever reason.

I'm unclear on the logical conclusion of "who writes the integration / sets the standard for who" here, but we figured we'd start here.

**Comment by sisby-folk** [comment]
So, shockingly, some NBT-crafting recipes already appear in EMI!

Normal Recipe:
![image](https://user-images.githubusercontent.com/55819817/180709763-de5e25f2-1632-4422-80ad-e97cf45fa04f.png)

NBT Recipe that saves the axolotl bucket NBT to the remainder:
![image](https://user-images.githubusercontent.com/55819817/180709961-2ced95dd-5b37-4518-af76-615ed327cefc.png)

Other recipes like custom smithing and brewing recipes don't appear. 
There may be some that do already I haven't listed - I don't have anvil recipes, and crafting table recipe support might be mixed (I don't have an nbt ingredient, nor result - *just* a remainder)

It's likely some funky API integration is required to get these to appear, but I'm leaving this issue open in case more needs to  be added to the API, which feels likely considering it's a difficult edge case for EMI's design.

**Comment by LemmaEOF** [comment]
Some funky API integration would be required to get them to appear indeed - NBT Crafting modifies the vanilla recipe code in ways EMI can't really see without explicitly depending on NBT Crafting to look for them.

Recipe remainders will always be accurate in EMI, no matter what type of weird injections are made to alter them - it simulates crafting the recipe and getting the remainders to see what they are.

**Comment by sisby-folk** [comment]
Ah, that's enlightening! thanks for the info.

There's some things that could be open to movement on the EMI side
admittedly. The concept of "declare a new brewable potion" isn't too
uncommon to be api-accessible.

I should probably see if my smithing-repair datapack actually *needs* to
use the `nbtcrafting:smithing` type instead of vanilla's, as well...

**Comment by sisby-folk** [comment]
I think the [issue on nbtcrafting](https://github.com/Siphalor/nbt-crafting/issues/114) supersedes this one, and if an API change needs to be made it can probably be made with a new issue, so I'm gonna close this.
