### ISSUE TITLE
EMI stealing focus even when turned off

### ISSUE THREAD

**Issue by Abalieno** [emilyploszaj/emi#140]
I've started to have an issue using REI where if I right click on the search bar to clear it, I cannot type anything until I exit and enter again the inventory. I thought it was REI having focus problems, but it's instead directly depending on EMI.

If I turn on the EMI UI what I typed on the REI search bar, but wasn't shown, appears instead in EMI's own search bar.

I think the same might happen when pressing R or U while hovering on the right panel item list.

I need to have both REI and EMI for compatibility reasons, and I toggle them on/off with their respective shortcuts.

The problem EMI has is that it steals focus even when it's "off". What it should do, instead, is to disable its own UI-related shortcuts, if EMI UI is turned off. So the search bar and recipe shortcuts. It doesn't make sense to have the shortcuts active while the UI is switched off (outside of the shortcuts to toggle the UI itself, of course).

**Comment by emilyploszaj** [comment]
Oops. Turns out this was a 1 line mistake. Fixed locally, I'll close when it's released.

**Comment by emilyploszaj** [comment]
Should be resolved (or at least improved) in 0.6.4
