### ISSUE TITLE
Support FTB Mods

### ISSUE THREAD

**Issue by HySand** [emilyploszaj/emi#142]
Support FTB Chunks, FTB Teams, FTB Quests...
They provide sidebars which may block EMI‘s left sidebar
![p](https://user-images.githubusercontent.com/77628540/218179660-d396c2fb-4980-45a0-8d5a-3fa3f5904f09.PNG)
I move EMI left sidebar down as a temporary solution, but it can't keep parallel with the inventory when changing resolution

**Comment by emilyploszaj** [comment]
Integration of exclusion areas is the responsibility of individual mods, in this case, FTB. Please check if they have an issue open for this, and if not, open one there.

**Comment by walksanatora** [comment]
for those who find this the FTB quest issue is FTBTeam/FTB-Mods-Issues#312
