### ISSUE TITLE
Some items not rendering on first open when running with Sodium

### ISSUE THREAD

**Issue by fun840** [emilyploszaj/emi#143]
I'm running Minecraft 1.19.3 with EMI `0.6.3+1.19.3` (latest) and Sodium `0.4.9-build.23` (latest). The only other mod is Fabric API. All of this is reproducible (at least for me) in a fresh install of 1.19.3.

### Problem

Every time I join a server or load into a world, the first time I open my inventory, most items don't render, but a few still do. Here's a screenshot:
![image](https://user-images.githubusercontent.com/66417988/218321826-67e88ab9-e7c3-4125-9adf-1d99e281bab0.png)
If I switch to the second page, more items also don't load in on that page, but if I switch back to the first page, everything is back to normal.

The logs are short and don't have any errors or related warnings, but just in case, I uploaded them [here](https://mclo.gs/ns5FPOb).

**Comment by emilyploszaj** [comment]
This is related to a recent Sodium update that broke rendering in a handful of mods to get more performance out of vanilla. EMI will have to update to work around this, should expect it for the next update.

**Comment by emilyploszaj** [comment]
Since the batched renderer disables itself when Sodium is present, this is now fixed
