### ISSUE TITLE
Option to change the container height instead of vertical margin

### ISSUE THREAD

**Issue by LucasOe** [emilyploszaj/emi#144]
With different screen- or gui-sizes the user needs a different vertical margin so recipes appear correctly. Because of this the user will have to edit the EMI settings every time he changes the gui size. I think a cleaner solution would be an option to change the height of the recipe container itself, instead of the vertical margin around it, just like it's done with the width.

Personally I would like to see the same border width for every recipe. Meaning, a recipe for create would have a slightly larger container than a recipe requiring a crafting table for example. But I'm not sure if that would be possible to implement.

**Comment by emilyploszaj** [comment]
This is a good idea, I think it's good to have both a max height and vertical margin setting for the recipe screen. When it comes to border width, that's unfortunately on the end of mod implementation. EMI tries to remain relatively consistent itself and generally goes for small displays to fit inside of tooltips comfortably.

**Comment by emilyploszaj** [comment]
This issue is superseded by #208 since it contains this issue and slightly more. I'll be closing this one and tracking the other.
