### ISSUE TITLE
Latest version for 1.18.2 crashes (Mod Incompat?)

### ISSUE THREAD

**Issue by ConqAra** [emilyploszaj/emi#145]
Log: [https://paste.ee/p/F1JDe](https://paste.ee/p/F1JDe)

**Comment by emilyploszaj** [comment]
Is this a change just with the latest version? It doesn't seem to have anything to do with EMI from a cursory glance.

**Comment by emilyploszaj** [comment]
Nope I've found it, this is a slotlink issue, they mixin to EMI
