### ISSUE TITLE
[Bug] Workstation Does Not Support Recipe

### ISSUE THREAD

**Issue by greensad** [emilyploszaj/emi#146]
On all recipes both vanilla and modded.

Log: https://paste.ee/p/P7tYF

**Comment by emilyploszaj** [comment]
This tooltip is displayed when you're hovering the fill button in a workstation that doesn't support the filling, like a smelting recipe inside of a crafting table. What screens are you in? Does this happen in furnace recipes inside of a furnace? Crafting recipes inside of a crafting table?

**Comment by greensad** [comment]
This happens on all recipes for all their respective workstations for instance; all crafting table recipes in a crafting table such as logs to planks.

**Comment by emilyploszaj** [comment]
I have a minimal viable environment with the latest version and it appears to be working. Are you able to determine particular mods that are causing this when present?
![image](https://user-images.githubusercontent.com/14813658/220236305-a1d685ea-aa35-400e-8f26-62fd0c769d79.png)

**Comment by greensad** [comment]
> I have a minimal viable environment with the latest version and it appears to be working. Are you able to determine particular mods that are causing this when present? ![image](https://user-images.githubusercontent.com/14813658/220236305-a1d685ea-aa35-400e-8f26-62fd0c769d79.png)

I did a bunch of testing today and found that the mod [Visual Workbench](https://modrinth.com/mod/visual-workbench) is the incompatibility. I should also add that the issue is still present in EMI 0.6.6.

**Comment by erazare** [comment]
Will confirm this as well latest releases of both mods same issue. mind you it WILL fill recipes fine, it just wont allow you to move items from toms inventory to your own and vice versa.

**Comment by ZedZedboi** [comment]
Can still confirm this with the newest version of both mods.

**Comment by emilyploszaj** [comment]
Fixed in 1.0.0
