### ISSUE TITLE
[Feature Request] Previous Search Using 'up' Key

### ISSUE THREAD

**Issue by greensad** [emilyploszaj/emi#147]
Just a feature I miss from REI and JEI, would be nice here. Pressing up enters the last searched text similar to how it works in Terminal/CMD/bash. Pressing up multiple times allows a short history of searches to be cycled through. Pressing down when looking at an older search cycles to a newer search.

**Comment by emilyploszaj** [comment]
Well overdue, implemented in 1.1.2
