### ISSUE TITLE
[1.19.2/Fabric] Unable to interact with items in Toms' Simple Storage UI.

### ISSUE THREAD

**Issue by KateReller** [emilyploszaj/emi#148]
When EMI is enabled, I am unable to pull out items from the inventory screen of [Tom's Simple Storage](https://github.com/tom5454/Toms-Storage).

Logs: https://mclo.gs/NRZmCs0

**Comment by emilyploszaj** [comment]
This is a bug in Tom's Simple Storage, I've found the issue and reported it to the open bug on their github here: https://github.com/tom5454/Toms-Storage/issues/200#issuecomment-1444931435
