### ISSUE TITLE
[Feature Request] Toggle Visibility Button

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#150]
Hi, I love the options for a vanilla-style interface! I've been using it to mimic the vanilla recipe book:
![2023-03-05_17 17 15](https://user-images.githubusercontent.com/108554062/222994608-d8457506-6b6b-4d05-a82c-e88cb7662e30.png)

Do you think it'd be possible to add a clickable button to toggle EMI's interface, or have an option to repurpose the vanilla recipe button to do this? I've always preferred the convenient button for hiding the recipe book interface as opposed to going out of my way to hit a keybind.

**Comment by emilyploszaj** [comment]
I've been considering allowing rebinding the action of pressing the recipe book button, but was unsure if there would be interest, this serves as good note that there are players who would enjoy it

**Comment by emilyploszaj** [comment]
This recipe book feature was added in 1.0.0
