### ISSUE TITLE
Keybinds for copying recipe id and screenshotting

### ISSUE THREAD

**Issue by emilyploszaj** [emilyploszaj/emi#152]
Just general purpose keybinds that work inside the bounds of a recipe box, would probably help people.

**Comment by Saereth** [comment]
just seconding this, its REALLY useful/important feature for packdev to have the copy recipe id keybind in jei working. Presently we have to disabled emi while in development to use this feature.

**Comment by emilyploszaj** [comment]
Keybinds for recipe ID have been added as of 1.0.28 and recipe screenshot keybinds have been retracted as a goal as they are unviable.
