### ISSUE TITLE
Interaction with Tom's Simple Storage Mod

### ISSUE THREAD

**Issue by rekkep** [emilyploszaj/emi#158]
When EMI is active and used with Tom's Simple Storage you cant take Items out of the Storage terminal

**Comment by fzzyhmstrs** [comment]
Are you using version 1.5.1 or later of Tom's Simple Storage? That version was supposed to fix a known issue with taking from the terminal

**Comment by rekkep** [comment]
> 

I was using 1.5.0, With version 1.5.3 its fixed, thanks
