### ISSUE TITLE
[Bug & API Request] Virtual Fluids are Displayed in World Interaction

### ISSUE THREAD

**Issue by Phoupraw** [emilyploszaj/emi#159]
Virtual fluids (fluids that can't be poured into the world but can only be used in recipe and storage) which have corresponding bucket item are displayed in world interaction category, though they can't exist as fluid block in the world. For example, milk fluid of Milk Lib, when `io.github.tropheusj.milk.Milk#enableMilkPlacing` hasn't been invoked.
![mc virtual fluid world interaction](https://user-images.githubusercontent.com/50520903/228516019-6446052a-c659-452b-813f-be62a1752bef.jpg)
In my mod, `net.minecraft.fluid.WaterFluid#toBlockState` of virtual fluids always returns empty block state (`Blocks.AIR.getDefaultState()`).  But Milk Lib doesn't so: it uses a static final boolean variable to determine whether vanilla milk bucket is able to place milk. So a more general and compatibale API is needed, maybe a fluid tag, an interface for fluid class, a `net.fabricmc.fabric.api.lookup.v1.custom.ApiLookupMap`, or something else.

**Comment by emilyploszaj** [comment]
Fixed in 1.0.0
