### ISSUE TITLE
[Bug] Some Recipes have no ID

### ISSUE THREAD

**Issue by Nataly171** [emilyploszaj/emi#163]
Certain recipes don't have an ID in EMI, and thus can't be hidden with filters. This includes, but may not be limited to:
- Repairing items in Crafting Table
- Repairing items in Anvil
- Applying Enchantments in Anvil
- Repairing items in Grindstone
- Disenchanting items in Grindstone
- Dyeing items such as Leather Armor
- Washing items such as Leather Armor in a Cauldron
- Copying Banners

This bug also extends to recipes of modded items, such as repairing and enchanting modded equipment.

Note that despite the fact that Recipe IDs are enabled, no Recipe ID is shown in the second screenshot.
![image](https://user-images.githubusercontent.com/109003930/230521071-63db4b35-ba71-4a46-8bc2-7871775fbf66.png)
![image](https://user-images.githubusercontent.com/109003930/230521097-1284ae33-df6f-4e8f-8063-283ca04da565.png)

**Comment by emilyploszaj** [comment]
I think it'd be a good idea to give these recipes synthetic recipe IDs for the upcoming 1.0.0 release.

**Comment by emilyploszaj** [comment]
Fixed in 1.0.0
