### ISSUE TITLE
[Feature Request] Add category for furnace fuels

### ISSUE THREAD

**Issue by TheRealWormbo** [emilyploszaj/emi#164]
While the fuel consumption of furnaces isn't exactly "a recipe", there are various blocks among vanilla Minecraft (furnace, blast furnace, smoker) and mods (e.g. Botania's Endoflame, Create's Blaze Burner) that consume fuel items, and many mods that add new fuel items. It seems only logical that a mod for presenting information about obtaining and using items also presents an overview of what fuel items can be used.

Fuel items would probably still be excluded from all kinds of smelting recipes, but it'd be nice to have information collected in one place about how long a furnace would run with various fuels and what items a furnace could actually be fueled with. Bonus points for allowing other mods to add more blocks that can consume standard fuel items to have that list show up, e.g. when you look for usages of an endoflame or blaze burner.

**Comment by emilyploszaj** [comment]
Added in 1.0.0
