### ISSUE TITLE
[Feature Request] Favorite/Default Tag Items

### ISSUE THREAD

**Issue by cplir-c** [emilyploszaj/emi#165]
I've been playing with Yttr recently, and it adds tags for things like iron, redstone, and gold. Whenever I used them in a recipe tree, it does not resolve by default.
I would want to pick vanilla iron, redstone, and gold to resolve those tags, and regular vanilla glass for the glass tag for example.
At the moment, I can select tag resolutions within one recipe tree, but they're not savable as a default across multiple trees.

**Comment by emilyploszaj** [comment]
Added in 1.0.0
