### ISSUE TITLE
[Bug] Hidden items still show automatically generated recipes

### ISSUE THREAD

**Issue by Swedz** [emilyploszaj/emi#166]
Items with the `c:hidden_from_recipe_viewers` tags still show for automatically generated recipes like:
- two tools crafted together in a crafting grid to repair it
- anvil repairing
- grindstone repairing
- grindstone disenchanting

For example:
![image](https://user-images.githubusercontent.com/6707125/233508151-2face46f-b01e-4d71-a275-94cfe6b7caa8.png)
![image](https://user-images.githubusercontent.com/6707125/233508168-69c1e002-d5a1-4a6c-b260-a8b3e4512954.png)
![image](https://user-images.githubusercontent.com/6707125/233508192-1a747262-18a7-4168-b161-c7c5601c802b.png)

**Comment by emilyploszaj** [comment]
Fixed in 1.0.0
