### ISSUE TITLE
Tags that only have entries with `#c:hidden_from_recipe_viewers` should not be shown

### ISSUE THREAD

**Issue by Technici4n** [emilyploszaj/emi#169]
![image](https://user-images.githubusercontent.com/13494793/236930385-86e5e0ad-860f-448f-af51-1ed50f155993.png)
![image](https://user-images.githubusercontent.com/13494793/236930424-80ce3d11-b6f5-4d28-a6db-8e7c761b8a51.png)

All the fluid pipes are disabled, but the tag still shows up in EMI.

**Comment by emilyploszaj** [comment]
This behavior was adopted for 1.0.0
