### ISSUE TITLE
[1.19.2] [Forge] EMI not Recognising  crafting inventories

### ISSUE THREAD

**Issue by ffuentesm** [emilyploszaj/emi#174]
I am trying to use the Storage Lecturn from Ars and Crating Terminal from Simple Storage, but EMI does not recognize it as a valid inventory space, so the recipe book shows as if it's empty. 
And even quick crafting does not recognize non-Player inventories as available space.
![image](https://github.com/emilyploszaj/emi/assets/44974827/c1df0339-bc34-4a6a-a46a-02762478f76a)
![image](https://github.com/emilyploszaj/emi/assets/44974827/0bdb2a6a-d39d-425e-93a5-40e63dd2345f)

**Comment by emilyploszaj** [comment]
Unfortunately this is the kind of issue that would need to be resolved by mods themselves adding EMI integration. JEI's information for recipe filling is not structured in a way that can be used by EMI particularly for craftables.
