### ISSUE TITLE
[1.19.2] [Fabric] Support modded tooltip components

### ISSUE THREAD

**Issue by l-Luna** [emilyploszaj/emi#175]
EMI 1.0.0 only uses `TooltipComponent.of` to handle tooltip data, which bypasses FAPI's `TooltipComponentCallback` entirely, causing modded tooltip components not to show up in EMI (and spam the log with error messages).

One fix is for EMI to trigger the event itself, though xplat might make that non-trivial.

**Comment by Technici4n** [comment]
Now that mixins can inject in interfaces, Fabric should move its inject to `TooltipComponent.of` directly. I'll PR the fix to Fabric shortly.

**Comment by emilyploszaj** [comment]
EMI originally invoked the lambda methods in `Screen` to capture all of these tooltip components, but in the migration to forge there were some unresolveable issues. It may be reasonable to simply have the functionality of the two loaders diverge and call the Screen lambda on fabric, I'll look into it properly

**Comment by emilyploszaj** [comment]
Re-added this behavior specifically for 1.19.4 and below fabric in 1.0.5
