### ISSUE TITLE
[Feature Request] Suggestions & Forge / JEI related things

### ISSUE THREAD

**Issue by SiverDX** [emilyploszaj/emi#176]
Option to configure this part:
![image](https://github.com/emilyploszaj/emi/assets/22003703/ac0ebbf3-c298-40bc-9810-05523b074737)

I have a lot of entries there so it's hard to go through them with EMI
JEI has an option to scroll by groups (I'm using Forge EMI with JEI so maybe you also have that feature functional in Fabric):
![image](https://github.com/emilyploszaj/emi/assets/22003703/c921f910-276e-4cfd-9414-5823941a8700)

---

Add an option to hide `Enchanted Book` level variants to de-clutter the list
(Only show the lowest or highest level)

(I think one could do this manually by hiding all of them but it would be cool to have it as an easy config)

---

Just FYI regarding Forge version - JEI Plugins seem to work:
* Just Enough Professions
* Just Enough Resources
* Just Enough Effect Descriptions
* JER Integration

but the loot tables from `Just Enough Resources` overwrite the `Shift` tooltip for craftable items
(I'm not sure if this is doable but it would be better if the crafting takes priority)
(It also only shows the first entry of `Just Enough Resources` but maybe cycling through them in the tooltip does not look good)

---

The recipes added from this mod: https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks
https://github.com/iron431/Irons-Spells-n-Spellbooks/tree/1.19.2/src/main/java/io/redspace/ironsspellbooks/jei

are having problems - normally each scroll has it's own combination entry for the `Arcane Anvil` but with EMI only the highest tier has one and you can scroll through the lower ones (the scrolling gives you a random next entry so you go from level 1 to 3 to 2 to 5 etc.)

This also means that the recipe tree only shows the recipe for the highest level

---

Items are missing the `Information` entry from `JEI`, but not all of them
It works for 
* https://www.curseforge.com/minecraft/mc-mods/artifacts
* https://www.curseforge.com/minecraft/mc-mods/arcane-lanterns

But not for
* https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

**Comment by emilyploszaj** [comment]
I'm gonna close this issue because there's a lot going on in it and the individual parts are all either resolved or better tracked by an existing individual issue.
