### ISSUE TITLE
Mild incompatibility with Just Enough Effect Descriptions

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#181]
![image](https://github.com/emilyploszaj/emi/assets/15698722/df8fba5c-34e2-414e-973c-f3190eed0fc3)

Hovering over where a potion effect usually is in your inventory will show its tooltip, despite it being moved somewhere else.

![image](https://github.com/emilyploszaj/emi/assets/15698722/68b165f7-b883-417b-a6f6-7c88a7536ae7)

https://github.com/emilyploszaj/emi/assets/15698722/0436a7d6-089f-4fe3-a314-59730ebfc239

emi-1.0.0+1.19.2+forge

**Comment by emilyploszaj** [comment]
This video actually seems to showcase three separate issues.
* The first one, and the one EMI can trivially fix: stacks are rendering tooltips in generic exclusion area (on pages other than the first), visible in the video. This is a simple logic error made by some changes in sidebar calculations, and I'll be sure to fix it.
* The second one, which is likely outside of EMI's control, is the tooltips rendered where effects aren't. EMI makes sure to diligently reuse vanilla codepaths in its mixin for moving effects around, and it appears JEED's effect location calculation is naive, which will either require an adjustment of logic on their side, or integration with EMI (using implementation classes, which is undesirable)
* The third one, potentially outside of EMI's control and more minor, is the double tooltip when hovering compressed effects. In vanilla, hovering a compressed effect (which happens on thin screen sizes) causes the effect to display a tooltip of remaining time. It may be possible EMI's method of compression is not being detected by JEED, or JEED may simply not recognize this vanilla behavior. This would also be resolved by JEED being more particular with its location detection.

I believe I'll be closing this issue when I've resolved and released the first of three listed, and will open an issue on JEED regarding the latter two.

**Comment by emilyploszaj** [comment]
I worked together with MehVahdJukaar and wrote a mixin for them which has better detection for both EMI and any mods that have other functions like this, this version of JEED has been released. Including some local changes, I've been able to confirm it works perfectly with EMI's settings now.
![image](https://github.com/emilyploszaj/emi/assets/14813658/75957f08-c5c7-4e56-ac37-9b4a0cf4e2c4)
This solves the second and third issues, and I'll plan a release later today resolving the first, kinda shocked with how fast this collaborative turnaround went :sweat_smile:

**Comment by SiverDX** [comment]
So is this part of the first mentioned problem?
![image](https://github.com/emilyploszaj/emi/assets/22003703/504b6a40-c1b0-4e5c-9b19-018215f3f36e)

Can't see my mouse but I'm hovering left to the red pickaxe
The item that the tooltip is from is on the second page (this is the third)

**Comment by aaronhowser1** [comment]
Amazing work! Tysm

**Comment by emilyploszaj** [comment]
All 3 issues have been resolved here and JEED integration should work perfectly, including in the case that EMI moves effects to the top of the inventory starting in 1.0.1
