### ISSUE TITLE
loosing connection to single player worlds

### ISSUE THREAD

**Issue by Nitron-picarla** [emilyploszaj/emi#182]
this is 100% just an incompatibility with another mod but i found it strange enough to at least ask if this has been seen before.
when attempting to load into a single player world the screen goes completely black, the mouse becomes visible, and after 8 seconds the following message appears

connection lost
Internal exception : java.lang.NoClassFoundDefFoundError: dev/emi/emi/emireloadmanager
back to server list
(clicking back to server list takes me to the multiplayer server list)

using quilt 1.19.2 client with emi 1.0.0 1.19.2 fabric/quilt. i've never seen an error like this, with the game confusing whether im in single player or not.

**Comment by Bluberry-Kat** [comment]
One of the mods in your modpack uses Polymer.  
Polymer uses EMI internals and (uniquely) broke in the 1.0.0 update; install Polymer-0.2.28 and it should be fixed.

**Comment by emilyploszaj** [comment]
Kat was correct, as Polymer uses EMI internals it occasionally breaks when it shouldn't. Polymer is often included by other mods, but if you include your own updated version, it should fix this issue.

**Comment by Nitron-picarla** [comment]
works perfectly now, thank you very much.

**Comment by WimpieRatte** [comment]
Bluberry-Kat, you legend! That was the fix I needed as well. Thank you! :D
