### ISSUE TITLE
If an item CAN have the searched text in the tooltip, it's shown, rather than if it DOES have the text

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#183]
![image](https://github.com/emilyploszaj/emi/assets/15698722/ffd82cd9-8a95-4784-9687-eaad80fb55f5)
![image](https://github.com/emilyploszaj/emi/assets/15698722/f72d99ad-cfd6-462f-983e-4f444cb6a7d7)
Both of the above searches show every Syringe, which can be set to any LivingEntity. Searching for any LivingEntity's name shows all Syringes.

![image](https://github.com/emilyploszaj/emi/assets/15698722/074ed2f3-767f-4667-b1aa-7c7a7755c22e)
Searching any potion effect shows every variation of any item that can have that in the tooltip.

emi-1.0.0+1.19.2+forge

**Comment by emilyploszaj** [comment]
I've been trying to figure out what causes this for a while, and now I believe it may have to do with comparison strictness. This could be resolved for the index using identity comparison, but would mess with the ability to search other sidebars.
I believe a compound resolution to this issue would function best:
* When doing baked lookup, use strict nbt comparison with cached values
* If this fails, recheck the state of the tooltip for the live stack

I'll look into implementing it

**Comment by emilyploszaj** [comment]
This solution was implemented in 1.0.1
