### ISSUE TITLE
Crash when looking at a recipe

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#186]
https://gist.github.com/aaronhowser1/57f666eb4a7170f75fe72c1c278b573e

It was a random sign from Engineer's Decor, but I can't replicate it

emi-1.0.0+1.19.2+forge

**Comment by emilyploszaj** [comment]
Stacktrace seems to indicate it's the same issues as present in #179 which has been resolved in dev by modernfix. I assume their next release will be soon so I'll close this bug as a duplicate
