### ISSUE TITLE
emi:fuel is white instead of orange

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#187]
![image](https://github.com/emilyploszaj/emi/assets/15698722/247a54f6-ecab-4786-a677-58e0de8c7379)
Idk of this is actually an issue, but the white kind of blends into the background and usually it's using the fully-fueled furnace gui texture

**Comment by BookerCatch** [comment]
Judging from

[xplat](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat)/[src](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src)/[main](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main)/[resources](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main/resources)/[assets](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main/resources/assets)/[emi](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main/resources/assets/emi)/[textures](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main/resources/assets/emi/textures)/[gui](https://github.com/emilyploszaj/emi/tree/1.19.4/xplat/src/main/resources/assets/emi/textures/gui)/widgets.png

It's very likely that this is intended to fit with all the other modern-styled white glyphs representing different crafting operations. It's just very unfortunate that it blends in. If desired, you can edit widgets. The glyph in question is at the bottom right.

**Comment by emilyploszaj** [comment]
The fuel icon is actually just a reuse of the simplified (recipe tree) icon for smelting. The reason it's white is... I haven't given it time to actually make a proper icon, but considering I do have a flame in my textures I might as well switch to the higher contrast version to make it more readable, I agree.

**Comment by emilyploszaj** [comment]
This was tweaked, the icon is now the full burning orange starting in 1.0.1
