### ISSUE TITLE
Recipe filling will not use different inputs for the same ingredient

### ISSUE THREAD

**Issue by yrsegal** [emilyploszaj/emi#19]
I had six jungle slabs and 3 oak slabs, but the recipe for a Composter wouldn't fill. Other recipes, such as Hay Bale, filled fine.

**Comment by emilyploszaj** [comment]
I thought I achieved parity with the recipe book when I implemented this, but it turns out not, I may have broken it recently, good catch.

**Comment by emilyploszaj** [comment]
Finally got around to this, fixed in 0.4.0
