### ISSUE TITLE
JEMI crash when clicking 'Show All Recipes' in Inventory when BetterX mods are present

### ISSUE THREAD

**Issue by lxly9** [emilyploszaj/emi#191]
As the title states an EMIAnvilRecipeCategory error occurs when clicking the 'Show All recipes' button in the inventory. This only happens when BCLib/BetterX mods are installed. I have opened an [issue](https://github.com/quiqueck/BCLib/issues/96) on BCLib's Github but wanted to report it here too.
[Log](https://mclo.gs/65cxXxq)

**Comment by lxly9** [comment]
Ive created forks of the BetterX mods, they can be built from the forks in my github. I recommend using these until BetterX plugins get updated.

**Comment by Shibva** [comment]
It seems like the issue has todo with the empty recipes the mod generates

Not only that this occurs as well with just EMI without JEI

**Comment by lxly9** [comment]
Its the faulty EMI plugin in BetterX Mods, the latest releases of my forks of the mods address the issue by disabling the whole plugin and relying on BetterX JEI plugins to be displayed in JEMI.

**Comment by emilyploszaj** [comment]
EMI has attempted to add more data integrity to fix this crash from occurring in 1.0.2, even though the issue itself is on the part of BetterX.
