### ISSUE TITLE
Forge: Items with really long JEI info strings do not split into mulitple pages

### ISSUE THREAD

**Issue by Vazkii** [emilyploszaj/emi#192]
JEI automatically splits long strings into multiple pages

![image](https://github.com/emilyploszaj/emi/assets/1794735/7d6ff1a2-79a6-48b1-9621-6d50eff45663)

**Comment by Vazkii** [comment]
![image](https://github.com/emilyploszaj/emi/assets/1794735/4559f889-55b1-40d6-9b89-c17bdcdbd305)

Additionally, for items that do explicitly have multiple pages registered, it merges them.

**Comment by emilyploszaj** [comment]
I forgot to close this, but it was resolved. The multiple pages issue was actually... a texture problem. As for the merging, there's nothing EMI can do to distinguish a multipage description and 2 different descriptions from JEI so it is acceptable
