### ISSUE TITLE
(safe) Simple Storage Network Inventory not recognized 

### ISSUE THREAD

**Issue by SmRzT** [emilyploszaj/emi#194]
EMI Forge 1.0 1.19.2

Cannot use items inside the Network as they are recognized/EMI dosent know they exist ig in a way.(says in emi not enough materials or something altough they are there)

When having items in Inventory it will try to insert to items into the crafting grid but its kinda hit or miss as sometimes items dont go in grid

**Comment by ffuentesm** [comment]
This is happening to all storage mods. 
Up till now only Toms Simple storage seems to be half working

**Comment by emilyploszaj** [comment]
I've definitely been able to use AE2

**Comment by SmRzT** [comment]
RS dosent work either, i assume that is know tho

**Comment by emilyploszaj** [comment]
This has been further fixed in EMI 1.0.2, tested for both Refined Storage and Simple Storage Network, should work for all other mods.
