### ISSUE TITLE
[1.19.2 Forge] EMI conflict with Create's toolboxes

### ISSUE THREAD

**Issue by Tlp300** [emilyploszaj/emi#197]
Having both EMI Forge and Create installed seems to break Create's toolbox GUIs.

EMI version: 1.0.1
Create version: 0.5.1b

Steps to reproduce:

1. Install EMI and Create on Forge.
2. Go into a world, give yourself a Create toolbox.
3. Place toolbox down, right click. GUI does not open.

Forge version: 43.2.11

https://gist.github.com/Tlp300/e4985aac8e659d289a422762ad527424 Log attached, did not appear to have anything though.

**Comment by ArkVeil** [comment]
I have also reproduced this bug on 1.19.2 Forge version 43.2.3. 

Create version: 0.5.1.b
EMI version 1.0.1 forge

**Comment by PlatinumPlatedPizza** [comment]
same thing here

Create version: 0.5.1.b
EMI version 1.0.2 forge

**Comment by Radu-Robu** [comment]
Issue still ongoing.

Forge version: 43.2.8
Create version: 0.5.0.i
Emi version: 1.0.3 forge
Minecraft version: 1.19.2

**Comment by SiverDX** [comment]
To add on this:
Visibility of EMI has no effect on this (meaning if you disable EMI the screen will still not show)

The toolbox stays open even if you go away from it or press `ESC`
It only closes itself when you open another screen (e.g. the inventory, another container or another toolbox)
(Unloading the chunk also works)

**Comment by emilyploszaj** [comment]
Finally was able to figure out this problem, sorry for the long period of time it was broken, but this is fixed in 1.0.5
