### ISSUE TITLE
Allow searching with `_` for mod entries

### ISSUE THREAD

**Issue by SiverDX** [emilyploszaj/emi#200]
![image](https://github.com/emilyploszaj/emi/assets/22003703/2596ae9c-dcb0-4c82-b8c7-3ffec8914120)

Searching:
![image](https://github.com/emilyploszaj/emi/assets/22003703/0e41f6c0-73a3-4e5f-932b-979e4990434f)

Result:
![image](https://github.com/emilyploszaj/emi/assets/22003703/9bc81667-60b1-444d-adda-50888edb6c23)

When I just search `@create` I can find the entries (but also stuff from other mods that have `create` in their mod-id

Another example: `create_enchantment_industry` - if I search for `industry` I can find the entries but not if the search string includes `_`

**Comment by emilyploszaj** [comment]
This is because you're not actually searching mod ids, you're searching mod *names*, which have spaces.

**Comment by SiverDX** [comment]
Oh yeah, that is true - can see that it works when I do that
Was a bit confused by the coloring:

![image](https://github.com/emilyploszaj/emi/assets/22003703/02b79b38-4b40-4176-89e9-9280f12914a3)

**Comment by emilyploszaj** [comment]
I think that's not actually working, if you want to match things with spaces you can do `@create @enchantment @industry` to match all the words but no spaces, or use a regex search like `@/create enchantment industry/`, to actually match the spaces, which isn't necessary in most cases. Do be noted that using regex is less performant, but it is a solution for pattern matching searches.

**Comment by SiverDX** [comment]
Oh yeah I can see that, seemed like the last entry or so was what actually filtered the rest out (since no mod had a similar entry in their name)

Thanks, guess this can be closed then
