### ISSUE TITLE
GUI doesn't render inside Sophisticated Chest/Backpack

### ISSUE THREAD

**Issue by FreeFull** [emilyploszaj/emi#203]
Forge version: 43.2.13
EMI version: 1.0.1+1.19.2+forge
Sophisticated Core: 1.19.2-0.5.57.275
Sophisticated Storage: 1.19.2-0.8.5.402

When a Sophisticated Chest or Backpack is open, EMI's GUI fails to render. However, EMI's GUI is still clickable. EMI's GUI does render if one clicks the cog for the Sophisticated Chest's settings.
![image1](https://github.com/emilyploszaj/emi/assets/1496908/7f6923e4-add0-4d0b-9dcf-db5b20b451a2)
![image2](https://github.com/emilyploszaj/emi/assets/1496908/8133136c-b751-472d-b8f5-fce2abf65df8)

**Comment by FreeFull** [comment]
[latest.log](https://github.com/emilyploszaj/emi/files/11644289/latest.log)
[debug.log](https://github.com/emilyploszaj/emi/files/11644290/debug.log)
Logs

**Comment by emilyploszaj** [comment]
Fixed in EMI 1.0.7
