### ISSUE TITLE
EMI menu is visible in EvilCraft's book gui

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#205]
I originally made an issue on their tracker here CyclopsMC/EvilCraft/issues/985 but they said to put it here instead

**Comment by emilyploszaj** [comment]
EMI by default shows up in its own screens, and any Handled/Container/Menu/Inventory Screen (the ones with the slots). There's otherwise no indication that EMI shouldn't treat this screen as normal so I'm not sure how EMI is supposed to detect this screen is not properly suitable...

**Comment by Patbox** [comment]
EMI could in theory check against slot count, as any ui with less than player inventory size likely won't allow crafting. This one seems to not have a single slot defined

**Comment by fzzyhmstrs** [comment]
If a screen doesn't have any slots, it probably shouldn't be a `handled screen`.

**Comment by emilyploszaj** [comment]
This was fixed in 1.1.0, screens without slots no longer render in EMI.
