### ISSUE TITLE
[Forge 1.0.2+1.19.2] Epileptic JEP Villagers

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#207]
Installing Just Enough Professions makes the villagers in the recipe view exhibit less-than normal behavior.

https://github.com/emilyploszaj/emi/assets/43504436/108ad34f-8918-44eb-a427-1c5b6d9c883b

**Comment by SiverDX** [comment]
I am somewhat confident that this is an issue with `Fresh Animation` and JER itself

I had this issue without EMI and now without `Fresh Animations` I don't have it with EMI

**Comment by emilyploszaj** [comment]
Because of that I don't think this is on EMI to fix, going to close.
