### ISSUE TITLE
[1.19.2 Fabric] Modern Industrialization incorect number of items in recipe when items are grouped.

### ISSUE THREAD

**Issue by Kokuhatsu** [emilyploszaj/emi#210]
If machine recipe require multiple items per slot it's not counted correctly in EMI.
It looks like only item type per slot is counted for input.
However output and used fluids are calculated correctly.

Mods versions are in the last screenshot.

link to recipe in Modern Industrialization repository: https://github.com/AztechMC/Modern-Industrialization/blob/master/src/generated/resources/data/modern_industrialization/recipes/assembler_generated/electric_age/hull/lv_machine_hull.json

REI recipe:
![obraz](https://github.com/emilyploszaj/emi/assets/34172652/d3fe2ffe-b839-4256-86fd-fbefe7825383)
EMI recipe:
![obraz](https://github.com/emilyploszaj/emi/assets/34172652/2e6fa207-facc-4b5c-bdeb-9f1badc65282)
EMI recipe with fluids:
![obraz](https://github.com/emilyploszaj/emi/assets/34172652/4c72f29b-94ba-4f1c-85f4-f370569077a6)

Installed mods:
![obraz](https://github.com/emilyploszaj/emi/assets/34172652/ddc488c1-7cf1-452c-9e51-d0b196374ddc)

**Comment by emilyploszaj** [comment]
I must've broken something silly about counts in a recent update, I'll look into it

**Comment by emilyploszaj** [comment]
Very silly mistake, this was more than visual, fixed in 1.0.3
