### ISSUE TITLE
[FABRIC 1.19.2] When emi is enable the worlds don't open

### ISSUE THREAD

**Issue by Facni** [emilyploszaj/emi#211]
It sais { [java.lang.NoClassDefFoundError dev / emi / emi / Emireloadmanager
Mods:
![imagen](https://github.com/emilyploszaj/emi/assets/112446096/546bab72-72d4-4142-84ab-62e2a1c1416f)
![imagen](https://github.com/emilyploszaj/emi/assets/112446096/459f4141-4649-4bc7-92e0-fd999aaf8507)

**Comment by emilyploszaj** [comment]
I believe you need to download the newest version of polymer, if this is not the case please upload a proper crashlog
