### ISSUE TITLE
[1.20 Quilt] The search box doesn't work

### ISSUE THREAD

**Issue by HitaloM** [emilyploszaj/emi#214]
When I click on the search box simply nothing happens, I checked the logs and found nothing even remotely suspicious, it might be happening because of other mods, but I couldn't identify which one would be conflicting with EMI.

### My mods list:
![image](https://github.com/emilyploszaj/emi/assets/40531911/7d3ce600-03de-475b-80b8-9e18987130a0)

**Comment by emilyploszaj** [comment]
This is resolved in 1.0.3
