### ISSUE TITLE
I don't understand the item searching in this mod

### ISSUE THREAD

**Issue by remidu64** [emilyploszaj/emi#215]
I'm probably just dumb but when I try to search for an item, I often don't get to see it.
For example: when I search for "gunpowder", I expect to see the gunpowder item but instead, nothing shows up.

Could you explain how does the item searching algorithm works in this mod?

**Comment by emilyploszaj** [comment]
Can you provide a more detailed case? Searching "gunpowder" will display gunpowder as expected.

**Comment by remidu64** [comment]
I will send a screenshot of what's happening whenever I can.

**Comment by remidu64** [comment]
![2023-06-14_11 58 43](https://github.com/emilyploszaj/emi/assets/60043514/82e4de06-5ddc-45f9-8196-99ea4c645a66)
![2023-06-14_11 59 04](https://github.com/emilyploszaj/emi/assets/60043514/2d7fef8a-ed31-4d87-b962-f97ebb52919d)

**Comment by emilyploszaj** [comment]
I can't reproduce this issue, there must be something else going on with your setup

![image](https://github.com/emilyploszaj/emi/assets/14813658/03235f77-9e13-4adb-b920-e8773b8dcff4)
