### ISSUE TITLE
[Forge 1.19.2] Critical Exception while Reloading

### ISSUE THREAD

**Issue by Talan67** [emilyploszaj/emi#219]
log: https://pastebin.com/KJ7qZGSM

EMI Version: 1.0.3
JEI Version: 11.6.0.1015
Forge Version: 43.2.11

Error both on Singleplayer and while on a Server

**Comment by emilyploszaj** [comment]
I haven't been able to reproduce this with a good chunk of mods with the provided versions. The log suggests it's a JEI error that's causing issues on EMI's side as well. Regardless, I've added some more safety in 1.0.4 that should hopefully help.
