### ISSUE TITLE
disconnected with "%s" when cheating in oversized nbt items on (vanilla) servers

### ISSUE THREAD

**Issue by 456dev** [emilyploszaj/emi#221]
# reproduction
1. start a vanilla 1.20.1 server
2. in singleplayer, use a command block to give an item, where the nbt is > 256 character long (longer than you can paste in chat)
3. bookmark the item
4. join the server, op yourself (i think?)
5. try to spawn the item with ctrl + left click. ctrl middleclick seems to work as normal, except if in certain guis (crafting table)
6. observe that you disconnect from the server

# error
## in client console
https://paste.ee/p/2XkFT
## on disconnect screen
![image](https://github.com/emilyploszaj/emi/assets/42748092/51457922-ad70-4c54-ae77-ff6407a230bd)

# version
quilt 7.0.3+0.83.1-1.20.1
minecraft 1.20.1
emi 1.0.4+1.20.1

**Comment by emilyploszaj** [comment]
This has been resolved in dev. It will be released along with the 1.20.2 port in the coming days.
