### ISSUE TITLE
[Forge] Recipe trees do not display recipes for items/blocks from mods.

### ISSUE THREAD

**Issue by HLRxxKarl** [emilyploszaj/emi#223]
Tested this in both 1.20.1 and 1.19.2, did not test Fabric. Vanilla recipes still expand in the tree just fine. But if any crafting component comes from a mod, it just hits a dead end, even if it's just a regular crafting recipe using only vanilla components. I've seen this brought up in the Curseforge comments, but didn't see it submitted anywhere here yet. If this issue were resolved, and better yet added support for things like Mekanism machine processes in the tree, I would love this mod so much.
![2023-06-18_23 08 01](https://github.com/emilyploszaj/emi/assets/80851619/6df6dd31-1189-4b9f-ba56-4ab968c38d7d)
![2023-06-18_23 55 59](https://github.com/emilyploszaj/emi/assets/80851619/eb3f433f-43a2-401d-ac1d-8576784e0edb)

**Comment by emilyploszaj** [comment]
This seems to be a misunderstanding of how the recipe tree works. EMI has default recipe expansions for vanilla recipes, and mods can define their own expansions, but primarily you're supposed to be able to set those yourself. The controls are explained in the info section in the corner, but you click a node and can set recipes either temporarily or permanently to expand the tree for exactly what you want to see.
