### ISSUE TITLE
[1.19.2] Incompatibility with MoreCreativeTabs mod

### ISSUE THREAD

**Issue by Pipsqueak737** [emilyploszaj/emi#224]
MoreCreativeTabs allows you to use resource packs to change, add, or remove creative tabs. However, EMI doesn't seem to recognize changes made with MoreCreativeTabs and the index will only follow the vanilla creative tabs even if they have been modified.

**Comment by emilyploszaj** [comment]
EMI in 1.19.2 doesn't follow the creative tabs, it gets its information from the search tab. I'm not sure if it's reasonable for EMI to be able to get information that items themselves don't expose about tabs in this version.

**Comment by emilyploszaj** [comment]
Closing this issue as EMI doesn't follow creative tabs in 1.19.2 and will reinvestigate when/if creative tab sorting is brought to that version
