### ISSUE TITLE
Dragging Fluids into filters in AE2 doesn't work

### ISSUE THREAD

**Issue by piotrb** [emilyploszaj/emi#225]
with just JEI, you can drag a fluid (eg water) (not the bucket, the actual water fluid) .. and drag it into filter spots in AE2 (like in interfaces, importers, exporters, etc) .. and it will correctly drop that in there .. seems like dragging them in EMI doesn't follow the same interface and AE2 doesn't recognize that as a valid droppable .. making it basically impossible to work properly with AE2 this way .. this is also the same for Mekanism gases, since AE2 can store and filter them the same way

**Comment by emilyploszaj** [comment]
This was related to another issue that was resolved in 1.0.5

**Comment by piotrb** [comment]
Oh nice, thanks! :)
