### ISSUE TITLE
Certain Items not showing up in EMI after the 1.0.2 Update

### ISSUE THREAD

**Issue by Bluetinity** [emilyploszaj/emi#227]
About half of the items from kibe mod don't show up in EMI versions 1.0.3+. The items show up in JEI just fine, but having EMI + JEI or just EMI standalone makes no difference. I've also tried to mess around with EMI settings, no luck.

1.0.2 and before
<img width="1312" alt="javaw_NnSVxw6uzp" src="https://github.com/emilyploszaj/emi/assets/27723917/302f315a-ed65-4978-9c17-1a959be2e295">

1.0.3+
<img width="1273" alt="javaw_twfiBW0jVq" src="https://github.com/emilyploszaj/emi/assets/27723917/229bead4-dbe3-4ed0-985c-5d0f3633dbbf">

**Comment by Bluetinity** [comment]
I've also noticed that the items don't appear in the vanilla creative inventory search

**Comment by SmRzT** [comment]
I've had something similar happen like after a few hours or searches some mods dissapeared in my case it was Pneumaticraft but a simple relog to the server fixed it

**Comment by emilyploszaj** [comment]
A fallback strategy was added in EMI 1.0.7 to catch mods like this

**Comment by Bluetinity** [comment]
I just installed 1.0.8 and it's still hidden.

**Comment by Bluetinity** [comment]
> A fallback strategy was added in EMI 1.0.7 to catch mods like this

Yeah it seems to be a problem with kibe, but half of kibe's items don't show up in the general index either
<img width="607" alt="javaw_IrDof4TX0Z" src="https://github.com/emilyploszaj/emi/assets/27723917/322588f7-3adf-4757-9bda-127a3ba7a49b">

**Comment by emilyploszaj** [comment]
This is an issue because Kibe registers about half of its items in creative tabs but not the other half. EMI's metric for if a mod needs to have all of its items show up is if it only puts a small amount of them into creative tabs. I believe Kibe needs to resolve this by properly handling creative tabs.

**Comment by SlayerTheChikken** [comment]
I do believe that Kibe needs to fix the issue for it not showing up in creative, but I do also think EMI should be showing all items with recipes as well; that is the point of it anyway :p

**Comment by emilyploszaj** [comment]
As of 1.0.25 EMI has an option to show all registered items.
