### ISSUE TITLE
[1.20.1] Compatibility with Crafting Tweaks

### ISSUE THREAD

**Issue by DeshiDesu** [emilyploszaj/emi#229]
**Mods:**
>emi-1.0.5+1.20.1+fabric.jar
craftingtweaks-fabric-1.20-18.0.2.jar

Clicking on the recipe book button will result in moving the recipe book button behind Crafting Tweaks' buttons.
Before:
![2023-06-27_01 43 07](https://github.com/emilyploszaj/emi/assets/120287925/ef08654d-0947-425b-8b91-9553ea711008)
After:
![2023-06-27_01 42 57](https://github.com/emilyploszaj/emi/assets/120287925/75f1415d-475f-4d22-968d-f1b5fd3ba5d7)

**Comment by emilyploszaj** [comment]
This may have to be something Crafting Tweaks resolves with a higher priority mixin
