### ISSUE TITLE
[1.19.2] Crash when viewing Every Compat's items 

### ISSUE THREAD

**Issue by Steveplays28** [emilyploszaj/emi#231]
[Log file (mclo.gs)](https://mclo.gs/z5bL4Ue)

Minecraft 1.19.2 Quilt
EMI 1.0.5

It seems to be [Every Compat](https://modrinth.com/mod/every-compat)'s items causing the crash, from my testing.

**Comment by emilyploszaj** [comment]
Honestly it's not clear in this log what even is crashing, it seems to be a mod dealing with crash reports crashing when trying to map perhaps another log? Do you have any other examples without stackdeobf?

**Comment by Steveplays28** [comment]
Sorry, didn't really take a detailed enough look at the log to notice the stackdeobf issue. It seems like a conflict with More Culling, but it happens specifically when looking at Every Compat's items.

Maybe this is a More Culling or Every Compat issue instead?

[Log file without `stackdeobf` (mclo.gs)](https://mclo.gs/O2RsmF6)

**Comment by emilyploszaj** [comment]
Yeah this looks more like a moreculling issue, I don't think it's every compat's fault, gonna close this, feel free to reopen if something new is discovered

**Comment by Steveplays28** [comment]
Alright! I'll make an issue on More Culling's repo, thanks!
