### ISSUE TITLE
[1.20.1 Fabric] Recipes still showing when present in Item Obliterator blacklist

### ISSUE THREAD

**Issue by gamerpotion** [emilyploszaj/emi#232]
When using Item Obliterator mod - https://www.curseforge.com/minecraft/mc-mods/item-obliterator
and placing items in its blacklist, their recipes are still visible in EMI  (not occuring in JEI/REI but only EMI)
this may cause players to gather recipes on servers and then later find out they cant craft it.

_emi-1.0.5+1.20.1+fabric.jar
Item_Obliterator-Fabric-MC1.20-1.3.0.jar_

### examples below

<img src="https://media.discordapp.net/attachments/1077294784877695017/1125596240223158302/image.png" />

<img src="https://media.discordapp.net/attachments/1077294784877695017/1125594922049876008/image.png" />

<img src="https://media.discordapp.net/attachments/1077294784877695017/1125595106083356703/image.png" />

### screenshot from using JEI (nuke core not showing)
<img src="https://media.discordapp.net/attachments/1077294784877695017/1125590268704477254/image.png" />

**Comment by emilyploszaj** [comment]
This would be an issue with ItemObliterator, it implements its plugins for other mods, there's nothing EMI can do from its side.

**Comment by gamerpotion** [comment]
Ok thanks for responding so quickly, will get in touch with them
@nvb-uy
