### ISSUE TITLE
[1.19.2] Emi does not respect Forge's IShapedRecipe

### ISSUE THREAD

**Issue by yrsegal** [emilyploszaj/emi#233]
<img width="436" alt="Screenshot 2023-07-04 at 10 36 24 AM" src="https://github.com/emilyploszaj/emi/assets/6596492/8312df12-829a-4125-b2e3-62d9f96ce037">

Quark's ShapedExclusionRecipe implements that, but it's shaped as though it was a 3x3 recipe, despite being 2x2.

**Comment by emilyploszaj** [comment]
That's peculiar, doesn't vanilla have a concept for shaped recipes? Oh well, I'll fix this

**Comment by yrsegal** [comment]
It does, but only for `ShapedRecipe` and this can't extend that for technical reasons

**Comment by emilyploszaj** [comment]
Oh, actually, this appears to be a Quark bug. Quark is returning `true` from `Recipe.fits` given large bounding boxes.

**Comment by yrsegal** [comment]
Oh wack

**Comment by emilyploszaj** [comment]
It's still likely reasonable to fix this on the EMI side so I will but yeah

**Comment by yrsegal** [comment]
huh. but we do `return parent.canCraftInDimensions(width, height);` (which i'm assuming is the mojmap for fits)

**Comment by emilyploszaj** [comment]
It only seems to consider the parent recipe's restrictions

**Comment by yrsegal** [comment]
well yeah, but the parent recipe is a 2x2 recipe here

**Comment by emilyploszaj** [comment]
`boolean shapeless = recipe.fits(1, recipe.getIngredients().size()) && recipe.fits(recipe.getIngredients().size(), 1);`
Not sure then, the only other possibility is your class extends shapeless recipe for some reason, which does not look like the case

**Comment by yrsegal** [comment]
Well it isn't showing the shapeless symbol, so I don't think it thinks the recipe is shapeless. It's just being improperly applied to the 3x3 grid instead of 2x2.

**Comment by emilyploszaj** [comment]
Ah, guess I gotta narrow in on the proper size, mods like ct must buffer with empty stacks for alignment. Okay this is my responsibility then.

**Comment by emilyploszaj** [comment]
This is fixed in EMI 1.0.7
