### ISSUE TITLE
[Suggestion/Improvement] Compatibility with Mekanism

### ISSUE THREAD

**Issue by Test-Account666** [emilyploszaj/emi#235]
Hey!

I really love EMI, but I'm forced to go back to JEI since EMI does not support some mods like Mekanism.

Maybe adding support for it is a possibility?

**Comment by Abbie5** [comment]
install jei alongside emi to see mekanism (and other mods that only support jei) recipes in emi

**Comment by Test-Account666** [comment]
Oh, I'm sorry for not reading correctly!

I thought it was incompatible with JEI

**Comment by emilyploszaj** [comment]
Abbie is correct, the compat exists. If it did not, JEI and EMI do not add support for mods, it goes the other way around. Regardless, this issue is resolved.
