### ISSUE TITLE
[Bug or ?]Folded tabs cannot be opened for viewing

### ISSUE THREAD

**Issue by ZHENGLOC** [emilyploszaj/emi#236]
I'm using this mod for the first time and I don't know if it's a bug or a feature. It is very inconvenient to use.
Just like the picture, I can't click to open.
![QQ截图20230709143311](https://github.com/emilyploszaj/emi/assets/24859848/eb9b5a90-6d81-4ed4-bbb4-f9bc17961aaa)
Especially some fluid tabs, I don't even know what those fluids are.
![QQ截图20230709144714](https://github.com/emilyploszaj/emi/assets/24859848/d53cdb8f-49f6-402c-871d-28a20d924f93)
[latest.log](https://github.com/emilyploszaj/emi/files/11994596/latest.log)
game version: 1.19.2
mod version: 1.0.6
mod loader: forge
[Machine Translation]

**Comment by emilyploszaj** [comment]
I'm sorry I don't understand what the issue you're having is. You should be able to left click (or press `r`) to see all the options in an ingredient. Is that what you're having an issue with?

**Comment by ZHENGLOC** [comment]
> I'm sorry I don't understand what the issue you're having is. You should be able to left click (or press `r`) to see all the options in an ingredient. Is that what you're having an issue with?

Right, I don't know why I can't click to view.

**Comment by emilyploszaj** [comment]
I took a better look at the log. This seems to be an issue with Fins and Tails. I'll release an update soon that fixes this incompatibility, for now you can try disabling the mod.

**Comment by ZHENGLOC** [comment]
> I took a better look at the log. This seems to be an issue with Fins and Tails. I'll release an update soon that fixes this incompatibility, for now you can try disabling the mod.

Wow! You are so efficient at work! Thank you so much!

**Comment by emilyploszaj** [comment]
This is fixed in EMI 1.0.7
