### ISSUE TITLE
[Forge 1.19.2] Does not show non-standard recipes (using workbenches other than vanilla's crafting table, e.g. Create mechanical crafter)

### ISSUE THREAD

**Issue by Hellvenn** [emilyploszaj/emi#237]
### Instance details:

- Launcher: Prism Launcher 7.1
- MC version: 1.19.2
- Modloader: Forge 43.2.8
- EMI version: 1.0.6+1.19.2+forge

### Featured mods:
![image](https://github.com/emilyploszaj/emi/assets/83005015/d7482b5c-1482-4bfc-81ac-1f78ee67b160)
![image](https://github.com/emilyploszaj/emi/assets/83005015/e167952d-408f-47af-90d3-f7ea3e1a1319)

### Problem details:
EMI doesn't open recipe viewer window for any items that require being crafted using modded workbenches. I've tested few items from both Create and Mekanism, neither of them seems to work. Also I was trying to trigger that with both Left Click and pressing `R`. I'm leaving Minecraft log file down below.

**Edit 1** I've read that in order to make this work with Mekanism I need to install JEI. So that one resolves itself, but still what about Create?

### Minecraft log:
[latest.log](https://github.com/emilyploszaj/emi/files/11995126/latest.log)

### Additional info:
Before I installed EMI, I had been using JEI in the first place and then switched to REI. I'm pointing it out as some of the config files for those are still left in the folders and I know EMI has a support for JEI. So if that mess somehow has conflicted with EMI, then I want you to know the situation.

**Comment by LucilleTea** [comment]
EMI has support for JEI recipes, but you need to have JEI installed at the same time to use this.
Without that, you need mods to support EMI directly, which is a bit rare on forge 1.19.2.
So just add JEI and you should be good.

**Comment by Hellvenn** [comment]
Doesn't Create support EMI on forge?

**Comment by LucilleTea** [comment]
I don't see a dedicated EMI plugin in the forge mod currently, and people in their discord talk about using EMI/JEI together for forge. I don't know if dedicated support is in the works.
Create fabric has dedicated EMI support.

The EMI/JEI integration should work well though, and any mods that do have dedicated EMI support will correctly prioritize it.

**Comment by Hellvenn** [comment]
Ok, I've installed JEI alongside EMI and now it's working with recipes, but there's _still_ issue with rendering when using Mekanism QIO:
![2023-07-09_14 52 45](https://github.com/emilyploszaj/emi/assets/83005015/04798ee2-a4a0-4aed-8f5b-4f5b91cb655e)

(_still_ beacuse it was from the beginning, but i didn't want to make an issue until resolving recipes not working)

Should I close this issue and make another one for the rendering problem?

**Comment by emilyploszaj** [comment]
Some rendering changes were added in EMI 1.0.7, however, if this doesn't fix the rendering issue, there's nothing EMI can do and it's Mekanism's doing.
