### ISSUE TITLE
EMI can pass not fully initialized screen to exclusion area providers

### ISSUE THREAD

**Issue by Technici4n** [emilyploszaj/emi#240]
The mixin in `HandledScreen#init` causes the exclusion area providers to receive a screen that's not fully initialized in some cases. For example:
![image](https://github.com/emilyploszaj/emi/assets/13494793/05c1d441-e647-4c30-956b-e6e57b8e0c64)

Here the exclusion area provider is dependent on the things running after `super.init()`, which leads to an ugly NPE in this specific case. It's ok for the subsequent frames however.

**Comment by emilyploszaj** [comment]
This has been fixed in 1.0.10

**Comment by Technici4n** [comment]
Thank you!
