### ISSUE TITLE
[bug] [1.20.1] Some Recipes don't display output item tooltips.

### ISSUE THREAD

**Issue by noawx** [emilyploszaj/emi#241]
Version: Fabric 1.20.1
EMI Version: 1.0.9+1.20.1+fabric

When viewing a recipe's output item, the tooltip is completely empty, expect for the batch cost.

Appears in vanilla and modded items alike.
This is only in specific recipes, and sometimes appears in the recipe tree, sometimes not.

Seems very random, but I have noticed that 4/5 recipes with the "minecraft:coals" tag had this issue.

![image](https://github.com/emilyploszaj/emi/assets/76262280/b53cc0c4-4aa2-4df3-93d3-608a703152cb)
![image](https://github.com/emilyploszaj/emi/assets/76262280/7ce08a65-3bab-439a-b759-3ceb64e846f3)
![image](https://github.com/emilyploszaj/emi/assets/76262280/cde9db5b-e060-4477-aac2-3072fc39d2c8)
![image](https://github.com/emilyploszaj/emi/assets/76262280/626ccfbd-01eb-4562-985f-261e0bf068e8)
![image](https://github.com/emilyploszaj/emi/assets/76262280/73a213af-272c-4b54-9460-0c23c93edc91)
![image](https://github.com/emilyploszaj/emi/assets/76262280/122ae5b7-97d6-46a9-9b95-5b0647883f7f)

**Comment by emilyploszaj** [comment]
Weird, this bug is very peculiar but I'll try to figure it out. Just as an aside, I really like your resource pack.

**Comment by emilyploszaj** [comment]
This has been fixed in 1.0.10
