### ISSUE TITLE
Potion Rendering potentially causing stutter

### ISSUE THREAD

**Issue by FooterManDev** [emilyploszaj/emi#248]
After receiving some hiccups when running /reload, I checked my latest.log to see what was happening, and Forge throws an error saying "Rendersystem called from the wrong thread", and it's always after EMI hides a potion thing. I believe this to be the cause of the hiccups, and eventually a crash.
https://gist.github.com/FooterMan15/7ca35c88591262ba1734897d4d41c796

**Comment by SiverDX** [comment]
as a workaround you can try setting `render_item_model` to `NONE` for https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips (common config)

that should avoid the rendering call for the tooltips

**Comment by emilyploszaj** [comment]
This likely has to do with the fact that EMI bakes its search index off thread to avoid a massive several second stutter, mods that mess with rendering while only getting tooltip text can cause issues like this, but there's no real actionable solution, unfortunately. That workaround may be useful to you but overall EMI can't resolve this issue.

**Comment by FooterManDev** [comment]
> as a workaround you can try setting `render_item_model` to `NONE` for https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips (common config)
> 
> that should avoid the rendering call for the tooltips

Thank you! Looks like this fixes my issue, and speeds up EMI as a whole interestingly.
