### ISSUE TITLE
[1.20.1-Forge] Creative Search blank when EMI is paired with JEI. (but not other tabs, just search.)

### ISSUE THREAD

**Issue by Gbergz** [emilyploszaj/emi#250]
# Title^

I am playing in my modpack found [[here]](https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7), testing EMI to have it for next pack update.

Only issue I've found is that the Creative search tab is blank, and even when searching.

# **Versions:**
MC: 1.20.1
Forge: 47.1.3
EMI: 1.0.11+1.20.1
JEI: 15.2.0.23

# **Screenshots:** 
(with EMI):
![bild](https://github.com/emilyploszaj/emi/assets/26634554/5694d4b1-54fe-4a67-9494-e8229554ee52)

(without EMI):
![bild](https://github.com/emilyploszaj/emi/assets/26634554/8c36cde3-d402-4439-a333-8b98caf0ecf5)

# Other notes:
I don't know if this happens with only EMI as I've not tested since I had to go out moment I posted this.

# Logs here if needed
Logs: https://gist.githubusercontent.com/Gbergz/1b2bbb94088925b0c4bf394674ecccd9/raw/f485cdee1492becb26b6ee32b04cd20e9b317550/gistfile1.txt

**Comment by emilyploszaj** [comment]
I've been unable to reproduce this issue and the log provided does not seem to contain EMI installed. If you can reproduce it with a certain set of problematic mods I'd be able to take a better look.

**Comment by Gbergz** [comment]
I can try to debug it see which mods clash, but so far I have not been able to.

**Comment by Gbergz** [comment]
Yeah this is still happening, but if you re-enter the world all is well, only on first join it doesn't show.

Not been able to figure out why this is an issue still.. sucks. It's really annoying.
