### ISSUE TITLE
Suggestion: Add search by ID config option

### ISSUE THREAD

**Issue by ejektaflex** [emilyploszaj/emi#251]
Or something akin to this. It would be nice to search based on ID instead of name.
Use cases:
* I'm learning another language, but I don't know what to type in said language.
* I'm playing with Pirate Language turned on, but don't know that "Glass" is now "Porthole", so I can't find it.
* More generally, I only know the ID of an item, but not the name of it in the current locale.

**Comment by emilyploszaj** [comment]
This was implemented a handful of versions back and I forgot to close this bug.
