### ISSUE TITLE
[Forge 1.19.2] Causes a GUI texture to not load

### ISSUE THREAD

**Issue by SiverDX** [emilyploszaj/emi#254]
**Version**: 1.0.12

Without EMI

![image](https://github.com/emilyploszaj/emi/assets/22003703/4c72d451-415e-4711-99f5-0bc8d83316c0)

With EMI

![image](https://github.com/emilyploszaj/emi/assets/22003703/ea32a492-767f-4bf1-8795-141e4725f6b9)

do you have any idea as to why this is happening?

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7db8c9dcbbc1a2b1963267e8eaab25e49ad497d3/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/gui/DragonScreen.java#L281-L303

The missing texture is this part:
https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7db8c9dcbbc1a2b1963267e8eaab25e49ad497d3/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/gui/DragonScreen.java#L298C1-L301

It will show up for a second while EMI is still loading but once EMI is ready it disappears

![image](https://github.com/emilyploszaj/emi/assets/22003703/de66b513-8349-4daf-bab1-2b2d3302d8dc)

**Comment by emilyploszaj** [comment]
This mod does not seem to properly interact with render state, it needs to set the state it relies on like depth testing. There is not a lot EMI can do here
