### ISSUE TITLE
[Bug] EMI is slightly buggy with Legendary Tooltips.

### ISSUE THREAD

**Issue by MbtMarco** [emilyploszaj/emi#256]
**Link the issue about it so you don't have to rewrite everything:**

https://github.com/AHilyard/LegendaryTooltips/issues/88

_(P.s. I don't know if this is an EMI or Legendary Tooltips issue)_

**Comment by emilyploszaj** [comment]
This is related to how EMI renders tooltips, which has to occur deeper into the vanilla code in order to accommodate some of the rendering things EMI has to do. Fixing this would be something legendary tooltips would have to do.
