### ISSUE TITLE
Suggestion: Category Name Modification

### ISSUE THREAD

**Issue by FooterManDev** [emilyploszaj/emi#258]
Add a way to modify Category names, for example:
`minecraft:crafting` > `minecraft:table`.

**Comment by emilyploszaj** [comment]
`minecraft:crafting` is the identifier of the crafting category, there's no reason to ever want it to change, it uses a translation string elsewhere. I'm unclear on why you'd want something like this unfortunately.

**Comment by FooterManDev** [comment]
Sorry, that’s not what I meant. I meant to suggest changing what name is displayed, but I worded very improperly.

**Comment by emilyploszaj** [comment]
These are translation keys <https://github.com/emilyploszaj/emi/blob/1.20/xplat/src/main/resources/assets/emi/lang/en_us.json#L274>
