### ISSUE TITLE
[Feature Suggestion] Ability to blacklist/exclude items from display in the sidebar

### ISSUE THREAD

**Issue by foul-fortune-feline** [emilyploszaj/emi#26]
As stated, it'd be nice to have a feature for EMI similar to the one for REI which allows one to set items not to be delayed. This would be valuable for mods like Chisels & Bits, which add a lot of similar items which don't have crafting recipes and are obtained in similar/identical ways

**Comment by inikishev** [comment]
> EMI supports this behavior, see `EmiRegistry.removeEmiStacks`

I am not sure where to find that. I want to disable AE2 facades, as it is just 67 pages of copies of every other vanilla and modded block, even ones that use entity models
