### ISSUE TITLE
Implement JEI recipe category decorator equivalent

### ISSUE THREAD

**Issue by rlnt** [emilyploszaj/emi#261]
Would love to see a similar approach to this feature:
https://github.com/mezz/JustEnoughItems/pull/3255

It exists as recipe category decorators in JEI and as recipe extensions in REI.

**Comment by emilyploszaj** [comment]
This is probably a reasonable API addition but some consideration will need to be made on how to integrate it.

**Comment by Mimic0445** [comment]
This would be super helpful for making mod packs with EMI.

I am currently going through every ore, raw ore, crushed ore, dust, ingot, block, plate, and gear.
Manually disabling all of the duplicate items after unifying the recipes.

**Comment by Rosethorns** [comment]
I've also come across my need for this, as the EMI provided model icons for tag categories does not work with dynamic item icons. So being able to reorder the priority recipe viewers icons would be ideal.

**Comment by emilyploszaj** [comment]
Implemented in 1.1.2, I misunderstood the scope at first, and thought the desire was significantly more complicated, but it's currently an experimental API addition to be marked un-experimental in 1.2.0, assuming it functions as desired.
