### ISSUE TITLE
[Suggestion] Having the blacklist be a separate file

### ISSUE THREAD

**Issue by Mrbysco** [emilyploszaj/emi#266]
Currently if a pack dev were to include the blacklist in a pack it'd overwrite the user's data every update. I'd like to suggest having the blacklist in a separate file

**Comment by ShyNieke** [comment]
Can it maybe grab the blacklist from JEI?

**Comment by Bluberry-Kat** [comment]
index customization can be done via resource pack. please see [the wiki](https://github.com/emilyploszaj/emi/wiki/Hiding-and-Adding-Index-Stacks) for more information.

**Comment by emilyploszaj** [comment]
Kat is correct, the local edit mode hidden stacks are per user, but can be copied to a resource pack file shipped with modpacks using common data scripters/loaders like KubeJS. That is to say this suggestion already exists.
