### ISSUE TITLE
[API Bug] Method "addTooltip" Doesn't Actually Add Widget

### ISSUE THREAD

**Issue by Phoupraw** [emilyploszaj/emi#267]
`dev.emi.emi.api.widget.WidgetHolder#addTooltip(java.util.function.BiFunction<java.lang.Integer,java.lang.Integer,java.util.List<net.minecraft.client.gui.tooltip.TooltipComponent>>, int, int, int, int)` only creates a new `dev.emi.emi.api.widget.TooltipWidget` but doesn't invoke `dev.emi.emi.api.widget.WidgetHolder#add` so the tooltip widget isn't be added actually. So does `dev.emi.emi.api.widget.WidgetHolder#addTooltip(java.util.List<net.minecraft.client.gui.tooltip.TooltipComponent>, int, int, int, int)` and `dev.emi.emi.api.widget.WidgetHolder#addTooltipText`.
```java
default TooltipWidget addTooltip(BiFunction<Integer, Integer, List<TooltipComponent>> tooltipSupplier, int x, int y, int width, int height) {
    return new TooltipWidget(tooltipSupplier, x, y, width, height);
}
```

**Comment by emilyploszaj** [comment]
Fixed in 1.0.18
