### ISSUE TITLE
[Suggestion] More advanced lookup history traversal using Back/Forward buttons

### ISSUE THREAD

**Issue by Miner239** [emilyploszaj/emi#268]
I'm aware that I can already use the lookup history to go back through the items I'm exploring. However, using it puts me back into the default view for the item I selected. Clicking the current item on the other direction also works, but the scroll position was lost.

I've been spoiled with the Recipe Book mod in Factorio that lets me spam E to go back one step at a time, while also preserving my scroll location on the previous views. That way I can traverse into distractions without losing focus and needing to scroll back to where I was looking before.

Can you implement viewing history that also stores scroll position, and a back/forward button to navigate through that history?

**Comment by emilyploszaj** [comment]
This is reasonable, I've been meaning into making history traversal better, I'll look into it.

**Comment by Miner239** [comment]
I feel a little bit awful now that I've discovered that Back feature already exists within the mod, bound by default to Backspace. It's exactly what I wanted! Adding Forward and buttons on screen (or something else) to communicate that the feature exist could still be on the table though.

**Comment by emilyploszaj** [comment]
Oh worry not. I assumed this description was telling me that the current back functionality wasn't working, glad to hear it is. Either way, I will keep this bug open for adding forward traversal functionality.

**Comment by emilyploszaj** [comment]
Forward has been added to augment history traversal. It will be released along with the 1.20.2 port in the coming days.
