### ISSUE TITLE
[API] Ability to check whether EMI keybinds are pressed

### ISSUE THREAD

**Issue by XFactHD** [emilyploszaj/emi#270]
An API to check whether a certain keybind is pressed when given a key code and scan code would allow mods to do things like opening recipes for or usages of an item when hovering non-slot widgets.

For context, I have a crafting system that looks similar to vanilla's stonecutter with a grid of buttons and I would like to allow players to open the "show recipe" screen of the item shown on the button they are hovering.

**Comment by emilyploszaj** [comment]
EMI is unlikely to expose such a large amount of unstable API surface. However, to accomplish your goal, you can register a stack provider for your screen. `EmiStackInteraction`s can specify a recipe context for lookups.

**Comment by XFactHD** [comment]
Understandable. A custom stack provider does the trick, I completely missed that part of the API.
