### ISSUE TITLE
[1.18.2]Please support forge 

### ISSUE THREAD

**Issue by safesaffawa** [emilyploszaj/emi#271]
Because I've been playing recently with the integration pack named ATFC and this one has a lot of nesting recipes in it, emi will have the features to do me a favor.
If you can support it thank you, it's very important to me.

**Comment by emilyploszaj** [comment]
EMI will update to 1.18.2 if it becomes practical to do so. At the moment there are pretty big issues preventing easy releases to 1.18.2. I'm closing this issue as it's a port/version request.
