### ISSUE TITLE
Support for forge's default config system.

### ISSUE THREAD

**Issue by theboo** [emilyploszaj/emi#272]
Would be very nice for pack devs to be able to ship a default configuration for EMI without overriding the player's config every pack update.

**Comment by emilyploszaj** [comment]
Forge's default config system doesn't really "exist", but the functionality that was implemented (for both Forge and Fabric versions of EMI) is reading from `defaultconfigs/emi.css` if `configs/emi.css` is unspecified. This is being released in 1.0.19.
