### ISSUE TITLE
[1.19.2-Forge] Crash when opening inventory with certain mods installed

### ISSUE THREAD

**Issue by WowyDoesThings** [emilyploszaj/emi#274]
It appears that there is a conflict between EMI, JEI, and FTB Library that causes the game to freeze upon opening the inventory. When any one of the aforementioned mods is removed, the issue disappears. 

### Steps To Reproduce
1. Create a new survival mode world with all mods present.
2. Open inventory.
3. If game didn't freeze, try crafting a double chest and opening it.

### Versions:
Forge: 43.2.21
EMI: 1.0.18
JEI: 11.6.0.1016
FTB Library: 1902.4.1-build.236
Architectury API: 6.5.85

### Extra Notes:
Initially spotted this issue with a larger group of mods, none of which seem to be problematic. However, the freeze did not occur when opening the inventory, rather only happening when opening a double chest specifically in a survival world.

### Logs:
[Here](https://gist.github.com/WowyDoesThings/bafa920f85b118314d4bfd4ef3a1eb8a)

**Comment by SiverDX** [comment]
![grafik](https://github.com/emilyploszaj/emi/assets/22003703/a3b045d5-317b-4d10-9f1f-31c2342f3835)

Cannot really re-create the issue you're having
Crafted two chests, made it a double chest, opened it etc. - everything is fine

Your exit code:
https://minecrafthopper.net/help/exit-code/code-805306369/

**Comment by WowyDoesThings** [comment]
Strange. I just tried this again (created a fresh instance using MultiMC, loaded forge, installed the mods, created a survival world) and still froze upon opening a double chest. 
I verified all relevant drivers are up-to-date and both my system and hardware are functioning properly. In various tests, I allocated 4, 8, and 15 GB (of installed 16) to the instance, so I'm still left puzzled. 
If it helps, I can also provide more information on my system specs in the morning.

**Comment by emilyploszaj** [comment]
I haven't been able to reproduce the issue either. The log provided doesn't seem to have any information relating to the crash either, so it's unclear what is happening. If you can find a small set of mods to reproduce it on other systems I can take another look.
