### ISSUE TITLE
Inventory search overlay support for soph storage/backpack

### ISSUE THREAD

**Issue by theboo** [emilyploszaj/emi#276]
Basically what the title says, would be cool if inventory search overlay worked with sophisticated storage/backpack inventories.

**Comment by emilyploszaj** [comment]
This has been resolved in dev. It will be released along with the 1.20.2 port in the coming days.

**Comment by NielsPilgaard** [comment]
Will the fix be for 1.19.2 as well, or only 1.20+?

**Comment by Bluberry-Kat** [comment]
It will be for 1.19.2 as well, just coinciding with the 1.20.2 port.

**Comment by NielsPilgaard** [comment]
Super, thanks 😊
