### ISSUE TITLE
Misplaced Crafting Recipe When Using Integrated Dynamics Storage Terminal

### ISSUE THREAD

**Issue by jmadarg** [emilyploszaj/emi#280]
I'm currently playing [ATM VolcanoBlock](https://legacy.curseforge.com/minecraft/modpacks/all-the-mods-volcanoblock) (which is a 1.19.2 Forge modpack) and added EMI to it. 

When I tried to craft using the Storage Terminal from Integrated Dynamics the recipe is like shifted by one slot, for example the following recipe should be the chest surrounded by the planks.

![image](https://github.com/emilyploszaj/emi/assets/62086445/b868aa63-635d-44a9-9fb3-0dd7d1e7e146)

And here is what should be a crafting table:

![image](https://github.com/emilyploszaj/emi/assets/62086445/c4480e1d-e309-4da5-861b-8c24debbe50f)

The issue happens in singleplayer and multiplayer. I haven't tried an isolated instance with only Integrated Dynamics and EMI yet.

**Comment by jmadarg** [comment]
A bit more of info, the fill feature works as correctly if I only use JEI instead of adding EMI

**Comment by underscorched** [comment]
I seem to be having this issue as well on a custom built modpack for 1.19.2. Some items seem to be voided entirely if it goes off the crafting table while moving a recipe into the crafting table!

**Comment by Blockmandoo** [comment]
I'm also having this issue in my pack, and it seems to void the top left item in the 3x3 table, and I'm having similar issues with _RFTools Storage_'s storage scanner, and _Simple Storage Network_'s storage request table

**Comment by emilyploszaj** [comment]
Sorry for the delay on this one, it's been resolved in 1.0.20
