### ISSUE TITLE
[Feature Request] Open Recipe Tree keybind

### ISSUE THREAD

**Issue by Treeways** [emilyploszaj/emi#281]
I'd like a keybind to open the Recipe Tree from in-world, instead of needing to hit `E` and then clicking on the Recipe Tree button with my mouse.

**Comment by Lumiinos8100** [comment]
There is already a way, search "View tree" in the emi config. It will only open the tree when your inventory is open.

![image](https://github.com/emilyploszaj/emi/assets/136110984/269740b9-b66c-4100-bd8f-efd82d3511f3)

**Comment by Treeways** [comment]
Works for me. I missed the keybind in the EMI config!
