### ISSUE TITLE
Crash 1.20.1

### ISSUE THREAD

**Issue by castilio20** [emilyploszaj/emi#282]
[crash-2023-08-17_17.06.28-client.txt](https://github.com/emilyploszaj/emi/files/12370306/crash-2023-08-17_17.06.28-client.txt)
[latest.log](https://github.com/emilyploszaj/emi/files/12370317/latest.log)
The game crash when i tried to see a recipe from a mod(blood magic)

**Comment by emilyploszaj** [comment]
Based on the stacktrace this may be a rubidium issue, but EMI uses normal draw functions and this is simply drawing a texture.
