### ISSUE TITLE
Emi brakes creative search function

### ISSUE THREAD

**Issue by castilio20** [emilyploszaj/emi#283]
![2023-08-17_08 46 06](https://github.com/emilyploszaj/emi/assets/76228548/f6d692b5-c707-4037-bd55-f465031c923a)

it seems it emi + another mod having some conflict in only emi and forge profile it doesnt do that
[latest.log](https://github.com/emilyploszaj/emi/files/12370595/latest.log)
[debug.log](https://github.com/emilyploszaj/emi/files/12370598/debug.log)
maybe the log shows somthing that i miss
if it doesnt show i could try binary search

**Comment by emilyploszaj** [comment]
Some other mod is causing this. As of late 1.19, a lot of mods have been handling the creative search system improperly and have multithreading issues. If you can find what it is you can report it to that mod author.
