### ISSUE TITLE
Is this a emi problem or the other mods ?

### ISSUE THREAD

**Issue by castilio20** [emilyploszaj/emi#284]
![2023-08-17_12 11 29](https://github.com/emilyploszaj/emi/assets/76228548/72a846dd-3bfc-4691-b16e-a49ffb820a90)
![2023-08-17_12 11 27](https://github.com/emilyploszaj/emi/assets/76228548/b8eb78f5-f2c3-42f5-89fd-2160e6b53ce6)
Is this a emi problem or i should report to the other mods?

**Comment by emilyploszaj** [comment]
This overlap is an issue with the other mods who use this book not defining their screen size properly.
