### ISSUE TITLE
Cheat Mode Deletion "0 air" Issue

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#286]
On 1.0.19, when you cheat in an item with cheat mode, it shows that item in the logs. When you delete that item (or any item) using cheat mode, however, the logs show "0 air" instead of what it was.

![image](https://github.com/emilyploszaj/emi/assets/72876796/d9c45e1e-49b7-4dc2-8bb9-47b56ef9f7c1)

**Comment by emilyploszaj** [comment]
I believe this has been resolved in 1.0.20
