### ISSUE TITLE
Backport Forge in 1.18.2

### ISSUE THREAD

**Issue by Sky-NiniKo** [emilyploszaj/emi#289]
Hello,

I play on a 1.18.2 Forge modpack and I really want to use EMI because it is awesome but... this jar does not exist.
I have seen that a Forge version exist in 1.19 so even tough I don't know much about modding but I assume this is a doable task and this is why I ask if it is possible to make it a reality.

Faithfully,
NiniKo

P.S.: I know this is selfish, so I do not expect you to respond favorably to my demand.

**Comment by emilyploszaj** [comment]
Sorry, backport requests aren't valid GitHub issues, so I'll be closing this.
