### ISSUE TITLE
Infinite "emi waiting for recipe data from server" somewhy

### ISSUE THREAD

**Issue by SoLowHigh** [emilyploszaj/emi#290]
![изображение](https://github.com/emilyploszaj/emi/assets/32336603/438eb14d-2513-4e3b-9da3-e08b4d8da1b7)

**Comment by emilyploszaj** [comment]
EMI displaying this means that the server just is not sending you tag and recipe data. This could be broken mods that are breaking the sync, or a server that malforms the data, but it is not an issue with EMI
