### ISSUE TITLE
Tooltip layers fighting each other

### ISSUE THREAD

**Issue by MuteTiefling** [emilyploszaj/emi#291]
I'm not sure if this is an EMI issue or Sophisticated Storage issue, but I'll report it to both as it only seems to occur with the two mods installed.

Mod versions

- emi-1.0.19+1.19.2+forge.jar
- sophisticatedbackpacks-1.19.2-3.18.55.889.jar
- sophisticatedcore-1.19.2-0.5.83.394.jar
- sophisticatedstorage-1.19.2-0.8.40.581.jar

More info here: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/648

Situation:
Play in Windowed mode or at least with a very small gui scale/screen resolution. This isn't necessary but really helps force the situation
Bookmark recipes that output more than 1 item live I've done here: 
![image](https://github.com/emilyploszaj/emi/assets/9543430/739cd507-6294-4f27-9689-f33c2db8a5a4)

Open any Sophisticated Storage and mouse over something with a very large tooltip. Again, it doesn't seem to matter what, it just needs to be big enough to expand to the left and cover the bookmarks. Like this heavily modified pair of boots:
![image](https://github.com/emilyploszaj/emi/assets/9543430/5e3da390-9d1d-4ee5-b5fb-32f48c74509e)

You'll notice that the quantities from the bookmarks are showing through the tooltip here. If I do the same thing in my player inventory, I do not see the numbers
![image](https://github.com/emilyploszaj/emi/assets/9543430/48800d3b-53b1-456b-bf47-273c077c8fe7)

**Comment by emilyploszaj** [comment]
I think I'm going to say this is a sophisticated storage problem. I properly use all of the forge events they post and it works on other screens, so they must be doing something wrong when they draw item tooltips.
