### ISSUE TITLE
can't join any world and also create (1.19.2 fabric) emi 1.0.19

### ISSUE THREAD

**Issue by Mark1ed** [emilyploszaj/emi#292]
![image](https://github.com/emilyploszaj/emi/assets/108518311/0a74deb8-349c-4b68-97a1-278ee151f3a2)
connection lost

**Comment by jonask028** [comment]
same issue with quilt if i try to use emi with AOF6

**Comment by jonask028** [comment]
@Mark1ed download the latest version of this mod: https://modrinth.com/mod/polymer?hl=en-US

**Comment by emilyploszaj** [comment]
Polymer is crashing. Install the latest version of polymer so it stops crashing.
