### ISSUE TITLE
[1.20.1] Searching by Mod ID on mods that have spaces in the formatted mod id doesn't work.

### ISSUE THREAD

**Issue by Gbergz** [emilyploszaj/emi#293]
### Info:
Searching for a mod that for example has two words / has a space in the formatted mod id / name doesn't work.
Example: Searching for `@EnderIO` doesn't work. But searching for just `@Ender` does.
Also to get around this you need to search like this: `@Ender @IO`. Then it picks up the whole mod name id.

Not sure if this is a bug or intended. But I'll report it anyways because it feels unintended.

### Images
Searching only by (`@enderio`)
![screen](https://github.com/emilyploszaj/emi/assets/26634554/665feb16-fa12-4250-86d9-4b40454361c4)

Searching by (`@ender @io`) (actual mod id) (doesn't work)
![screen2](https://github.com/emilyploszaj/emi/assets/26634554/9365ce3d-c4d3-446f-a427-3beef2738905)

### Versions:
**MC**: 1.20.1
**Forge**: 47.1.3
**EMI**: 1.0.19
**JEI**: 15.2.0.27

**Comment by emilyploszaj** [comment]
This is intentional, all searches are broken into different queries by spaces

**Comment by Gbergz** [comment]
Alright. Good to know. Thanks for the answer :)
