### ISSUE TITLE
[1.20.1] Crashing issues when viewing the mod Chisels and Bits in EMI. (JEI is installed.)

### ISSUE THREAD

**Issue by Gbergz** [emilyploszaj/emi#296]
### What happened:
Client crashes when viewing the mod Chisels and Bits in EMI. (JEI is installed.)

### Versions:
MC: 1.20.1
Forge: 47.1.3
Chisels and Bits: 1.4.141
JEI: 15.2.0.27
EMI: 1.0.19

### Crash Report:
https://gist.githubusercontent.com/Gbergz/1fd23d632daf8a3d536674be3d231234/raw/8695e3ff497c20d29576ec0640548054701a2555/gistfile1.txt

Crash is reported on Chisels and Bits issue tracker too incase its caused by them:
`https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/1143`

**Comment by emilyploszaj** [comment]
I believe this is an issue caused by Chisels and Bits not having a fallback in their custom item renderer.

**Comment by marchermans** [comment]
There is no way to do this alternatively.......
The model needs access to the registry to generate all the variants on demand.....

I am not sure why EMI is trying to access block and item models outside of the world being setup?

**Comment by emilyploszaj** [comment]
The only time it'd be accessed is to render it during gameplay after the world is loaded.

**Comment by fzzyhmstrs** [comment]
It seems like `EmiAgnosForge` hard passes `null` for the Level, instead of whatever level the MinecraftClient instance may or may not have inside it. This is a potential origin of the conflict:

https://github.com/emilyploszaj/emi/blob/b773b7b8cc0f2825c36997ba07b8d0b6774c863b/forge/src/main/java/dev/emi/emi/platform/forge/EmiAgnosForge.java#L270

**Comment by emilyploszaj** [comment]
That can be resolved then

**Comment by emilyploszaj** [comment]
I was able to resolve this on my end, but I will maintain chisel and bits needs to be safer, the world parameter is annotated by mojang as nullable.

**Comment by fzzyhmstrs** [comment]
It is technically annotated that way, but:
![image](https://github.com/emilyploszaj/emi/assets/72876796/13ed0058-3ba1-4970-9053-de0ebeba633c)

**Comment by emilyploszaj** [comment]
That is the world, I'm talking about the model method which explicitly has a nullable world.
