### ISSUE TITLE
[Suggestion] Adjust background.png for resource pack artists

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#297]
Hello! I have a very specific request that probably wouldn't be relevant to 99% of people, but I figured I'd mention it anyway in case it would be easy to implement.

I've been trying to add mod support for my GUI resource pack, but I'm running into a bit of trouble with EMI, specifically with the file `assets/emi/textures/gui/background.png`. It uses a single pixel and stretches it for the entire "vanilla style" index background, which is preventing me from implementing some custom designs.

I don't normally ask for technical texture changes, but if this wouldn't be too much trouble to change to 4x4 size or bigger, I'd super appreciate it. But I know nothing about coding, so if this would be an annoying ordeal to fix, then please don't bother with my minor request.
![background-export](https://github.com/emilyploszaj/emi/assets/108554062/8bcac7d0-c669-4c66-bcb8-8fe0adfa6e81)

**Comment by emilyploszaj** [comment]
Unfortunately, changing this would break *existing* resource packs, and that's something I wouldn't want to do. I may consider a change in the next minor update or when there's sufficient breaking change in EMI's graphics. Sorry to disappoint

**Comment by ghost** [comment]
Ah, I hadn't considered existing packs. Completely understandable.
