### ISSUE TITLE
[Feature Request] Patchouli "Quick Lookup" Compatibility

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#301]
Patchouli's "quick lookup" feature works in the JEI interface, but not EMI's. A compatibility fix would be much appreciated if possible, as this makes referencing Patchouli entries much easier.

Minecraft: `1.20.1`
Forge: `47.1.4`
EMI: `1.0.19`
Patchouli: `1.20.1-81`
(No other mods are installed)
![patchouli](https://github.com/emilyploszaj/emi/assets/108554062/bb708800-ead0-4452-8c00-6e8c0678797b)

**Comment by emilyploszaj** [comment]
Patchouli is going to have to write this compat. If you've got JEI installed it might already work though.

**Comment by crafting-Aaron** [comment]
Doesn't seem to work with both installed but yeah this is probably an issue for Patchouli
