### ISSUE TITLE
[Forge 1.20.1] Apparent issues displaying Solar Craft recipes

### ISSUE THREAD

**Issue by Gronglegrowth** [emilyploszaj/emi#304]
Using [Solar Craft](https://www.curseforge.com/minecraft/mc-mods/solar-forge) 3.2.2, and EMI 1.0.19 with JEI 15.2.0.27, attempts to view unlocked recipes (tested so far with only the recipe for the Speed Tile, as that's the only one I have thus far) in my actual world appear to display with no items visible.

This _does not_ happen in a creative world (wherein I cheated myself all the progression required for that mod's recipes to be viewable), where they appear normally.

Removal of EMI causes recipes to display properly again.

Textfile of my full [modlist](https://github.com/emilyploszaj/emi/files/12509440/modlist.txt), using forge 47.1.3.

**Comment by emilyploszaj** [comment]
This is, as far as I can tell, resolved in 1.0.20
