### ISSUE TITLE
[bug] Can't assign extra mouse buttons to Back action

### ISSUE THREAD

**Issue by juh9870** [emilyploszaj/emi#305]
When I assign Button 4 or Button 5 (side buttons on a mouse) to the back action, they do nothing when pressed.

Assigning other buttons to that action works fine, as well as assigning mouse buttons to different actions.

**Mod version**: 0.7.3+1.18.2, Fabric

![image](https://github.com/emilyploszaj/emi/assets/15922601/de62456c-26bd-4571-8bc7-d0724ab73a9f)

**Comment by emilyploszaj** [comment]
Can you reproduce this in modern versions of EMI on 1.19.2+?

**Comment by juh9870** [comment]
Not present in 1.19 at least

**Comment by emilyploszaj** [comment]
Going to have to close this issue then, versions before 1.0.0 are no longer supported. This will be fixed if a 1.18.2 backport ever happens.
