### ISSUE TITLE
Some Create Recipes added by Datapacks don't display correctly

### ISSUE THREAD

**Issue by PersuGames** [emilyploszaj/emi#307]
Just discovered this mod series and I'm already in love with the additional features compared to something like JEI. I've found an inconsistency however which is most likely not meant to be a thing. From what I've seen some Create Datapack Recipes that use the chance variable in other recipes than washing (where it works correctly) don't display the chance and don't take it into account.
![Zrzut ekranu 2023-09-07 230343](https://github.com/emilyploszaj/emi/assets/67759479/bd37183b-0e09-4b81-be3e-40196fcca341)
![Zrzut ekranu 2023-09-07 230715](https://github.com/emilyploszaj/emi/assets/67759479/5d18ac34-f9a4-4407-a20d-8175ddb0ca3d)
Also, don't mind the broken dark mode resource pack. Already requested compat for that.

**Comment by emilyploszaj** [comment]
This appears to be Fabric, so the Create Fabric team maintains their EMI integration and you'd want to open a bug with them :slightly_smiling_face:
