### ISSUE TITLE
[Suggestion] Scrolling while hovering over the craft-type tabs should scroll though those instead of through the recipe pages

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#308]
![image](https://github.com/emilyploszaj/emi/assets/15698722/e7266245-9dba-47a8-84b0-7008484dab14)
Scrolling over these at the very top should scroll over those, not through the pages of (for example) Garden Cloche recipes.

**Comment by aaronhowser1** [comment]
It should also say how many pages of tabs there are, like `[ 5 / 32 ]`

**Comment by emilyploszaj** [comment]
Tabs not changing on scroll is intentional, you can scroll tabs at any location in the recipe screen with `shift + scroll`. As a design theme I try to avoid scrolling target changing unpredictably. For number of tab pages yeah that's just an issue though, it should be displayed somewhere.

**Comment by emilyploszaj** [comment]
Time swayed my opinion, this was implemented in EMI 1.0.25
