### ISSUE TITLE
[Bug] Crash on leaving with Backpacked Mod

### ISSUE THREAD

**Issue by RynShirayuki** [emilyploszaj/emi#311]
Leaving a server/singleplayer world with EMI and the Backpacked (Fabric) Mod from MrCrayfish causes the client to crash with the error messagejava.lang.IllegalStateException: Config property is not linked yet 
![image](https://github.com/emilyploszaj/emi/assets/39139683/1568b710-230b-44c4-b96a-1624d183c1ba)

**Comment by SiverDX** [comment]
that's not very helpful atleast post the whole log not just some snippet

**Comment by RynShirayuki** [comment]
> that's not very helpful atleast post the whole log not just some snippet

It was just to let them know as I've seen people commenting in MrCrayfish's discord about it but no post on the github

(I'll download it myself and upload in a bit)

**Comment by emilyploszaj** [comment]
Feel free to reopen if you have a log that has some fault of EMI, but this seems to be an issue with the Backpacked mod, and there is no log.
