### ISSUE TITLE
Pressing escape does returns to inventory in certain cases

### ISSUE THREAD

**Issue by Gaming32** [emilyploszaj/emi#312]
In the case where the current screen is not an `HandledScreen` when a `RecipeScreen` is opened, the screen returned to will be the inventory, not the screen returned to. This comes down to `RecipeScreen.old` being of type `HandledScreen` and a check occurring to switch to the inventory screen in the case of the current screen not being `HandledScreen`:
https://github.com/emilyploszaj/emi/blob/deef228b4a35cbcccd2e48e645118ed333a26013/xplat/src/main/java/dev/emi/emi/api/EmiApi.java#L241-L243
https://github.com/emilyploszaj/emi/blob/deef228b4a35cbcccd2e48e645118ed333a26013/xplat/src/main/java/dev/emi/emi/api/EmiApi.java#L102-L112

This does not match the behavior of other recipe viewers and causes some less than ideal behavior with my mod, where it returns to the inventory screen instead of the bingo card screen.

**Comment by emilyploszaj** [comment]
This could definitely be improved, that handled screen requirement is, I believe, legacy behavior.

**Comment by emilyploszaj** [comment]
This has been resolved in dev. It will be released along with the 1.20.2 port in the coming days.
