### ISSUE TITLE
[Request]Added the ability to copy recipe ids to the clipboard

### ISSUE THREAD

**Issue by 3453890470** [emilyploszaj/emi#314]
Sometimes I need to use the recipe id to disable the recipe, which makes it a bit difficult for me to use, showing only the recipe id and not copying it to the clipboard. If you can, be sure to add features and buttons that copy the recipe id to the clipboard, just like the button that moves the item to the synthesis slot.
![image](https://github.com/emilyploszaj/emi/assets/104831916/091c6c7b-f586-44db-9b4e-2664be683ab1)

**Comment by 3453890470** [comment]
Request from 1.19.2

**Comment by emilyploszaj** [comment]
This is a good suggestion. I've got an issue already tracking a similar feature, so I'm going to close this one as a duplicate. #152
