### ISSUE TITLE
setting recipe defaults for specific outputs does not work outside of recipe tree context

### ISSUE THREAD

**Issue by Abbie5** [emilyploszaj/emi#315]
pressing ctrl+left click to set a recipe default for a specific output stack doesn't seem to be working unless it's in the context of choosing the recipe for a recipe tree

emi 1.0.19+1.20.1, fabric

**Comment by Abbie5** [comment]
log: https://0x0.st/HOqb.txt

steps to reproduce:

- install emi, modern industrialization & dependencies
- look up recipe for diethyl ether
- press ctrl+left click on the diethyl ether output

expected result:
the recipe is set as default for diethyl ether

actual result:
nothing happens

**Comment by emilyploszaj** [comment]
This has been resolved in dev. It will be released along with the 1.20.2 port in the coming days.
