### ISSUE TITLE
Creavite Mode Serach

### ISSUE THREAD

**Issue by DinnerBeef** [emilyploszaj/emi#316]
NeoForge: 47.1.73
Mod Version: 1.0.19
Minecraft: Version 1.20.1

I installed EMI however when I try and search in creative mod now it just stays blank. If I remove EMI the creative mod search works like it's supposed to.

**Comment by emilyploszaj** [comment]
I can not reproduce this issue with just vanilla + EMI. This is likely another mod having search indexed information (name, tooltip) be thread unsafe, which can only be resolved by the mods themselves. You may be able to find more information in your log at which mods are causing this.
