### ISSUE TITLE
[1.20.1] EMI causes items to not display with Obscure Tooltips

### ISSUE THREAD

**Issue by Talan67** [emilyploszaj/emi#318]
EMI fully loaded: ![image](https://github.com/emilyploszaj/emi/assets/64811316/43060f37-409c-4676-b0ef-9ce286fce596)

EMI not loaded: ![image](https://github.com/emilyploszaj/emi/assets/64811316/0bf1e0a7-8304-4327-9484-238a48b8b8a6)

Forge 47.1.3
emi-1.0.20+1.20.1+forge.jar
Obscure-Tooltips-2.2.jar

Log: [latest.log](https://github.com/emilyploszaj/emi/files/12718662/latest.log)

**Comment by emilyploszaj** [comment]
Obscure X mods are closed source and there is nothing in the log, thus I cannot debug them. Regardless, there's nothing EMI is doing that can be breaking rendering like this, it's likely the mods depend on fragile render state which can be broken by any number of mods drawing anything, and they need to be more defensive with setting the state they need. This is on Obscure Tooltips to resolve.
