### ISSUE TITLE
Unable to use keybinds or search EMI while certain modded inventories are open

### ISSUE THREAD

**Issue by ArcanePigeon** [emilyploszaj/emi#32]
While inventories like Probably Chests or Toms Simple Storage are open you cannot type in the EMI  search bar or use any keybinds from EMI.
Probably Chests uses LibGui for generating the chest UIs which may be causing the issue, may not be. idk if TSS uses it.

**Comment by emilyploszaj** [comment]
EMI redid input handling in 0.6.0 to occur before screens, this should be resolved.
