### ISSUE TITLE
[Question] Is there a way to hide an item if there's multiple items in an ingredient tag? Example in desc.

### ISSUE THREAD

**Issue by Gbergz** [emilyploszaj/emi#321]
Title ^

Hiding the other two options in the screenshot below:
![bild](https://github.com/emilyploszaj/emi/assets/26634554/54a0164c-2d22-462f-b1f0-c3731c79ceb9)

So there's only one option, not multiple.
I guess removing the tag would solve it but is there any other way?
**-** Gbergz

**Comment by emilyploszaj** [comment]
You want to use the `disable` field when hiding stacks https://github.com/emilyploszaj/emi/wiki/Hiding-and-Adding-Index-Stacks

**Comment by Gbergz** [comment]
Thank you!
