### ISSUE TITLE
[1.20.2] Can't connect to any servers

### ISSUE THREAD

**Issue by RuiNtD** [emilyploszaj/emi#322]
An internal error occurs when I connect to any server. Only mods installed are EMI and Fabric API.

Log: https://mclo.gs/njoeM5e

![image](https://github.com/emilyploszaj/emi/assets/1149870/df94959b-2ac0-418f-8be2-56d6d5b62c92)

**Comment by evhan751** [comment]
Having this issue too, using Modrinth app

**Comment by Gaming32** [comment]
Deobfuscated: `class net.minecraft.world.item.crafting.RecipeHolder cannot be cast to class net.minecraft.world.item.crafting.Recipe` (Mojmap)

**Comment by berrydiaboli** [comment]
I have the same issue, but the output is a little different

`Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: class net.minecraft.class_8786 cannot be cast to class net.minecraft.class_1860 (net.minecraft.class_8786 and net.minecraft.class_1860 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)`

**Comment by nco2k** [comment]
i have the same issue.

**Comment by Juuxel** [comment]
Note: This happens because `readRecipe` returns `RecipeEntry` now, but the callback info still refers to `Recipe`.
https://github.com/emilyploszaj/emi/blob/7576bd8b6c4221ea5632caa14c129fd832fb5bec/fabric/src/main/java/dev/emi/emi/mixin/SynchronizeRecipesS2CPacketMixin.java#L18-L20

**Comment by emilyploszaj** [comment]
oh I was wondering where I touched recipe networking, thanks for figuring it out juuxel

**Comment by emilyploszaj** [comment]
Fixed in 1.0.22
