### ISSUE TITLE
Crafting block shows up in UI even when c:hidden_from_recipe_viewers

### ISSUE THREAD

**Issue by limejet** [emilyploszaj/emi#323]
Hello!

I'm trying to integrate [Wired Redstone](https://github.com/Kneelawk/WiredRedstone) with my modpack. To that end i've used KubeJS to disable all the default recipes wired redstone adds, and hidden every item and block i don't want using the `c:hidden_from_recipe_viewers` tag. 

However, the crafting block from the mod still shows up in the UI, here:
![image](https://github.com/emilyploszaj/emi/assets/4407285/d27faf98-b407-4bc8-9a68-3c27e153d3e4)

Clicking the block does nothing. It's just showing up as an alternative for all recipes that use the crafting table even though it isn't one.
This is with EMI v1.0.21+1.19.2+fabric, running on Quilt 0.20.2.

I don't really know how to get the block off of there, would a resource pack with a recipe/filter file that has `{"removed": ["redstone_assembler"], "disabled": true}` in it work? 

For ease of reproducing, I created a minimal mrpack: [kubejs-emi-test.mrpack.zip](https://github.com/emilyploszaj/emi/files/12785631/kubejs-emi-test.mrpack.zip)
It includes kubejs, wiredredstone, emi and respective dependencies, and a script that disables the recipes. Just go to any crafting table recipe and the redstone assembler shows up.

**Comment by emilyploszaj** [comment]
Behavior was adjusted, stacks that are disabled described in [this page](https://github.com/emilyploszaj/emi/wiki/Hiding-and-Adding-Index-Stacks) now works for hiding workstations as of 1.0.24
