### ISSUE TITLE
create multi-item output deploying recipes only display first output

### ISSUE THREAD

**Issue by Poly-0000** [emilyploszaj/emi#326]
create deploying recipes that have multiple outputs only display the first output.

behavior:
![grafik](https://github.com/emilyploszaj/emi/assets/89388476/85eec881-fa5e-4f65-b90c-252c32772f73)

expected behavior (JEI):
![grafik](https://github.com/emilyploszaj/emi/assets/89388476/a41e7d82-85d7-40b8-92bd-da19cf237185)

**Comment by emilyploszaj** [comment]
This is a bug in Create's integration, open an issue there.
