### ISSUE TITLE
[Suggesting] Add JEI's Recipe ID feature

### ISSUE THREAD

**Issue by ffuentesm** [emilyploszaj/emi#327]
Would be possible to add the JEI feature that shows the "Recipe added by_________" when another mod adds an alternative craft recipe for an item? Same for Datapacks crafting recipes. 
![image](https://github.com/emilyploszaj/emi/assets/44974827/bb14926c-81f2-4a81-b6e3-8c5ddb47b822)

Basically I wish you could add the recipe ID that JEI has. This would be a BIG quality of life that would let modders, and users know where a recipe .json file is located inside the .jar facilitating certain game fixes
![image](https://github.com/emilyploszaj/emi/assets/44974827/077f5bc3-b943-465a-9185-e75a4c2ac11a)

**Comment by emilyploszaj** [comment]
I'm not sure what you mean by same thing for datapacks, datapacks are not mods?

**Comment by ffuentesm** [comment]
I mean that in JEI if  a Datapack added a recipe, it would have a small tooltip on JEI saying "Craft added by ______"

**Comment by ffuentesm** [comment]
> I'm not sure what you mean by same thing for datapacks, datapacks are not mods?

As you can see, JEI has a "recipe added by [source]" as those sources can be both from mods or datapacks
![image](https://github.com/emilyploszaj/emi/assets/44974827/f1111900-ba06-4284-8c64-b68f8a44bbab) 
![image](https://github.com/emilyploszaj/emi/assets/44974827/200d277d-5e5a-434c-8b8d-dcd579ca690a) 
![image](https://github.com/emilyploszaj/emi/assets/44974827/322d840a-ada2-40b9-9c98-1426f6840dc6)

**Comment by ffuentesm** [comment]
> I'm not sure what you mean by same thing for datapacks, datapacks are not mods?

Basically I wish you could add the recipe ID that JEI has. This would be a BIG quality of life that would let modders, and users know where a recipe .json file is located inside the .jar facilitating certain game fixes 
![image](https://github.com/emilyploszaj/emi/assets/44974827/1278690b-d4ff-415f-9a6f-68540803de6c)
