### ISSUE TITLE
better resource packs support?

### ISSUE THREAD

**Issue by knoxhack** [emilyploszaj/emi#329]

**Comment by emilyploszaj** [comment]
You're going to have to be more specific in what you want, EMI as it stands has pretty decent resource pack support for standard usage, and exceptional resource pack support for its custom resource formats. If you have something more specific in mind let me know.

**Comment by knoxhack** [comment]
For example JEI uses the enabled resource pack by default:
![2023-10-09_00 51 52](https://github.com/emilyploszaj/emi/assets/9358725/02cb119d-436c-4854-a690-aaba062bdbea)

But EMI doesnt:
![2023-10-09_00 57 22](https://github.com/emilyploszaj/emi/assets/9358725/de34dfcb-5ef0-4f3d-85c0-2d8486f1a3d4)


Resource pack:
[https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)

**Comment by emilyploszaj** [comment]
It looks like that because the resource pack you linked has special JEI textures.

**Comment by knoxhack** [comment]
ahhh I see, sorry about that ^^
