### ISSUE TITLE
Mod brakes jei visibility of hover biom list from industrial-foregoing

### ISSUE THREAD

**Issue by Kenshij** [emilyploszaj/emi#330]
Installed Mods

emi-1.0.22+1.19.2+forge.jar
jei-1.19.2-forge-11.6.0.1018.jar
industrial-foregoing-1.19.2-3.3.2.3-5.jar
titanium-1.19.2-3.7.4-28.jar

Mod brakes the jei ability to show biom list from industrial-foregoing.
When emi is removed, it's visible. With emi the hover list is not visible.
Shown in usage of laser base fluid or ore. Hover over the tree.

How it should be: 
![image](https://github.com/emilyploszaj/emi/assets/11033477/071c2384-aae7-4022-9677-f4e69de96bcb)

**Comment by emilyploszaj** [comment]
Fixed in 1.0.23
