### ISSUE TITLE
EMI Crash: PreparableModelLoadingPlugin$DataLoader missing

### ISSUE THREAD

**Issue by Arthurmeade12** [emilyploszaj/emi#331]
I am not a developer; I cannot diagnose this crash beyond knowing that it is caused by EMI.
Thanks for any help.
[https://mclo.gs/J6elDvz](https://mclo.gs/J6elDvz)

**Comment by emilyploszaj** [comment]
This is a class not defined error for a standard QSL/FAPI class, some mod must be corrupting it, and it can't be EMI, your best bet is a binary search.
