### ISSUE TITLE
[Feature Request] Item Zoom

### ISSUE THREAD

**Issue by BBoldt** [emilyploszaj/emi#332]
I just think what this mod offered would be a good feature to implement in EMI:
https://www.curseforge.com/minecraft/mc-mods/itemzoom

I really enjoy the large previews of items you hover over, and it makes use of space that isn't really used by anything on the left. Would be cool just as an option. At the very least, make the mod supported when it updates to 1.20.1. It works with the creative menu but not EMI.

**Comment by emilyploszaj** [comment]
I don't plan on adding this functionality and replacing an existing mod that does its job, and that'd be mean. However, ItemZoom needs to add support for EMI, EMI can't do anything to support it. Also, you might be surprised to learn that EMI adds several different types of sidebars, like the craftable sidebar, which can use space on the left. I suggest looking at the "Config Presets" section of the Config to learn more of the features.
