### ISSUE TITLE
[Feature Request] ability to disable EMI in some screens

### ISSUE THREAD

**Issue by Pyrofab** [emilyploszaj/emi#334]
Not all `HandledScreen`s are recipe GUIs, for example Blabber's dialogue screen :
![image](https://github.com/emilyploszaj/emi/assets/25536265/5e0f5313-ac53-4a5e-9ea8-5346c3b5a21f)

I looked around but it seems there is no official way of disabling the overlay on specific screens, could one be added if that is indeed the case ?

**Comment by emilyploszaj** [comment]
This has been something I've wanted to support but I have to ask, why are you using a HandledScreen when you're not using slots?

**Comment by Pyrofab** [comment]
Dialogues are controlled from the server, therefore I want to open it from the ServerPlayerEntity, know when a player closes the screen, have somewhere to store the state while the screen is opened, etc. Extending `HandledScreen` is the most straightforward way that I am aware of ¯\\\_(ツ)\_/¯

**Comment by dandalous** [comment]
Waystones and Tetra's crafting table and toolbelt for some examples of where blacklisting mod screens would be useful. Or at least a way to move the search bar besides bottom right and center. 

![2023-12-13_00 51 28](https://github.com/emilyploszaj/emi/assets/125793933/bf9d3e5e-0190-41b6-85b2-6c2c2234d08c)
![2023-12-13_00 55 15](https://github.com/emilyploszaj/emi/assets/125793933/757a0dd5-fb89-4709-bec3-9ee788dba60a)

(Incredible mod btw! I hope one day AE2 supports Craftables like Tom's Simple Storage Network, Crafting Station and others do. It's such a cool feature I've wanted in JEI for a long time)

**Comment by emilyploszaj** [comment]
This was fixed in 1.1.0, screens without slots no longer render in EMI.

**Comment by BookerCatch** [comment]
Could you please add a configuration option to accept a list of screen class names under which EMI will not render? Certain mods do funky stuff with their screens and containers whilst having slots; it would be nice for pack development to have these screens display without EMI.
