### ISSUE TITLE
[Feature Request] An option to give JEI recipes priority for certain mods when JEI is also installed

### ISSUE THREAD

**Issue by HappiePlant** [emilyploszaj/emi#336]
It would be nice to have an option to have JEI recipes get priority for certain mods for mods that haven't implemented their EMI recipes correctly. Because when I have a mod that supports both EMI and JEI, the EMI recipes show up (which makes sense).

For example, Create Fabric has this exact issue (https://github.com/Fabricators-of-Create/Create/issues/1148 and https://github.com/Fabricators-of-Create/Create/issues/1106), when playing with EMI and JEI, the EMI recipes which are not implemented correctly (I'm not sure) show up.

This would be nice for compatibility reasons :)

**Comment by emilyploszaj** [comment]
In almost every case this is going to be giving mods worse compatibility, with create it may solve niche issues but break a ton of EMI features like proper handling of chance, remainders, and some of create's fluid recipes. Ultimately, create just needs to resolve the issue.

**Comment by HappiePlant** [comment]
Makes sense, thanks for your reply :)
