### ISSUE TITLE
When searching tags by default, an option to ignore block tags and only search itemtags

### ISSUE THREAD

**Issue by Yarden-zamir** [emilyploszaj/emi#343]
for example right now if I search for pickaxe it will show me all of minecraft:minable/pickaxe which is basically all block lol

**Comment by emilyploszaj** [comment]
`#pickaxe -@minecraft`
`#pickaxe -#mineable`

**Comment by Yarden-zamir** [comment]
Again, I was asking for "searching tags by default". I know I can manually filter those, just not really solving my use-case. This sort of thing is not obvious for most players and I want people to be able to easily search for things of the same type, luckily we already have a type system which is tags, but that is rendered useless in many cases because of the use of block tags as well by default. I can of course add search aliases for every item of the same type, meaning for all tags, but I believe that is a bit overkill and I truly thing it would be best to support that sort of thing on the mod side as my use-case is not especially unique

**Comment by emilyploszaj** [comment]
I see. Either way, this is an antifeature, people not understanding why they can't find the tags they're searching up was a hugely common issue before block tags were included in the tag lookup, and gating common sense features like this buried in the config can cause headaches. In general, I heavily suggest search aliases for things you intend players to actually be looking up.
