### ISSUE TITLE
Internal Exception error when entering a world with EMI installed

### ISSUE THREAD

**Issue by akai-hana** [emilyploszaj/emi#344]
![image](https://github.com/emilyploszaj/emi/assets/55887501/7e9d9c69-41cd-4c3a-a603-b0936933a05c)
Using lastest EMI 1.19.2 fabric release.

I'm not sure what this error could mean. Maybe an incompatibility with some other mod?

logs: https://pastes.io/w2apxeulml
mod list: https://pastes.io/jhlzndl2g0

I can also send the entire modpack if anyone wants to test it on their computers. Just ask and I'll send a link.

**Comment by emilyploszaj** [comment]
You have the mod Polymer installed and this is a crash from it, not EMI. To fix it you can update polymer.
