### ISSUE TITLE
[Forge - 1.19.2]: Latest update causes reload-loop when KubeJS is present

### ISSUE THREAD

**Issue by SiverDX** [emilyploszaj/emi#345]
```log
[06Nov2023 17:42:08.359] [Render thread/INFO] [EMI/]: [EMI] Tags synchronized, reloading EMI
[06Nov2023 17:42:08.359] [Render thread/INFO] [EMI/]: [EMI] Starting Reload
```

It keeps reloading non-stop
(Maybe because KubeJS can add / remove entries from tags?)

[latest.log](https://github.com/emilyploszaj/emi/files/13270032/latest.log)

**Comment by emilyploszaj** [comment]
I have absolutely no clue why this is happening, but this can't be EMI's doing. Both EMI and JEI are reloading in that log and it's a vanilla reload, something EMI never triggers. I also cannot imagine what particularly about the latest version would even interact with this. KubeJS needs to fix it.
