### ISSUE TITLE
[1.19.2] When used with JEI, EMI doesn't highlight red the missing ingredients

### ISSUE THREAD

**Issue by sarim** [emilyploszaj/emi#346]
# Without JEI
![2023-11-07_00 56 54](https://github.com/emilyploszaj/emi/assets/1235888/d3ef4b5f-21a6-474e-85c0-1f34683b641b)
![2023-11-07_00 56 56](https://github.com/emilyploszaj/emi/assets/1235888/0178dc75-962f-4474-bfc6-ed53c73db9ca)

# With JEI
![2023-11-07_00 55 24](https://github.com/emilyploszaj/emi/assets/1235888/f222731e-36e4-4074-aa7c-f5efa427b7a3)
![2023-11-07_00 55 33](https://github.com/emilyploszaj/emi/assets/1235888/2a2af85b-1842-479c-aa0e-c6c0e7976584)

Forge 43.2.23
Mod  List: 
craftingstation-1.19.2-6.0.3.jar
emi-1.0.23+1.19.2+forge.jar
ironchest-1.19.2-14.2.7.jar
jei-1.19.2-forge-11.6.0.1018.jar

**Comment by emilyploszaj** [comment]
This should be fixed in EMI 1.0.25
