### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by ardissaps** [emilyploszaj/emi#35]
- AlloyForgery
- Owo Lib Exclusive Zone

![image](https://user-images.githubusercontent.com/82106625/179496915-5dd7c531-fe19-4734-a51a-a12c78db7548.png)

**Comment by LemmaEOF** [comment]
These are things that Alloy Forgery and OwOLib will need to implement themselves - EMI doesn't have the time or traditional responsibility for it
