### ISSUE TITLE
[Feature Request] Make item in tag and list ingredient defaultable

### ISSUE THREAD

**Issue by Phoupraw** [emilyploszaj/emi#356]
If a recipe includes a tag ingredient or a list ingredient, I have to specify which item I want each time I use crafting tree, which is annoying.
Besides, if a defaulted recipe contains a tag or list ingredient, and I have two matched items in my inventory, one is cheaper while the other is more expensive, the recipe handler might use the expensive one to craft, and I have no way to prevent it unless I put the expensive one into a temporary chest.

**Comment by emilyploszaj** [comment]
You can default a tag, there's a bind for it which I believe is ctrl click. List ingredients don't serialize and can't be defaulted because of it.

**Comment by Phoupraw** [comment]
> You can default a tag, there's a bind for it which I believe is ctrl click. List ingredients don't serialize and can't be defaulted because of it.

I can't default a tag. There is no icon for default in the side. I set the hotkey for default and press the hotkey while hovering stacks but it has no effect.
My EMI version is 1.0.25+1.20.1+fabric.
