### ISSUE TITLE
[Feature Request] Clock and Compass randomness

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#359]
Make clock and compass random in EMI index tab when player in survival mode
(To make a reason to craft them instead of view just in tab)

**Comment by Bluberry-Kat** [comment]
![a clock and compass in default position](https://github.com/emilyploszaj/emi/assets/20749209/67070ba1-dbf5-434e-b011-9631aa2f4dbd)
they already don't do anything, they don't need to be random.

**Comment by Disketaa** [comment]
1.20.2
![Test](https://github.com/emilyploszaj/emi/assets/76956762/e145acc0-8fc2-44b8-a5b8-fbbf3d4b68e6)

**Comment by emilyploszaj** [comment]
This is not the behavior of vanilla. You have a mod that is making the compass and clock do this.

**Comment by BookerCatch** [comment]
The mod in question is likely Embeddium/Rubidium. Having this loaded alongside EMI causes this issue. This does not occur with JEI+Embeddium/Rubidium, however.

**Comment by embeddedt** [comment]
@emilyploszaj The overload of `DrawContext#drawItem` that you call here:

https://github.com/emilyploszaj/emi/blob/bde2638164d02e1416518f3194b14cac4278ded5/xplat/src/main/java/dev/emi/emi/api/stack/ItemEmiStack.java#L89

passes the client player & world to the compass model, which allows it to resolve the angle. I think if you want to prevent this behavior you need to use `drawItemWithoutEntity` instead. I'm not sure why this is not an issue without a Sodium-like mod installed; do you use a different rendering path for vanilla?

**Comment by emilyploszaj** [comment]
It seems like it doesn't occur in vanilla because of the batched renderer, which has to be disabled because of sodium crashing custom vertex writers or something back in the back. This is something EMI will have to resolve and it shouldn't be that bad given the context from embeddedt, thanks for looking into it.

**Comment by embeddedt** [comment]
Custom vertex writers should be fine as of Sodium 0.5.4; all of the fallback solutions from Embeddium have made their way upstream. That is only usable on 1.20.2+ though.

**Comment by emilyploszaj** [comment]
This was fixed in 1.0.28 (and only affected 1.20 onward versions)
