### ISSUE TITLE
[Feature Request] Reminder always at the bottom

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#360]
Some custom recipes place the reminder in a tooltip between the values instead of at the bottom

![image](https://github.com/emilyploszaj/emi/assets/76956762/ac7c8dd7-9e14-4e3d-a6ec-16a532484025)
`Normal placement`

![image](https://github.com/emilyploszaj/emi/assets/76956762/ff2a8ec1-1a5d-4d28-bab1-4b3cc5764a8c)
`Weird placement`

```
  "output": {
    "type": "item",
    "id": "minecraft:nether_wart",
    "nbt": "{display:{Lore:['[{\"translate\": \"recipe.emi.group\", \"italic\": false, \"color\": \"gray\"}, {\"text\": \": \"}, {\"translate\": \"recipe.emi.entry.bartering\", \"color\": \"gold\"}]']}}",
    "chance": 0.03,
    "remainder": {
      "type": "item",
      "id": "minecraft:nether_wart",
      "amount": 2
    }
  }
```

**Comment by emilyploszaj** [comment]
This is just how EMI's tooltip components are organized, chance appears lower than remainder, it's not acting inconsistently.
