### ISSUE TITLE
[Feature Request] View Recipes from FTB quests quest book 

### ISSUE THREAD

**Issue by ScriptAero** [emilyploszaj/emi#361]
I like EMI a lot as it is nice being able to see the recipe trees on more tech focused packs, however on a pack that uses the questbook for a progression walkthrough we are unable to click on the item required and have the recipe show up similar to JEI, this feature from JEI has been endlessly helpful and I would love to see it in this mod too. 

I'm unaware if this is a bug or just not a feature thanks plenty in advance.

**Comment by SiverDX** [comment]
install https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat then it should work

**Comment by ScriptAero** [comment]
ahh thank you I completely forgot about this mod, I just thought it was a mod issue or incompatibility
