### ISSUE TITLE
Tooltips in config screen don't have a language key.

### ISSUE THREAD

**Issue by eterna1-0blivion** [emilyploszaj/emi#363]
I'm doing a translation into Russian, but I've encountered a trouble - the tooltips that are shown when hovering cannot be translated - they don't have a language key.

Please add language keys for these tooltips (screenshot of the problem and link to the code attached below), and I'll send back a completed Russian translation when I finish it :3

![22019 Image 1920x1080](https://github.com/emilyploszaj/emi/assets/50429313/1da73cc0-9b3e-44bc-8584-3199a7268317)

https://github.com/emilyploszaj/emi/blob/bde2638164d02e1416518f3194b14cac4278ded5/xplat/src/main/java/dev/emi/emi/config/EmiConfig.java#L46C2-L46C49

**Comment by emilyploszaj** [comment]
https://github.com/emilyploszaj/emi/blob/1.20.2/xplat/src/main/resources/assets/emi/lang/fr_fr.json Tooltips are translatable, they simply are not translated to english because config file comments are populated before resource packs are loaded.
