### ISSUE TITLE
Mild incompatibility with Legendary Tooltips

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#365]
With JEI and Legendary Tooltips

https://github.com/emilyploszaj/emi/assets/15698722/cc13d128-b80c-4743-aafc-56412077921f

With EMI (and JEI) but no Legendary Tooltips

https://github.com/emilyploszaj/emi/assets/15698722/54293d42-be43-4da3-923e-bda0d2de893e

With EMI (and JEI) and Legendary Tooltips

https://github.com/emilyploszaj/emi/assets/15698722/9c34b64b-46bb-473f-a856-4134fd24c5bf

emi-1.0.27+1.19.2+forge
LegendaryTooltips-1.19.2-forge-1.4.0

**Comment by emilyploszaj** [comment]
I'm familiar but there's nothing EMI can do to resolve this issue, legendary tooltips is just a highly incompatible mod that causes a lot of issues like breaking tooltips like this which work with vanilla. They've been informed of this incompatibility for a long time and have caused other incompatibilities in the past which are also not resolved. I'd recommend not using the mod.
