### ISSUE TITLE
Let's Do: Candlelight Compat

### ISSUE THREAD

**Issue by ryleu** [emilyploszaj/emi#372]
I would love to see compatibility for the [Let's Do: Candlelight](https://modrinth.com/mod/lets-do-candlelight) mod's cooking recipes.

**Comment by emilyploszaj** [comment]
Mods provide their own compatibility for JEI or EMI, and if they provide compat for either then you can get the recipes in EMI.

**Comment by ryleu** [comment]
got it, cheers!
