### ISSUE TITLE
[Spectrum] Not all output is displayed

### ISSUE THREAD

**Issue by Kisuny** [emilyploszaj/emi#373]
I changed the mechanism from the spectrum a little bit, adding a little more items there than usual, the display only 3 of these recipes
Example: 
![image](https://github.com/emilyploszaj/emi/assets/56004431/2e8b5d79-bd60-43f6-8b40-ab21e6fb43af)
![image](https://github.com/emilyploszaj/emi/assets/56004431/87e43333-e6cd-45da-aef5-3fbd8cd2fd4a)
![image](https://github.com/emilyploszaj/emi/assets/56004431/523c4a39-f2dc-4b33-aa43-fd371f71be89)

**Comment by emilyploszaj** [comment]
Please report this to spectrum.
