### ISSUE TITLE
Legacy ID based sorting?

### ISSUE THREAD

**Issue by Scraft161** [emilyploszaj/emi#382]
would it be possible to make the mod sort items by their pre-1.13 IDs/pre-inventory reorganization order.

I (and likely quite a few other modded players) have gotten used to the ID-based sorting that TMI/NEI/JEI have offered over the years and have gotten quite used to the order things used to be in (as hacky as it was) and my one complaint is that EMI doesn't offer it from what I have found (I'm fine with the current order as default as objectively speaking it is better) but having the old sorting for those who want it would be a great addition in my opinion.

**Comment by emilyploszaj** [comment]
There's an option for index source if you want to just pull from the registry, it's one of the first options in the config.

**Comment by Scraft161** [comment]
Thanks for the quick response.

Does it require me to reload the world or restart the game?
I remember messing with it and it not affecting the order at all

**Comment by emilyploszaj** [comment]
Yeah, it's one of the few settings that require a reload.
