### ISSUE TITLE
[BUG] Stack hiding feature does not function?

### ISSUE THREAD

**Issue by JENOVAAbsolute** [emilyploszaj/emi#384]
Minecraft version: 1.20.1
Fabric Loader version: 0.15.3
Fabric API version: 0.91.0
EMI version: 1.0.28

As seen in the image below, I selected a few items to hide in the index, but the items are not hidden. I restarted my game as well, since I had to do that to apply the same changes when I used JEI.

![image](https://github.com/emilyploszaj/emi/assets/60951301/35a37d1c-26f0-423f-8333-85852c201b92)

Latest.log
https://pastebin.com/evfqBHQU

**Comment by emilyploszaj** [comment]
You have edit mode still on.

**Comment by JENOVAAbsolute** [comment]
Oh my Lord. I assumed I didn't have to disable edit mode since it didn't need to be disabled in JEI. Now that I think about it, this is better, as I can re-enable them without going into the config file. 

Thank you.
