### ISSUE TITLE
[Compatibility issue] between EMI and Gates to eternity in modpack.

### ISSUE THREAD

**Issue by KurdaBOy** [emilyploszaj/emi#385]
Hi i play LL7 (TNP Limitless) modpack and found recently that when using EMI content from Gateways to eternity mod does not show up when i search it, some other mods like iron jetpacks seems to beheve strange aswell.

Gateways mod with EMI:
![2023-12-20_12 11 34](https://github.com/emilyploszaj/emi/assets/1353526/72a77d6f-ea35-4116-a3bb-9e1cc1331201)

With only JEI:
![2023-12-20_12 18 27](https://github.com/emilyploszaj/emi/assets/1353526/2e450e1f-e04e-4aac-bf4f-d6e7917720fb)

Iron Jetspacks with EMI:
![2023-12-20_12 12 40](https://github.com/emilyploszaj/emi/assets/1353526/e53d4710-48c8-4469-9585-7b7dac7ba063)

With only JEI:
![2023-12-20_12 18 43](https://github.com/emilyploszaj/emi/assets/1353526/72dec625-957c-4242-b69c-902ac2d26711)

Reported to pack dev team but I was also advised to report it here just in case.

Some additional info

Pack version: Limitless 7 v0.33.0
Forge version: 47.2.0
EMI version: 1.0.28
JEI version: 15.2.0.27

Log files:
[latest.log](https://github.com/emilyploszaj/emi/files/13726866/latest.log)

And Crash (it sometimes crashes when world is loaded and i try to open inventory):
[crash-2023-12-20_12.34.28-client.txt](https://github.com/emilyploszaj/emi/files/13726803/crash-2023-12-20_12.34.28-client.txt)

**Comment by emilyploszaj** [comment]
I think I left this open to take a better look, EMI and JEI should both be pulling sidebar stacks from the creative tabs, there have been many mods in the past that have broken this vanilla system and caused EMI to use the fallback registry items, which seems to be present in your screenshot here. There's not much EMI can do to fix this, you'd have to remove the problem mods breaking vanilla creative tabs.
