### ISSUE TITLE
Clicking the Search Field doesn't defocus other Mods Text-Fields on Screen

### ISSUE THREAD

**Issue by shartte** [emilyploszaj/emi#388]
Happens with AE2, where the AE2 search box is still focused when I click into the EMI search field.

Loader: NeoForge 1.20.4

I'll investigate this myself, since it might be an issue in AE2 itself, but it's unclear. Focus behavior in Minecraft has always been a problem.

**Comment by shartte** [comment]
Since your widgets aren't part of the current screens component tree, the default handling will not work.
But, your `EmiScreenManager` should  probably make sure that the focus within the current screen's widget tree is cleared (`client.currentScreen.setFocused(null)`)

**Comment by emilyploszaj** [comment]
Fixed by #389
