### ISSUE TITLE
powah and rs compat

### ISSUE THREAD

**Issue by wraithhawit** [emilyploszaj/emi#390]
can't dump energized steel recipe to my pattern grid like I can in base JEI. would be nice to have
![image](https://github.com/emilyploszaj/emi/assets/122818656/331a8a92-4736-4f92-9676-ddc426c52555)

**Comment by emilyploszaj** [comment]
I'm unclear why I didn't close this at the time, but I'm not sure this is related to EMI, I've tested support with the pattern terminal and recipes added by other mods, it should be handing over the base JEI recipes, unless gregtech's mixins are involved and intruding.
