### ISSUE TITLE
[Suggestion] Toggle visibility should only affect sidebars

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#394]
I configured the recipe book widget to toggle the visibility of EMI's sidebars to emulate the vanilla recipe book interaction. This works great, but now when pressing U or R over a stack, the expected behavior (the uses or recipes are displayed) does not work. It would be nice if the (default) U and R hotkeys display the uses and recipes of a stack independent of the visibility option *of the sidebars*

**Comment by emilyploszaj** [comment]
This seems to be a duplicate of #39 so it'll be tracked there, thanks!
