### ISSUE TITLE
[BUG] Left Index doesn't update while searching

### ISSUE THREAD

**Issue by Kiryonn** [emilyploszaj/emi#395]
| Minecraft | Modloader | Mod
|---|---|---|
| 1.20.1 | Fabric 0.15.3 | 1.0.29 |

![image](https://github.com/emilyploszaj/emi/assets/60699390/44b06bb2-2507-428c-be62-4c3079037d97)

**Comment by emilyploszaj** [comment]
Duplicate of #377
