### ISSUE TITLE
[Bug] EMI fails to load if Destroy is present

### ISSUE THREAD

**Issue by Gronglegrowth** [emilyploszaj/emi#400]
Reported to Destroy [here](https://github.com/petrolpark/Destroy/issues/7). If that mod is loaded, EMI will experience a critical error. Here is my logfile where this happened: [log.txt](https://github.com/emilyploszaj/emi/files/13843489/log.txt)

**Comment by petrolpark** [comment]
Destroy and EMI now load together. I think this can be closed.
