### ISSUE TITLE
EMI displays single-item Create mixing recipes that don't exist.

### ISSUE THREAD

**Issue by myriantics** [emilyploszaj/emi#402]
![2024-01-06_16 51 38](https://github.com/emilyploszaj/emi/assets/88632676/b08f6393-48e7-4adb-9847-e18b48ed90c5)
Create's mixer allows for the automated crafting of shapeless recipes. However, it omits those recipes that only require one item to be crafted. EMI shows these single-item recipes erroneously, but only when viewing the recipe of the output item. If you look at the uses of these items, the fake recipes do not show.

Fabric 1.20.1
EMI version 1.0.29

Modlist:

  [✔] advanced-networking-2.0.3+mc.1.20.1
  [✔] ae2wtlib-15.2.1-fabric
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] Applied-Botanics-fabric-1.5.0
  [✔] appliedenergistics2-fabric-15.0.18
  [✔] Aquamirae-6
  [✔] architectury-9.1.12-fabric
  [✔] bankstorage-0.3.8
  [✔] beansbackpacks-1.0-1.20.1
  [✔] blahaj_1.20-0.5.1
  [✔] blockus-2.7.10+1.20.1
  [✔] Bookshelf-Fabric-1.20.1-20.1.8
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] Botania-1.20.1-443-FABRIC
  [✔] cccbridge-mc1.20.1-fabric-v1.6.2b
  [✔] cc-tweaked-1.20.1-fabric-1.109.3
  [✔] chainmail_bucket-1.0.3-1.20.1
  [✔] cherishedworlds-fabric-6.1.5+1.20.1
  [✔] cloth-config-11.1.118-fabric
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] create_enchantment_industry-1.2.11
  [✔] createaddition-fabric+1.20.1-0.9.0
  [✔] create-sodium-fix-0.5.1-d-build.5+mc1.20.1
  [✔] creeperoverhaul-3.0.1-fabric
  [✔] dark-loading-screen-1.6.14
  [✔] Decorative Blocks-fabric-1.20.1-4.0.3
  [✔] deeperdarker-fabric-1.20-1.2.5
  [✔] deepmoblearning-refabricated-0.5.15-BETA+1.20.1
  [✔] derelict-1.0.1
  [✔] emi-1.0.29+1.20.1+fabric
  [✔] EnchantmentDescriptions-Fabric-1.20.1-17.0.11
  [✔] endermanoverhaul-fabric-1.20.1-1.0.3
  [✔] explosive-enhancement-1.2.2-1.20.x
  [✔] ExtendedDrawers-2.1.0+mc.1.20.1
  [✔] fabric-api-0.91.0+1.20.1
  [✔] fabric-language-kotlin-1.10.17+kotlin.1.9.22
  [✔] farmers-delight-fabric-1.4.3
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] garnished-1.5.1-hotfix-1+1.20.1
  [✔] geckolib-fabric-1.20.1-4.3.1
  [✔] global_packs-fabric-1.19.4-1.16.1_fabric
  [✔] here-be-no-dragons-1.0.0
  [✔] Iceberg-1.20.1-fabric-1.1.18
  [✔] indium-1.0.27+mc1.20.1
  [✔] inmis-2.7.2-1.20.1
  [✔] inmisaddon-1.0.4
  [✔] ItemBorders-1.20.1-fabric-1.2.0
  [✔] Jade-1.20-fabric-11.7.0
  [✔] JadeAddons-1.20.1-fabric-5.2.3
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] modmenu-7.2.2
  [✔] moonlight-1.20-2.8.80-fabric
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] naturespirit-1.4.0-1.20.1
  [✔] notenoughanimations-fabric-1.7.0-mc1.20.1
  [✔] Obscure-API-16
  [✔] owo-lib-0.11.2+1.20
  [✔] Patchouli-1.20.1-84-FABRIC
  [✔] pearfection-1.20.1-1.1.1
  [✔] persistent-stuff-1.2.0
  [✔] polyeng-fabric-0.1.0-1.20.1
  [✔] polymorph-fabric-0.49.1+1.20.1
  [✔] Powah-5.0.4
  [✔] PresenceFootsteps-1.9.1
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] randomium-1.20-1.29-fabric
  [✔] resourcefulconfig-fabric-1.20.1-2.1.1
  [✔] resourcefullib-fabric-1.20.1-2.1.20
  [✔] revelationary-1.3.6+1.20.1
  [✔] Searchables-fabric-1.20.1-1.0.2
  [✔] sodium-fabric-mc1.20.1-0.5.3
  [✔] sparkle-1.1.0
  [✔] spectrum-1.7.4-deeper-down
  [✔] spelunkery-1.20.1-0.3.5-fabric
  [✔] spirit-walker-0.1.5+1.20
  [✔] staaaaaaaaaaaack-fabric-1.20-1.4-64
  [✔] supplementaries-1.20-2.7.21-fabric
  [✔] tempad-fabric-1.20.1-2.3.3
  [✔] TerraBlender-fabric-1.20.1-3.0.1.2
  [✔] themetip-u0.6
  [✔] things-0.3.3+1.20
  [✔] trinkets-3.7.1
  [✔] wraith-waystones-3.3.2+mc1.20.1
  [✔] Xaeros_Minimap_23.9.3_Fabric_1.20
  [✔] XaerosWorldMap_1.37.2_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.2.1+1.20
  [✔] youre-in-grave-danger-2.0.0-beta.6
  [✔] Zoomify-2.11.2****

**Comment by emilyploszaj** [comment]
This is part of create's EMI plugin.
