### ISSUE TITLE
A very strange question

### ISSUE THREAD

**Issue by tangzixiang-hash** [emilyploszaj/emi#404]
I found it in the boilerplate when I tried to add the item to AE2, it should be 125, not 343, I don't know how this was caused, I tried to modify the fluid units in EMI, but nothing happened, I encountered it while playing atm9, I added your mod myself into this modpack.
![image](https://github.com/emilyploszaj/emi/assets/60438085/ffd98333-46cd-422e-92b2-84dda039e204)
![image](https://github.com/emilyploszaj/emi/assets/60438085/2e81fdb6-e726-4ef7-a0bd-3263ed215d1f)
![image](https://github.com/emilyploszaj/emi/assets/60438085/24f003de-25b9-4c77-a2d4-51cdaf018807)

**Comment by emilyploszaj** [comment]
This is kinda absurd but the JEI recipe actually uses 343 mB. EMI attempts to read tooltips to coerce the stack into what they're displaying it as... but this only works in english because of the translation, and there's no better way to do this. Create is lying about the amount of fluid in JEI.
