### ISSUE TITLE
[Bug] Doesn't work with Just Enough Archaeology.

### ISSUE THREAD

**Issue by QwertRvg** [emilyploszaj/emi#405]
When installing EMI alongside JEI and Just Enough Archaeology, that addon's recipes don't properly work.
The source blocks from brushing as well as the structure names are placed wrong. The menu becomes difficult to understand.
![image](https://github.com/emilyploszaj/emi/assets/89683173/9d07bea4-9e46-4465-a0de-49eee7b11983)

**Comment by emilyploszaj** [comment]
This is a bug with just enough archaeology placing its widgets outside of the display bounds.
