### ISSUE TITLE
Some recipies don't fill to the survival 2x2 Crafting grid when JEI is installed

### ISSUE THREAD

**Issue by aninusmuffin** [emilyploszaj/emi#408]
## How to reproduce:
- Install EMI 1.0.30+1.20.1+fabric
- Install JEI 15.2.0.27
- Open minecraft 😯
- Survival mode
- Get an Oak Log
- Switch to the Craftables view
- Click on the planks to fill craft
- Doesn't work

## This doesn't happen if:

- you are in a Crafting table
- in creative mode (no inventory crafting grid)
- JEI isn't installed

The log doesn't seem to show anything relevant: https://mclo.gs/W9g39fL

**Comment by emilyploszaj** [comment]
This should be fixed in 1.1.0
