### ISSUE TITLE
Tooltips Offset in Monobank Container

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#409]
When used alongside Monobank and viewing the contents of a monobank, the index tooltips are strangely offset to the left.
![2024-01-10_09 08 57](https://github.com/emilyploszaj/emi/assets/43504436/30acb799-7aa8-43f2-9974-05e9b0d3f7b1)
[latest.log](https://github.com/emilyploszaj/emi/files/13888764/latest.log)

**Comment by emilyploszaj** [comment]
This would be something caused by Monobank's render state that EMI can't control, best to report on their repo.
