### ISSUE TITLE
PrepareItemCraftEvent makes user disconnect

### ISSUE THREAD

**Issue by RubenPX** [emilyploszaj/emi#410]
```
Jan 10 17:44:03 apolo bash[641147]: [17:44:03 INFO]: ***** lost connection: Internal Exception: java.lang.IllegalStateException: PrepareItemCraftEvent cannot be triggered asynchronously from another thread.
```

Mod version: 1.0.29
Minecraft version: 1.19.2
Forge version: 43.3.2

**Comment by emilyploszaj** [comment]
`PrepareItemCraftEvent` seems to be a bukkit event? There's not enough context here and EMI does almost nothing on a dedicated server, so I'm closing this unless more information is provided
