### ISSUE TITLE
Add support to sophisticated backpacks

### ISSUE THREAD

**Issue by RubenPX** [emilyploszaj/emi#411]
It's possible to add support to sophisticated backpaks?

Mod link: https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
Core mod: https://www.curseforge.com/minecraft/mc-mods/sophisticated-core

![image](https://github.com/emilyploszaj/emi/assets/23123160/0ac927ba-259a-475c-9a81-5f2a308f0a2d)

**Comment by emilyploszaj** [comment]
sophisticated backpacks should be supported. Any custom JEI integration they have will be forwarded by JEI to EMI if you install both.

**Comment by Phoupraw** [comment]
> sophisticated backpacks should be supported. Any custom JEI integration they have will be forwarded by JEI to EMI if you install both.

Not entirely supported. Only `Destination.NONE` but no `Destination.CURSOR` or `Destination.INVENTORY`. It just fills the crafting slots but doesn't craft, the same as #499.
![2024-04-07_01 31 44](https://github.com/emilyploszaj/emi/assets/50520903/729c94fc-d29b-40b5-919a-dda85862fd9a)

**Comment by Phoupraw** [comment]
And, EMI doesn't detect any craftables, though there are actually some items craftable.
![2024-04-07_02 32 11](https://github.com/emilyploszaj/emi/assets/50520903/33869fe1-7989-43b4-8046-45db6edce922)

**Comment by RubenPX** [comment]
@emilyploszaj 

> And, EMI doesn't detect any craftables, though there are actually some items craftable. ![2024-04-07_02 32 11](https://private-user-images.githubusercontent.com/50520903/320227651-33869fe1-7989-43b4-8046-45db6edce922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzQ2ODYsIm5iZiI6MTcxMjQzNDM4NiwicGF0aCI6Ii81MDUyMDkwMy8zMjAyMjc2NTEtMzM4NjlmZTEtNzk4OS00M2I0LTgwNDYtNDVkYjZlZGNlOTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIwMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjJjNmZhOTBmOWQzOGE0YTU0YTU5MmJmNjU3NTg1M2RhYzkyNmEyNDFlMDcyNDk0ZmUzYmJiNzg3MTdlZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-dc3aGiotuUWSS_NwBD8IfqJN8x9Y3Yut4aSfwzlVU)

**Comment by emilyploszaj** [comment]
Sophisticated backpack's integration is provided by JEI, which doesn't support craft to cursor/inventory or craftables. Sophisticated backpacks would need to add first party integration to support these features.
