### ISSUE TITLE
EMI Renders Favorites in Waystones GUI

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#412]
Similar to Monobanks issue I raised earlier, this weird interaction is occurring where the favorites panel is displaying (and oddly at that) in the Waystones GUI. If the top panel is enabled and set to Favorites, it renders, too, but not with the jank. Just want to check with you to confirm this is or isn't on EMI's end.

![2024-01-12_13 21 54](https://github.com/emilyploszaj/emi/assets/43504436/9e81e0e4-b40f-4cb1-ac0d-3d40080e80e9)

**Comment by emilyploszaj** [comment]
This was fixed in 1.1.0, screens without slots no longer render in EMI.
