### ISSUE TITLE
[Bug] Crash upon opening inventory with a potion effect.

### ISSUE THREAD

**Issue by pauliesnug** [emilyploszaj/emi#413]
Hi, I splashed a fire resistance potion in the nether while using EMI + JEI and now upon opening my inventory, my game crashes. I believe the issue has to do with this mixin from the stacktrace: https://github.com/emilyploszaj/emi/blob/93e0d4f33f61299255947656367bd0429baa50a6/xplat/src/main/java/dev/emi/emi/mixin/AbstractInventoryScreenMixin.java#L75

My logs are: <https://mclo.gs/Nz874EW>

**Comment by emilyploszaj** [comment]
My mixin is in the log but it's not causing the issue, this is on porting lib

**Comment by pauliesnug** [comment]
> My mixin is in the log but it's not causing the issue, this is on porting lib

Ah sorry!! I just realized and was going to close this issue. The issue was actually https://github.com/Fabricators-of-Create/Porting-Lib/issues/75. Thank you! This mod is awesome
