### ISSUE TITLE
"accidently" deactivated interface

### ISSUE THREAD

**Issue by TheRasmus42** [emilyploszaj/emi#415]
Because I'm stupid, I disabled the HUD of EMI, so there is no search bar and also the EMI config button is gone.. 
In the modpack, darkrpg..., I can't find a hotkey to revert the clicks and get back the comfort of EMI. 

Any suggestions how I could solve this problem? 

Thanks in advance!

**Comment by fzzyhmstrs** [comment]
Ctrl + o, or go into mod menu and into the EMI config from that way

**Comment by TheRasmus42** [comment]
Hell... so easy.. thanks for the take!
