### ISSUE TITLE
[Suggestion] Useless large interface 

### ISSUE THREAD

**Issue by hikarosato** [emilyploszaj/emi#420]
Is that possible to make this interface narrower, and expand only when you need to show more than one recipe?

![image](https://github.com/emilyploszaj/emi/assets/35894722/033533b6-c396-4e24-a968-6a41b15e2e1d)

**Comment by emilyploszaj** [comment]
This is a conflict of desires. If EMI were to dynamically size the window to not take up too much space in cases like these, it would cause buttons and UI elements to move around in a way that is hard to use. Ultimately, there is nothing else that could go in that space, so it's fine as it is.
