### ISSUE TITLE
[Request] JEI-Like "Scrolling Tag Display" Config, Other Tag Display Options

### ISSUE THREAD

**Issue by IdrisQe** [emilyploszaj/emi#421]
Hi, so EMI is fantastic, easily my favourite recipe browser, but one thing I strangely miss from JEI is the way that tagged items would scroll through the possibilities on the recipe screen. So an item crafted with any plank would, each second or two, switch which plank was showing on the recipe. Don't get me wrong, I like the way that EMI handles tags with the X icon and the tooltip showing all the items, but it would be nice to have an option to also show the different items being scrolled through so you wouldn't need to hover to see what all is in the tag.

I get this is a completely pointless cosmetic change and wouldn't be high priority or anything, it'd just be nice to have as a config option!

Additionally, some alternative tag indicators would be nice. The little corner X is nice, but as I said earlier depending on item sprites or screen resolution or a number of factors, can be a little hard to see. It would be nice to have some configurable options, like perhaps a coloured border that shows around the crafting slot, or a slightly different coloured background, or any number of things. Just spitballing some ideas.

Thanks again!

**Comment by emilyploszaj** [comment]
The way EMI displays tags like it does is that cycling items are extremely bad for information density and presentation. Adding a setting to cycle tags would add unnecessary complexity for an option that is just worse for users.

The icons EMI uses for tags are textures that can be changed in resource packs like any other, if the */x/shape doesn't suit you.

More icons for tagged ingredients would be interesting, but seeing as slot background is currently used to represent if an ingredient is chance based or not, there's not a ton of room. This last suggestion may be revisited in the future, but for the moment I'm going to close the issue, thanks for your suggestions.

**Comment by IdrisQe** [comment]
> The way EMI displays tags like it does is that cycling items are extremely bad for information density and presentation. Adding a setting to cycle tags would add unnecessary complexity for an option that is just worse for users.
> 
> The icons EMI uses for tags are textures that can be changed in resource packs like any other, if the */x/shape doesn't suit you.
> 
> More icons for tagged ingredients would be interesting, but seeing as slot background is currently used to represent if an ingredient is chance based or not, there's not a ton of room. This last suggestion may be revisited in the future, but for the moment I'm going to close the issue, thanks for your suggestions.

I feel like "worse for users" is a bit subjective given I'd personally prefer it for clarity even if it is bad for information density, but okay. (Especially since if paired with the current tooltip system it wouldn't really have any less information) If anything the main issue is that usually whatever block is shown is one I don't recognize, meaning I then have to hover over to see what it actually is, while a changing item will usually flick by something recognizable before I even move my mouse. It feels more intuitive. That may just be because I'm used to TMI/NEI/JEI admittedly, but whatever. I feel like options never hurt to give.

Glad to know I can resource-pack it though, thanks for the info!

**Comment by SlimeChannel** [comment]
I wish that was a thing, because when I try to look the recipe for a statue upgrade from Statues mod, it just shows me the tag on both sides without telling what is actually upgraded, and because it's not that popular of a mod, it's really hard to find on the internet. That option would help a lot in that situation, so it's not just aesthetic side involved here
