### ISSUE TITLE
FTBFilteringSystem cause massive (2-3sec) lag on RenderThread when EMI installed (when opening the quest gui)

### ISSUE THREAD

**Issue by Exzept1on** [emilyploszaj/emi#422]
Mostly described here: https://github.com/FTBTeam/FTB-Mods-Issues/issues/1086

Steps: 
1. Install JEI + EMI
2. Install FTB Quests + FTBXModCompat + FTBFilterSystem
3. Create quest with item which matching any tag, for example `minecraft:planks`
4. Close your game.
5. Open your game.
6. Enter the world.
7. Wait EMI initialization.
8. Try to open quest gui.
9. Game freezes 2-3secs.
10. Try to open inventory (again freezes on 2-3secs).

**Comment by emilyploszaj** [comment]
Seems explained on their end
