### ISSUE TITLE
[1.19.2][UI issue] Misaligned UI elements when using the default Recipe Book

### ISSUE THREAD

**Issue by Beethoven-n** [emilyploszaj/emi#425]
All UI elements are misaligned when you use the vanilla Recipe Book.
The buttons render in the wrong position, and _are_ clickable, but only in their original positions.
Also, all items in the Index render missing, though they are also still clickable.
![image](https://github.com/emilyploszaj/emi/assets/44652883/0dfd12c8-0c0b-41ff-b956-32dd8de62f31)

Example of the craftable tooltips being misaligned too
![image](https://github.com/emilyploszaj/emi/assets/44652883/f3d0f93d-92e3-4540-8d24-5ca96705aabe)

Loader: Forge version 43.3.0
Minecraft version: 1.19.2
EMI version: 1.0.30+1.19.2+forge

**Comment by emilyploszaj** [comment]
This was a forge specific issue, and has been resolved in 1.1.1
