### ISSUE TITLE
[1.20.1] Fill Recipe not working in the player inventory crafting grid

### ISSUE THREAD

**Issue by ffuentesm** [emilyploszaj/emi#426]
EMI:emi-1.1.0+1.20.1+forge
Forge:47.1.3
JEI:jei-1.20.1-forge-15.2.0.27

For some reason, the quick craft function is not working for some recipes when you are outside a crafting table. 
Using the Fill recipe function on EMI or the Craftables Recipe window. Neither work on the player inventory, only on crafting tables.  
https://github.com/emilyploszaj/emi/assets/44974827/f6c7fa10-bbce-423c-a13f-6da224a428be

**Comment by aninusmuffin** [comment]
Weird, it seems 1.1.0 didn't fix the issue

Related: https://github.com/emilyploszaj/emi/issues/408

**Comment by emilyploszaj** [comment]
I misdiagnosed the issue, it's properly fixed in 1.1.1
