### ISSUE TITLE
Immersive Engineering (It doesn't show) + EMI+JEI 1.19.2 

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#427]
Minecraft 1.19.2
Forge 43.3.5

1. Emi-1.1.0+1.19.2+forge.jar
2. JER-Integration-4.5.0.jar
3. Jeimultiblocks-1.19.2-0.0.3.jar
4. Jei-1.19.2-forge-11.6.0.1018.jar
5. JustEnoughProfessions-forge-1.19.2-2.0.2.jar
6. JustEnoughResources-1.19.2-1.2.3.243.jar

![image](https://github.com/emilyploszaj/emi/assets/106809386/da654cd5-c179-47f6-852e-5fe5f431fb21)

**Does not show the recipe and structure**

![image](https://github.com/emilyploszaj/emi/assets/106809386/5a75ae07-2be6-42ce-9e6d-f5df7701d2d9)
This only applies to one structure in the screenshot above. Here they are just separated by molten objects)) it happened by accident)

Everything is a bit confusing here.
![image](https://github.com/emilyploszaj/emi/assets/106809386/2fbf7f78-e995-4e72-ac33-ea15fc0eac2d)

I'll explain now. There are 3 types of item search in EMU, as I understand it. When Creative or Registered are used individually, the structure of the building is not shown. You need to make the /reload command to reload the recipes, so as not to re-enter the world. 

Farther. If you set the combined mode, they will be shown, but not all of them and for some reason they are duplicated, and that's how I understood the buildings. In short, it's very confusing)) 

I use Google Translator. There may be errors in the text)

![image](https://github.com/emilyploszaj/emi/assets/106809386/8dd67faa-3163-44e4-a045-488a920fb7f6)
Here is an example from the combined mode where it shows in one case an item and its construction/recipe. But it does not show in the similar duplicated item below.

![image](https://github.com/emilyploszaj/emi/assets/106809386/b945366f-47ac-421a-ac28-0fd502e6b791)

**Comment by emilyploszaj** [comment]
The former collection of items are added by the mod just for display purposes, and the latter collection are the actual stacks. You're seeing the display items because your index source includes all registered items. If you'd like to not see them, use a different source or hide the stacks with hide mode.
