### ISSUE TITLE
It's real scary )))  Butchers Delight + EMI Render 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#428]
OMG hah))) Please can I fix this))))

Forge 43.3.5
Minecraft 1.19.2

Butchersdelight beta 1.19.2 2.0.9f.jar
Butchersdelight Foods beta 1.19.2 1.0.2.jar
Emi-1.1.0+1.19.2+forge.jar

![image](https://github.com/emilyploszaj/emi/assets/106809386/c50a3bf7-5d91-4771-80ce-d9cb69e3994d)
![image](https://github.com/emilyploszaj/emi/assets/106809386/b8054c7d-8b83-4663-ab48-676e19c95373)
![image](https://github.com/emilyploszaj/emi/assets/106809386/1f2f2eaf-ed3c-4916-bc36-0452e9a9b911)
![image](https://github.com/emilyploszaj/emi/assets/106809386/70f24d7c-e27b-43fe-bdcf-04fab283da92)
![image](https://github.com/emilyploszaj/emi/assets/106809386/63f4b93a-0cc7-4573-a60d-0efc426e722f)

**Comment by emilyploszaj** [comment]
If your index source includes all registered items, it will show all registered items. You can use edit mode to hide certain stacks you don't want to see.

**Comment by Krimatoria** [comment]
> Если ваш источник индекса включает все зарегистрированные элементы, он покажет все зарегистрированные элементы. Вы можете использовать режим редактирования, чтобы скрыть определенные стопки, которые вы не хотите видеть.

But the models are huge. Is this how it should be?

**Comment by emilyploszaj** [comment]
Mod devs are free to to make their item models look as huge as they want.

**Comment by Krimatoria** [comment]
> Разработчики модов могут свободно делать свои модели предметов настолько огромными, насколько они хотят.

Ok)))
