### ISSUE TITLE
"Move Effect" Option makes the effect card overlaps with the Recipe Book

### ISSUE THREAD

**Issue by Golder06** [emilyploszaj/emi#43]
As the title says, if you have the "Move Effect" option turned on and you open the survival Recipe Book, the effect "card" (for a lack of a better term) will overlap with the new Recipe Book tab.

Images for demonstration:
![image](https://user-images.githubusercontent.com/53577918/180714414-daf9c1ea-533d-462b-ad51-f9e6a52e8f72.png)
![image](https://user-images.githubusercontent.com/53577918/180714487-0393786e-0c26-457c-ab41-708be8f3b154.png)

**Comment by emilyploszaj** [comment]
Oh I thought I handled this properly, I'll get on it.

**Comment by emilyploszaj** [comment]
Fixed in 0.3.1
