### ISSUE TITLE
[EMI 1.1.0+1.20.1+forge] Percentaged output in recipe tree

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#432]
EMI indicates in the recipe that an item has a probability (here 50%) for the recipe (here cutting board) as an output. But in the recipe tree it doesn't show ~8 (4/50%) wild rice like in the fabric version.

Installed mods:
EMI 1.1.0+1.20.1+forge
Create 1.20.1-0.5.1.f
JEI 15.3.0.1
Farmer's Delight 1.20.1-1.2.4
![2024-02-08_13 48 35](https://github.com/emilyploszaj/emi/assets/159393991/5ead2d68-2d51-4777-a4f7-2a1a0d7f1650)
![2024-02-08_13 49 28](https://github.com/emilyploszaj/emi/assets/159393991/0929c754-6858-4988-afd6-2b62a136541d)

**Comment by emilyploszaj** [comment]
This is a bug with farmer's delight

**Comment by ghost** [comment]
No, Create also doesn't work

**Comment by emilyploszaj** [comment]
Create forge also doesn't implement an EMI plugin to communicate chance

**Comment by MrRedstone4848** [comment]
There could be the problem.

ingredients: [
  {
    "count": 1,
    "chance": 0.5,        <-Did you include this to the recipe tree calculations already?
    "item": "minecraft:flint"        <- This could be any other item
  }
],
...
(in JSON-File)

Both mods use this to provide a chance and there could many more mods which also use this method.

**Comment by MrRedstone4848** [comment]
I looked into the code: It seems that EMI doesn't uses
{
  "count": 1,
  "chance": 0.5,    <- this
  "item": "minecraft:flint"
}
as a chance or rounds it down (float to integer).

Where is dev.emi.emi.bom.TreeCost.calculateCost(...) called? I heavily believe the parameter chance of this method is wrong, 0 or 1.

**Comment by ghost** [comment]
Both mods use "chance" in the recipe JSON files to get this item only at the defined percentage

Create example: 
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "minecraft:gravel"
    }
  ],
  "processingTime": 250,
  "results": [
    {
      "item": "minecraft:sand"
    },
    {
      "**chance**": 0.1,
      "item": "minecraft:flint"
    },
    {
      "**chance**": 0.05,
      "item": "minecraft:clay_ball"
    }
  ]
}

Farmer's Delight example:

{
  "type": "farmersdelight:cutting",
  "ingredients": [
    {
      "item": "farmersdelight:wild_rice"
    }
  ],
  "result": [
    {
      "item": "farmersdelight:rice"
    },
    {
      "**chance**": 0.5,
      "item": "farmersdelight:straw"
    }
  ],
  "tool": {
    "tag": "forge:tools/knives"
  }
}

EMI just cannot handle the "chance" for its recipe tree calculations.

**Comment by emilyploszaj** [comment]
Vanilla has no concept of chance, what these mods are doing is adding a tooltip that mentions chance for JEI. JEI has no concept of chance, EMI does. A mod with an EMI plugin can specify its recipes have a chance for consumption/production.
