### ISSUE TITLE
[1.1.0+1.20.1+fabric] Incorrect shapeless recipes with 1 item create mod mixer

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#433]
Every shapeless recipe with 1 ingredient is also shown as Create automated shapeless crafting recipe.

Used mods:
EMI 1.1.0+1.20.1+fabric
Create Fabric 0.5.1-d-build.1161+mc1.20.1
Fabric API 0.91.0+1.20.1
![2024-14-08_02 15 47](https://github.com/emilyploszaj/emi/assets/159393991/681f0e73-4b29-4913-8c25-ec2e625038fd)
![2024-14-08_02 11 51](https://github.com/emilyploszaj/emi/assets/159393991/53706f5b-2efd-48e2-a1e0-c30a6e30a370)

**Comment by emilyploszaj** [comment]
This is a bug with create

**Comment by ghost** [comment]
But JEI and REI handle it anyway
