### ISSUE TITLE
[1.1.0+1.20.1+fabric] Potion fluids of Create mod are not registered correctly

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#434]
Every potion is an "Invalid Potion" in an Automatic Brewing recipe
![2024-02-08_02 34 02](https://github.com/emilyploszaj/emi/assets/159393991/17537a04-9a12-4477-af29-09d2ed03ca07)
But when I try it it shows its real name
![2024-02-08_02 31 53](https://github.com/emilyploszaj/emi/assets/159393991/05187077-67e6-49ba-92ea-c5bf78cab5d3)
![2024-02-08_02 31 56](https://github.com/emilyploszaj/emi/assets/159393991/14746cf2-79f8-40b2-aa67-d0974e7a2034)

There are no filling or emptying recipe tabs for water bottles, potions, splash potions and lingering potions either:
![2024-02-08_02 25 15](https://github.com/emilyploszaj/emi/assets/159393991/ef00fe30-b350-4107-a0b6-3ff4751c24af)
![2024-02-08_02 23 57](https://github.com/emilyploszaj/emi/assets/159393991/493692d4-e253-41e0-b639-58632183bca6)

**Comment by emilyploszaj** [comment]
This is a bug with create's fabric EMI plugin.

**Comment by ghost** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1106
