### ISSUE TITLE
Effects in compact mode display incorrect timer.

### ISSUE THREAD

**Issue by Lgmrszd** [emilyploszaj/emi#435]
When player has more than one effect (enabling compact mode) it displays incorrect remaining time.
For example, if given two effects of 60 seconds duration it shows as 20 minutes.

Tested on 1.20.4 with:
Fabric 0.15.3
Fabric API 0.92.0
EMI 1.1.0

**Comment by emilyploszaj** [comment]
This is fixed in 1.1.1
