### ISSUE TITLE
[emi-1.1.0+1.20.1] The mods of the enchanted book displays all is Minecraft

### ISSUE THREAD

**Issue by the-king-ai** [emilyploszaj/emi#436]
emi-1.1.0+1.20.1+forge:
![image](https://github.com/emilyploszaj/emi/assets/67614922/052e3780-4b92-4bdc-b652-329727b09d2c)

jei:
![image](https://github.com/emilyploszaj/emi/assets/67614922/20f7fa1c-0661-4837-800c-5ac3bea6089a)

**Comment by emilyploszaj** [comment]
This is simply a difference in what EMI and JEI consider the mod responsible for a particular item. In this case, minecraft is adding these books, and their identifier is `minecraft:enchanted_book`, so EMI displays "Minecraft"
