### ISSUE TITLE
Apotheosis + EMI

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#438]
Apotheosis-1.19.2-6.4.1.jar
Emi-1.1.1+1.19.2+forge.jar

Superimposing attribute characteristics on top of an EMI Recipe book
![image](https://github.com/emilyploszaj/emi/assets/106809386/feb9edbe-e191-4c7b-8212-7926f6ab1264)
![image](https://github.com/emilyploszaj/emi/assets/106809386/53871e8a-37f4-4a36-892a-f4f410f48261)

**Comment by emilyploszaj** [comment]
This is on Apotheosis's end, there seems to be no exclusion area at all present so EMI doesn't know to move.
