### ISSUE TITLE
Mouse Click stack FIX 1.19.2 

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#439]
Minecraft 1.19.2
Forge 43.3.5

emi-1.1.1+1.19.2+forge.jar
jei-1.19.2-forge-11.6.0.1018.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.3.243.jar

Clicking on the same item does not work. For example, I want to get a lot of boards, before I would just click a few times and I would add blocks. This is not happening now. I can only press Shift + click and do everything at once. But I can't get the right amount of items.

For some reason, only one item is added when clicked. Although I have plenty of ingredients to create the boards. They should be taken from the inventory, but this does not happen.

![image](https://github.com/emilyploszaj/emi/assets/106809386/7a93e5b2-2ee7-426a-88e1-e68a155b2ebe)

**Comment by emilyploszaj** [comment]
I can't reproduce this with just EMI in 1.19.2, can you reproduce this with just EMI or figure out what mods are causing this?

**Comment by Krimatoria** [comment]
> Я не могу воспроизвести это с помощью только EMI в 1.19.2. Можете ли вы воспроизвести это только с помощью EMI или выяснить, какие моды вызывают это?

In short) 

What items does the EMI: shift + click, click +1 item?
- stonecutter 
- foundry 
- the stove 

Works partially with a workbench :
- click + shift works 
- click +1 item - does not work 

I think this is a purely workbench problem. I have two mods that remove the recipe book from the code and optimize recipes. Perhaps this is some kind of shift conflict.

And honestly, I think few people need to click on one subject))))

> Another interesting point that I saw is that it turns out I can turn the mouse wheel and add items from the inventory to the vanilla workbench. It's very fast. But I can't do the same thing using the EMI book, for example) I don't know if it's meant to be that way or not.

Even if I have all the ingredients from which it can be made. I'll try later without mods purely with EMI and removing mods working with the book.

> They clean up the book and optimize the code. You can look at the forge)

- [nerb](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)-1.19.2-0.3-FORGE.jar
- [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)-1.19.2-7.1.4.jar

> It's everything else with a book or a workbench.

- VisualWorkbench-v4.2.4-1.19.2-Forge.jar
- FastSuite-1.19.2-4.1.1.jar
- FastFurnace-1.19.2-7.0.0.jar

**Comment by emilyploszaj** [comment]
FastWorkbench and FastSuite are known to break mods, I don't think EMI can do anything to work around it. If you want this function, you can try uninstalling these mods.

**Comment by Krimatoria** [comment]
> Известно, что FastWorkbench и FastSuite ломают моды, и я не думаю, что EMI может что-то сделать, чтобы обойти это. Если вам нужна эта функция, вы можете попробовать удалить эти моды - FastWorkbench и FastSuite

Oh, is it breaking? How? Can I get more details? maybe I should remove them too))) FastWorkbench, FastSuite

Otherwise I have about 200 WARN errors in the game) Although these are mostly recurring mistakes in terms of recipes or lack of textures. Maybe tags)
