### ISSUE TITLE
Search errors in RU/EN Languages TAGs

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#441]
Emi-1.1.1+1.19.2+forge.jar

Some recipes are not searched for in a specific language. I think this applies to a large number of recipes, not only [flint].
If you use an iron search, for example. I see only three items, by changing the language, I see all the items related to hardware in the game by tags, as it should work. But it does not work correctly in RU in the search.

![2024-02-16_16 12 01](https://github.com/emilyploszaj/emi/assets/106809386/c5fc1a56-a94a-4ec7-8458-ca562783050c)
![2024-02-16_16 11 29](https://github.com/emilyploszaj/emi/assets/106809386/335d3d19-6f2f-481e-aaa3-f45be65903e3)
![2024-02-16_16 11 54](https://github.com/emilyploszaj/emi/assets/106809386/0b5240cb-3e85-4d60-bccb-9a201b60eb54)
![2024-02-16_16 20 28](https://github.com/emilyploszaj/emi/assets/106809386/103a3d9a-a60c-4ad7-8e74-4193c17b6ebe)
![2024-02-16_16 20 34](https://github.com/emilyploszaj/emi/assets/106809386/e9992148-aad8-467c-8fe3-d9bfda5ce780)

**Comment by emilyploszaj** [comment]
I'm not sure what the issue you're reporting here is, EMI searches both by ID and by translated name, which is why stuff like "iron" and "flint" will show more results than translated names if mod devs have translated their items differently.

**Comment by Krimatoria** [comment]
> I'm not sure what the issue you're reporting here is, EMI searches both by ID and by translated name, which is why stuff like "iron" and "flint" will show more results than translated names if mod devs have translated their items differently.

You're right) I checked without EMI (just removed one mod) with the entire 280+ mods and JEI build. Yes, the same thing, the result is even worse. EMI shows many times more items)

![2024-02-17_22 47 47](https://github.com/emilyploszaj/emi/assets/106809386/a3f80966-5792-4fd2-8189-31cb03e8501b)
![2024-02-17_22 47 53](https://github.com/emilyploszaj/emi/assets/106809386/74db0d22-1420-4dd3-b207-fedeecd3212f)
