### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#442]
I pointed the mouse at the tree
![image](https://github.com/emilyploszaj/emi/assets/106809386/44aa738c-6548-476a-abd1-a0c8902556f2)

**Comment by emilyploszaj** [comment]
Can you describe what your issue is? It looks you have legendary tooltips installed, a mod that breaks the tooltips of several mods, including some of EMI's, and has made no effort to fix it. I recommend uninstalling legendary tooltips.
