### ISSUE TITLE
EMI not loading items into crafting grid from SSN to crafting grid

### ISSUE THREAD

**Issue by Jadan1213** [emilyploszaj/emi#443]
I use simple storage network for bulk item storage, and it has a crafting screen that lets you craft from items directly in the inventory. JEI detects this and will place items into the crafting grid properly, but EMI just shows that I don't have the items available.
![image](https://github.com/emilyploszaj/emi/assets/68805162/7adb2a7e-fdf6-4283-b1b9-50cb52e5f557)
![image](https://github.com/emilyploszaj/emi/assets/68805162/c8b2f81a-81e6-4390-a299-00245854e7da)

**Comment by emilyploszaj** [comment]
Install JEI along with EMI to get access to its integration like this one through EMI

**Comment by Jadan1213** [comment]
> Install JEI along with EMI to get access to its integration like this one through EMI

it won't cause any lag issue right? i removed JEI because i was getting an fps hit from it showing items

**Comment by emilyploszaj** [comment]
I can't vouch for JEI's performance along side EMI, if you want native EMI support without the need for JEI for SSN you can ask the author to add native EMI support.
