### ISSUE TITLE
Filter recipes for container

### ISSUE THREAD

**Issue by mateus3c** [emilyploszaj/emi#445]
It would be extremely helpful if we could filter recipes to only show the ones specific for the container being used. For example, when playing with mods that add other "crafting tables" like Farmer's Delight and their addons it is kinda difficult to keep track of what I can and cannot do with the cooking pot or with the keg etc. This applies to many other mods. Is this feature possible in any way?

**Comment by emilyploszaj** [comment]
Looking up uses of a workstation (like a cooking pot) will show you recipe categories that can be made there, and recipe categories (the tabs in the recipe screen) should represent unique processing types that are associated with workstations when looking up recipes.

**Comment by mateus3c** [comment]
> will show you recipe categories that can be made there

this doesnt seem to be the case, the only thing that is shown is the tags associated with the workstation block, also the 'craftables' page only shows the recipes I could make with the items on my inventory, so it isn't really helpful if I don't know what I could craft on a modded workstation to begin with

**Comment by emilyploszaj** [comment]
If a mod hasn't registered a workstation then the lookup won't show anything. You can additionally click the "view all recipes" button in EMI and browse every recipe for every specific recipe category.
