### ISSUE TITLE
[Suggestion] API-Only Integration

### ISSUE THREAD

**Issue by quiqueck** [emilyploszaj/emi#45]
A user of our Mod suggested to integrate EMI (quiqueck/BetterEnd#51). Since I really like your concept, I would like to do so. However we also have support for REI (and planed Support for JEI), which of course conflict with EMI.

That is why we like to integrate it as an optional Dependency. As far as I tested this appears to work fine. However, when developing I am can not disable EMI, which makes updating our other Integrations a bit cumbersome (have to disable all EMI related code, reconfigure the project to exclude EMI do my changes and then re-enable EMI).

It would be great, if we could integrate your Mod using `modCompileOnly` and `modRuntimeOnly` (similar to the way REI and JEI deliver their Mod).

If I try integrating EMI using `modCompileOnly`, the runtime will crash:
```
Caused by: java.lang.ClassNotFoundException: dev.emi.emi.api.stack.EmiStackConvertible
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
```

However, our code does not call any EMI-related code that could trigger this.

**Comment by emilyploszaj** [comment]
This was a bug with Loom that got fixed today. You can update to the latest Loom snapshot, or disable interface injection to continue using an older version of Loom. I'm sorry this has affected people.

**Comment by quiqueck** [comment]
Oh, nice. That was just some poor timing then :)
