### ISSUE TITLE
Wireless Pattern Encoding Terminal cannot fill in the patterns properly

### ISSUE THREAD

**Issue by LHC-mo** [emilyploszaj/emi#454]
minecraft version:1.20.1       EMI version:1.1.2      Applied Energistics 2 Wireless Terminals version:15.2.1
### Please provide support for "Applied Energistics 2 Wireless Terminals"
When i use Wireless Pattern Encoding Terminal,EMI cannot write the processing table into the processing patterns
EMI displays "Current workstation does not support recipe"
But when i use ME Patterm Encoding Terminal ,EMI can work normally.

![image](https://github.com/emilyploszaj/emi/assets/80680105/6f17d8e0-328d-4547-b1f1-58ed9cadecf0)

![image](https://github.com/emilyploszaj/emi/assets/80680105/3c6e1846-c2eb-4eba-a1e2-5242ef55a756)

**Comment by emilyploszaj** [comment]
This is a bug with gregtech with how they mixin to EMI, please report it to them

**Comment by LHC-mo** [comment]
That's true. Thank you for your reply
