### ISSUE TITLE
Recipe IDs no longer visible

### ISSUE THREAD

**Issue by MuteTiefling** [emilyploszaj/emi#459]
Version: emi-1.1.2+1.19.2+forge

When Dev mode option to show IDs and Advanced Tooltips are enabled, IDs are not shown. 

![image](https://github.com/emilyploszaj/emi/assets/9543430/4fa26504-7e9c-42a3-814c-8ff862162536)

Seems to only impact non crafting table recipes because those are still showing:

![image](https://github.com/emilyploszaj/emi/assets/9543430/b8243669-9485-4023-97e9-b4c5a61037c0)

**Comment by emilyploszaj** [comment]
This is very peculiar, are you able to favorite any of these recipes? Pressing [a] above a recipe should add it to the sidebar as long as it has an ID, and you'd be able to see it in the `emi.json` if it has changed? I'll look into it to see if I can figure it out.

**Comment by MuteTiefling** [comment]
Adding them to the favorites just adds the item stack itself as shown below
![image](https://github.com/emilyploszaj/emi/assets/9543430/baa60ce3-ce2f-493c-a2d0-7c69556400e5)

We can see there that I can favorite Polished Granite, but attempting to favorite any of the recipes that are in our hide list just favorites the stack itself. 

Further down, I've also favorited things like the compressed iron drill bit and iridescent source generator. These two recipes appear in the Ritual of the Forest crafting type; the same type used by the original conversion catalyst recipe we're trying to hide. For what it's worth though, every non minecraft recipe type I attempt to bookmark in this way shows the same in `emi.json`; no recipe ID, just the stack.

Due to an issue with the Patchouli implementation in Ars Nouveau and Nature's Aura, we're pretty much forced to do this trick where we put a fake recipe on the original crafting type, hide it, and then create our own custom recipe on the side. This prevents the Patchouli book from breaking because the ID it's looking for no longer exists.

**Comment by emilyploszaj** [comment]
Aha! Fortunately I've been able to reproduce this and figure out why it's happening, this will be fixed in the next version of EMI very soon, recipes are indeed not being assigned correctly after an update, thank you for reporting, I'll close this when I've released the version.

**Comment by MuteTiefling** [comment]
Seems like this (https://github.com/EnigmaticaModpacks/Enigmatica9/issues/890) might also be related? If not, let me know and I'll open a new issue for it.

**Comment by emilyploszaj** [comment]
Correct, EMI can only favorite a recipe if it can be serialized (i.e., has a consistent ID that points to it), which is the underlying issue here.

**Comment by emilyploszaj** [comment]
Fixed in 1.1.3

**Comment by MuteTiefling** [comment]
awesome thanks!
