### ISSUE TITLE
Unable to hide recipes by ID

### ISSUE THREAD

**Issue by MuteTiefling** [emilyploszaj/emi#460]
Version: emi-1.1.2+1.19.2+forge

Our scripts for this used to work in older versions of EMI. This is our script which writes out a JSON based on a list defined elsewhere: https://github.com/EnigmaticaModpacks/Enigmatica9/blob/master/kubejs/client_scripts/expert/emi_hide_recipes.js

The result of that script is here: https://gist.github.com/MuteTiefling/a229b52acb05d03130c1255bd3b7d9d6

Due to https://github.com/emilyploszaj/emi/issues/459 I'm unable to validate that that ID format (`"id": "jei:/naturesaura/animal_spawner/sheep_magenta"`)is still correct, however

**Comment by emilyploszaj** [comment]
After investigating #459, it is indeed the same issue, so I'll close this issue and track that one.
