### ISSUE TITLE
[Bug] Inventory overlay being doubled when using REI

### ISSUE THREAD

**Issue by Gamemassa** [emilyploszaj/emi#462]
Hi, I'm not sure if EMI is supposed to work with REI like it does with JEI, (if it's not, then I apologize for posting an irrelevant bug report) but when I do use it with REI I'm noticing the overlay being doubled on the right side.

![2024-03-10_19 08 37](https://github.com/emilyploszaj/emi/assets/18667108/16c54866-66a4-4ba0-a21d-bf1ea1ab0c35)

Switching REI to the left side and fooling around with layout options in both mods' configs partially fixes the issue, but some items are still overlapping each other (most importantly the search bars)

![2024-03-10_19 16 44](https://github.com/emilyploszaj/emi/assets/18667108/7faaff2a-9fe8-406c-bcaa-d00930fa6830)

(also, quick side note (and you probably can already tell anyway) there's a tiny bit of text in the background of the upper left corner, which is just my coordinates in my SP world and isn't part of the issue).

**Comment by emilyploszaj** [comment]
EMI is not intended to work with REI.

**Comment by Gamemassa** [comment]
> EMI is not intended to work with REI.

Wow, that was a fast response! And again, sorry for the inconvenience.

**Comment by emilyploszaj** [comment]
Don't sweat it, happened to have my email open.

**Comment by Gamemassa** [comment]
> Don't sweat it, happened to have my email open.

Actually, tbh, I think if EMI just had a way to actually set the search bar position (instead of just "Centered > Yes/No") that might fix my issue. Any chance that could be added in a future update?
