### ISSUE TITLE
Incompatibility with Snowee's Text Animator

### ISSUE THREAD

**Issue by BaconPalm** [emilyploszaj/emi#464]
Mod loader
Fabric

Minecraft version
1.20.1

Mod version:
1.1.3

Strange thing to have an incompatability with, but its about the only thing I can decypher from the error log:
![image](https://github.com/emilyploszaj/emi/assets/34732532/714ac4fa-c52a-4871-b57e-12bb9f7888de)

As you can see there's a null method invoked, which may be on their end, not yours but I'll repost this issue on their repository as well.
(Edit, the same crash is on their repository already, I jumped the gun...)

**Comment by emilyploszaj** [comment]
Yeah as noted, this is on their side.
