### ISSUE TITLE
[bug] 'Fill Recipe' Button Not Respecting Slot Max Count

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#47]
When a crafting block has a handler for auto-moving ingredients and you shift-click the [+] button, EMI will move items into slots beyond the slots stated maximum count via `getMaxItemCount`. As an example, I am integrating EMI into [my mod](https://github.com/fzzyhmstrs/ai), and the Imbuing Table crafting grid has a central slot with a maximum allowable item count of 1:
![image](https://user-images.githubusercontent.com/72876796/181782991-4f7f89c7-ee69-441b-9b3f-34cfdf1e8d28.png)

But when I use the shift click, EMI transfers 8x melon slices into the middle slot in the below example:
![image](https://user-images.githubusercontent.com/72876796/181783118-54526bcb-0a91-44f4-8338-8bed9cc8b01a.png)

With this behavior, if the user were to press the craft button for "4x Imbued Quartz", 7 of the melon slices are going to be overwritten, as the middle slot is both an input and an output (because it is an enhanced enchanting table), like so:
![image](https://user-images.githubusercontent.com/72876796/181783366-d37777c8-a60a-45bc-9412-ff66e224ab03.png)
(I'm in creative mode, so the other 12 ingredients didn't decrement on purpose)

Possible Solution:
If EMI is using `setStack` in the `Slot`, instead using `insertStack` may resolve this. `insertStack` automatically splits the inserted stack based on the allowable count, and returns the remainder that couldn't fit.

**Comment by emilyploszaj** [comment]
Oh inventory max count and how it plagues us forever. I'll get this fixed.

**Comment by emilyploszaj** [comment]
Fixed in 0.3.1

**Comment by fzzyhmstrs** [comment]
Is the intended behavior after the update to simply not fill the restricted slot at all? (Pic below after shift-clicking the recipe in 0.3.1)

![image](https://user-images.githubusercontent.com/72876796/183148105-af7996e3-7433-4f80-b36d-7dc90794ce7a.png)

**Comment by emilyploszaj** [comment]
Nope, this isn't intended, rats, can I see your code?

**Comment by fzzyhmstrs** [comment]
Definitely. What part of the code are you looking for? Below is my init in the screenhandler; it uses a fairly typical `addSlot` implementation. `ImbuingSlot` is just a tweak of vanilla slots that lets me shunt setStack to the inventory itself rather than having to pass through the slot (does nothing but avoid a redundant `markDirty()` call). I only use that functionality with REI because it was causing a massive blast of "onContentChanged" every time you transferred something...

[https://github.com/fzzyhmstrs/ai/blob/3e5842428bf292af033cbd852073ba9770ea2908/src/main/kotlin/me/fzzyhmstrs/amethyst_imbuement/screen/ImbuingTableScreenHandler.kt#L104](https://github.com/fzzyhmstrs/ai/blob/3e5842428bf292af033cbd852073ba9770ea2908/src/main/kotlin/me/fzzyhmstrs/amethyst_imbuement/screen/ImbuingTableScreenHandler.kt#L104)

**Comment by emilyploszaj** [comment]
I found where I went wrong with this, it's good that it's not filling the restricted slot, but I missed a line that did restriction properly, should be in the next update

**Comment by emilyploszaj** [comment]
Fixed (properly, hopefully) in 0.3.2
