### ISSUE TITLE
GregTech tools counted too many times

### ISSUE THREAD

**Issue by steph-lion** [emilyploszaj/emi#477]
GT tools come with a durability, as vanilla tools. The problem is, when used as a crafting material, they get counted as N, where N is the output items you want. In the screenshot: 3x hammers, 3x wire cutters.

I think it should be always considered as 1.

Example:
![image](https://github.com/emilyploszaj/emi/assets/52045633/8bf7f8a8-e83b-430f-898f-32b3b9502777)

**Comment by emilyploszaj** [comment]
This is a bug with gregtech not specifying their ingredients as having remainders.

**Comment by screret** [comment]
I am fairly certain we **do** specify the items as having remainders.

**Comment by screret** [comment]
right [here](https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/api/item/IGTTool.java#L473), in fact. for all tool types.

**Comment by emilyploszaj** [comment]
EMI has a concept for remainders on `EmiStack`s used in the inputs and outputs of recipes. By default, remainders are obtained for normal crafting recipes using the vanilla remainder system by assembling items in a crafting grid and calling the method, but any complex recipes or complex hooks (This seems to have access to a player during some hook?) EMI cannot provide cannot be done automatically. Your hooks do not interact with the actual recipe system so there is no way for EMI to be able to detect this.

**Comment by screret** [comment]
> EMI has a concept for remainders on `EmiStack`s used in the inputs and outputs of recipes. By default, remainders are obtained for normal crafting recipes using the vanilla remainder system by assembling items in a crafting grid and calling the method, but any complex recipes or complex hooks (This seems to have access to a player during some hook?) EMI cannot provide cannot be done automatically. Your hooks do not interact with the actual recipe system so there is no way for EMI to be able to detect this.

the player hook is only used for damaging the item, it'll return the stack anyway.
anyway, how should these be registered to EMI as damageable in some way?

**Comment by emilyploszaj** [comment]
In a recipe, remainders are defined using EmiStack.setRemainder
