### ISSUE TITLE
GregTech machines not recognized as catalysts

### ISSUE THREAD

**Issue by steph-lion** [emilyploszaj/emi#478]
When using tree, and using a recipe which uses a GT machine, its model does not appear in the tree.

![image](https://github.com/emilyploszaj/emi/assets/52045633/0e54e3b9-7482-4f0a-a9ae-c1020733bfb4)

By hovering it you can see the name but not the icon/model of the machine
![image](https://github.com/emilyploszaj/emi/assets/52045633/ea760dd7-de91-4d06-abad-21a3c30c581e)

**Comment by emilyploszaj** [comment]
From my understanding this is simply the gregtech machines being rendered inconsistently with vanilla items and something they would need to fix, I believe they have a bug open.

**Comment by embeddedt** [comment]
This appears to be an EMI bug that occurs if the batching renderer is disabled. Rendering of the GT machine is triggered by

https://github.com/emilyploszaj/emi/blob/44b478054a05f96dc935672566653596e49d1678/xplat/src/main/java/dev/emi/emi/screen/BoMScreen.java#L714

as it is the category for the recipe.
The [overload of `StackBatcher.render`](https://github.com/emilyploszaj/emi/blob/44b478054a05f96dc935672566653596e49d1678/xplat/src/main/java/dev/emi/emi/screen/StackBatcher.java#L152-L164) which is called here (the one accepting a `Batchable`) does not appear to fall back and render the Batchable manually if batching is disabled, unlike the one accepting an `EmiIngredient`. This causes the machine to simply never be rendered.

**Comment by emilyploszaj** [comment]
This is a correct diagnosis, weird, thanks.

**Comment by embeddedt** [comment]
This is probably fixed in the latest release since the code now checks for `StackBatcher` being enabled.

https://github.com/emilyploszaj/emi/blob/e06ba48d14d51aa1e221df3e3be75aec09fcf89c/xplat/src/main/java/dev/emi/emi/screen/BoMScreen.java#L713
