### ISSUE TITLE
Chance based output tooltip is confusing

### ISSUE THREAD

**Issue by pupnewfster** [emilyploszaj/emi#484]
When hovering over an output that has a chance set the tooltip is "Consumption chance: x%", which sounds like it is meant for chance based inputs. But when viewing the recipe in the recipe tree, it shows that it displays that it is properly left over and what the rough amount is.

Version: 1.1.1+1.20.4

**Comment by MrRedstoneToGo** [comment]
Yea, EMI's recipe tree is very buggy when dealing with chances. Which mod do these recipes come from?

**Comment by pupnewfster** [comment]
They will be coming from Mekanism https://github.com/mekanism/Mekanism/pull/8035

**Comment by Abbie5** [comment]
I can't reproduce this issue on the latest versions of EMI and Modern Industrialization on NeoForge 20.4.210.

![2024-03-21_21 29 17](https://github.com/emilyploszaj/emi/assets/43531981/eaae68b0-dd6c-45fc-89d3-568239819b85)

Did you set `.recipeContext(this)` on your output slots?

**Comment by emilyploszaj** [comment]
Abbie's on the right track here. Chance tooltips are based on whether EMI can tell if a recipe is an input or an output. Logical output slots should be defining their recipe context with `.recipeContext(this)` as Abbie said, which enables a handful of things in the slot hover, like changing consumption chance to production chance and displaying cost per batch of recipes utilizing recipe defaults. It's a bit of a confusingly named party of the API I will admit.

**Comment by pupnewfster** [comment]
Yeah, it works now, I was missing the recipe context. Thanks
