### ISSUE TITLE
Issue Regarding Items in a Tag and viewing recipes

### ISSUE THREAD

**Issue by ThePansmith** [emilyploszaj/emi#485]
Something related to hiding categories?

https://github.com/Nomi-CEu/Nomi-CEu-Modern/issues/178

**Comment by emilyploszaj** [comment]
This is working as intended with an issue on the modpack side. This modpack disables the `emi:tag` recipe category which is responsible for displaying tags when you look them up. When you look up recipes for a tag, the only thing that typically can exist is these tag recipes, and they've all been removed, so like an item with no recipes nothing is showing up.

**Comment by ThePansmith** [comment]
Oh, whoops. 

Sorry!
