### ISSUE TITLE
Crash when trying to view recipe of tech reborn advanced drill

### ISSUE THREAD

**Issue by Zetabite** [emilyploszaj/emi#49]
https://paste.ee/p/kj6RZ

**Comment by LemmaEOF** [comment]
Oh my god, modmuss what are you *doing* https://github.com/TechReborn/TechReborn/blob/1.19/src/main/java/techreborn/items/tool/DrillItem.java#L57

for SOME REASON the advanced drill is given -1 max damage, which is a HUGE assumption-breaker and I'm shocked doesn't end up having any issues in vanilla. EMI can fix this by ignoring tools with -1 max damage, but this is such a weird decision in the first place that I've got half a mind to go shout at TechReborn for it anyway

**Comment by Zetabite** [comment]
i totally get it :'D

**Comment by emilyploszaj** [comment]
This is actually already fixed in 0.3.0.
