### ISSUE TITLE
Fluids and Effects rendering behind mouse highlight

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#492]
Opening this tracking issue per the brief discussion in Discord today. Pasted here for reference. Fluids, Flamarine's Effect stacks, and possibly others render behind the mouse highlight square rather than in front of it.

Discord discussion
![image](https://github.com/emilyploszaj/emi/assets/72876796/79c1e8ec-6f5b-4b4c-9899-5a58ece51539)

Example of status effect stack being hovered over
![image](https://github.com/emilyploszaj/emi/assets/72876796/c0953214-faa8-4304-a266-7027decf48c6)

**Comment by emilyploszaj** [comment]
This was fixed for vanilla stack types in the latest release
