### ISSUE TITLE
ATM 9 No Frills Exception

### ISSUE THREAD

**Issue by Bimmr** [emilyploszaj/emi#495]
I tried to grab the log from after I joined the server, so hopefully this has enough info to be sort of helpful.

Versions:
emi-1.1.4+1.20.1+forge.jar
Forge-47.2.21

Log: [https://pastebin.com/8b86dpeT](https://pastebin.com/8b86dpeT)

Let me know if you need me to check/find anything for more information and I can grab that.

**Comment by emilyploszaj** [comment]
There doesn't seem to actually be anything fatal on any EMI threads in this log. Some mod is breaking creative tabs which has a fallback and otherwise it seems like EMI gets to the point of baking search before an OpenGL render crash not caused by EMI on the render thread.
