### ISSUE TITLE
Incompatibility with JEI + Visual Workbench; Craft to Inventory/Cursor doesn't work properly

### ISSUE THREAD

**Issue by Hati-** [emilyploszaj/emi#498]
Mod Loader: Quilt
EMI Version: 1.1.4+1.20.1+fabric
JEI Version: 15.3.0.4
Visual Workbench Version: 8.0.0

EMI's functionality to "Craft One to Inventory", "Craft All to Inventory", and "Craft one to Cursor" doesn't properly work when both JEI and Visual Workbench is installed. When using these functions EMI will fill up the workbench with the recipe properly, but wont do the crafting as expected. Removing either JEI or Visual Workbench fixes the issue, and EMI will do the crafting to Inventory and Cursor properly.

**Comment by emilyploszaj** [comment]
As noted in another issue, EMI can't provide this functionality because crafting is handled by JEI integration, which does nto support it. For this functionality, mods would need to add EMI integraiton.
