### ISSUE TITLE
[Bug] Lack of compability with Crafting Station: JEI Edition

### ISSUE THREAD

**Issue by Phoupraw** [emilyploszaj/emi#499]
Though [Crafting Station: JEI Edition](https://www.curseforge.com/minecraft/mc-mods/crafting-station-jei-edition) is compatible with JEI and EMI is compatible with JEI, there is still a little imcompability between them.
![2024-04-03_01 06 54](https://github.com/emilyploszaj/emi/assets/50520903/87d27638-8757-425a-8613-cafae16eff33)
1. GUI overlap
2. Crafting station doesn't support instant crafting. No matter how you click stack or recipe, items are just filled into the slots but no crafting.

(Though Crafting Station: JEI Edition is open source, it doesn't accept issue, so I can only comment this issue under its curseforge comments page, and report it here.)

**Comment by emilyploszaj** [comment]
Can you enable the dev exclusion area setting and send this screenshot again?

**Comment by Phoupraw** [comment]
![2024-04-04_18 27 44](https://github.com/emilyploszaj/emi/assets/50520903/af011c41-329a-4cbd-b3d4-50218b1996de)
I can't craft into inventory or craft into cursor. I can only fill in the slots.

**Comment by emilyploszaj** [comment]
This mod isn't defining any exclusion areas to EMI or JEI, so EMI can't move out of the way. They need to specify them in a plugin.
