### ISSUE TITLE
Cant escape out of the search box when in typing mode

### ISSUE THREAD

**Issue by frikinjay** [emilyploszaj/emi#5]
Click on the search box at the bottom then press escape key.

**Comment by emilyploszaj** [comment]
Currently enter or the focus bind (ctrl + f) will exit out of the search box, you can also click outside of the search. I'll be releasing 0.1.1 later tonight which adds support for esc as well, and will be closing this issue then, thanks for reporting.

**Comment by frikinjay** [comment]
I see, thanks for the reply.

**Comment by emilyploszaj** [comment]
Fixed in 0.1.1

**Comment by me0wing-katt0** [comment]
nope, still happens, please reopen

**Comment by emilyploszaj** [comment]
This is about certain keybinds, not about being stuck in search areas because off a Debugify issue. https://github.com/isXander/Debugify/issues/109
