### ISSUE TITLE
[Game Crash] Crash when right clicking on an item tag group.

### ISSUE THREAD

**Issue by f-raZ0R** [emilyploszaj/emi#50]
[crash-2022-07-30_12.00.56-client.txt](https://github.com/emilyploszaj/emi/files/9226946/crash-2022-07-30_12.00.56-client.txt)

**Comment by f-raZ0R** [comment]
Can not reproduce with just EMI, likely a mod compability issue.

**Comment by emilyploszaj** [comment]
This seems to only possible to occur if something prevented EMI from initializing, in which case EMI probably shouldn't have been able to interact with. Do you have any clue what scenario caused this?

**Comment by emilyploszaj** [comment]
Fixed in 0.3.1
