### ISSUE TITLE
[Bug] EMI 1.1.4 Fabric/Quilt - Crafting causes stack trace and sometimes crash 

### ISSUE THREAD

**Issue by znopp** [emilyploszaj/emi#502]
Not a crash log, but [it contains the error](https://mclo.gs/7MFevu5).

When trying to craft using EMI, and either crafting all or just one to your inventory, it causes a stack trace and the recipe to not be crafted.

If you at this stage click the item to craft it, the game also crashes.

**Comment by znopp** [comment]
I edited the title because it turns out that even if you do not craft to inventory, even just clicking the recipe and taking out the item from the inputted recipe causes [the game to crash](https://mclo.gs/2e2ssm9).

**Comment by znopp** [comment]
Actually actually, simply crafting in your inventory causes the same stack trace and the game to crash. I tried converting 16 coal blocks into coal, and when picking up the first 9 coal the game crashed.

**Comment by znopp** [comment]
Actually, for real this time, it's all crafting.

**Comment by emilyploszaj** [comment]
The stacktrace you've linked shows an error in quilt, not EMI, I'd report it to qsl.
