### ISSUE TITLE
The item index page obscures the UI of the mod workbench interface

### ISSUE THREAD

**Issue by AWAKEN-1** [emilyploszaj/emi#504]
When using the [Workshop for handsome adventurer](https://www.curseforge.com/minecraft/mc-mods/workshop-for-handsome-adventurer) mod,, tabs are not automatically indented, and above the UI
![2024-04-07_23 03 54](https://github.com/emilyploszaj/emi/assets/77484596/64eccba2-d16b-4078-96ac-7af471d45b82)
Although it is possible to adjust the number of rows and columns in the settings to avoid this if. But if there is a feature to make tabs automatically indented in this mod, I would appreciate it.（In JEI this page can be indented normally）

**Comment by AWAKEN-1** [comment]
![2024-04-07_23 52 36](https://github.com/emilyploszaj/emi/assets/77484596/601659a3-cc34-4713-a6e3-92dd7108bf08)
This is the screen when using JEI
![2024-04-07_23 55 47](https://github.com/emilyploszaj/emi/assets/77484596/14910228-598c-4e48-9f66-e5808df4ca17)

![2024-04-07_23 55 53](https://github.com/emilyploszaj/emi/assets/77484596/79fb16f0-ae5e-4871-a388-b8b37575f3af)

**Comment by emilyploszaj** [comment]
Your screenshot with exclusion areas show that the screen doesn't specify an exclusion area in EMI, but it appears to specify one in JEI. This should be rectified by installing JEI with EMI.
