### ISSUE TITLE
[Enhancement] Full support for adding items with custom nbt to favourites

### ISSUE THREAD

**Issue by mpustovoi** [emilyploszaj/emi#507]
At the moment, in addition to the usual items, only single custom potions or enchantment tools can be added to favorites.
It would be much better to be able to add more deeply defined nbt items to favorites (as in REI, I don't know about JEI). For example, chests or barrels with preset contents, spawn eggs of mobs with custom characteristics and equipment. In general, all that you can give yourself an item with a command, having previously generated it using MCStacker.
Yes, sometimes such items can contain a huge number of characters per line, but it's still very convenient.
I'm currently using the latest version of EMI for Forge 1.20.1

**Comment by emilyploszaj** [comment]
![image](https://github.com/emilyploszaj/emi/assets/14813658/c93bc1bf-3674-4c63-b1ac-5c3dd9cc57b6)
You can favorite items with arbitrary nbt, and multiple of the same item if they differ by nbt.

**Comment by mpustovoi** [comment]
I know I can add simple items to favorites. Something like this: `/give @p barrel{BlockEntityTag:{Items:[{Slot:0b,id:"minecraft:apple",Count:2b},{Slot:1b,id:"minecraft:bread",Count:4b}]}}`
![image](https://github.com/emilyploszaj/emi/assets/92390626/0d154a39-cbb0-47c6-bf4b-22d341fd7c02)
This function only works sometimes, and even then only with items in the player's hotbar, and not, for example, from a chest when it comes to such items:
![image](https://github.com/emilyploszaj/emi/assets/92390626/97699bb8-5a8d-46d9-b714-21451daf7cb2)
I have two double chests of such items :(
