### ISSUE TITLE
Conflict with Mekanism's Gauge Dropper

### ISSUE THREAD

**Issue by Sharparam** [emilyploszaj/emi#510]
The [Gauge Dropper](https://wiki.aidancbrady.com/wiki/Gauge_Dropper) in Mekanism can be used to interact with fluid or gas gauges in that mod to empty/deposit fluids/gases by left/right clicking them.

With EMI installed, it overrides the mouse click behaviour to instead show recipes or usages for the fluid/gas.

Even if the default left and right click keybindings for showing recipes or usages are changed/removed, it still blocks the dropper usage (and instead nothing at all happens when clicking).

Disabling EMI, either by disabling the mod completely or using the in-game option to disable it, makes the Gauge Dropper work normally.

Image of the gauges I'm talking about, with the Gauge Dropper hovering over it (left clicking here *should* empty that gauge and deposit it into the dropper, but with EMI installed it opens the recipe view instead):

![image](https://github.com/emilyploszaj/emi/assets/551094/c6d2bd54-f68f-4aa0-a60d-55419f7d0be0)

Minecraft version: 1.20.4
NeoForge version: 20.4.214
EMI version: 1.1.4+1.20.4+neoforge
Mekanism version: 10.5.11

**Comment by emilyploszaj** [comment]
This is related to Mekanism's EMI integration and should be reported to them.

**Comment by Sharparam** [comment]
Turns out it was actually already fixed in the latest version of Mekanism, I just missed it when skimming their changelog :facepalm:
