### ISSUE TITLE
[Bug] Mouse wheel scrolls 3 index pages instead of 1 on macOS

### ISSUE THREAD

**Issue by unilock** [emilyploszaj/emi#511]
On macOS specifically, when scrolling the mouse wheel to navigate between pages of EMI's index, each "click" of the wheel (individual event?) moves 3 pages ahead (or behind) instead of only 1 page.

This can be worked around by either enabling "Discrete Scrolling" in Minecraft's "Mouse Settings", or by installing another mod such as [MacOS Input Fixes](https://github.com/hamarb123/MCMacOSInputFixes) (both of which may not exist for every version).

As far as I know (and have tested), this issue persists across every EMI version, from 0.1.0 to 1.1.4, from Minecraft 1.4.7 to 1.20.4.

***

[MouseTweaks](https://github.com/YaLTeR/MouseTweaks) has a similar issue, and has implemented a toggleable workaround for it ("ScrollItemScaling"):
- https://github.com/YaLTeR/MouseTweaks/pull/22:
  > [ScrollItemScaling is a] way to have it transfer exactly one item on each scroll event, rather than proportionally to the wheel delta reported. This makes it match up with the "bumps" on my mouse's scroll wheel.
- https://github.com/GTNewHorizons/MouseTweaks/pull/4
  > ScrollItemScaling allows either transferring an amount of items proportional to the scrolling speed *(EDIT: as reported by the mouse),* or always transferring *only one* item per scroll event (which is useful on macOS).

***

This is my (crude) workaround for retroEMI ([source](https://git.sleeping.town/Rewind/retroEMI/src/commit/038b2be78d9c42db18d8cfca1f567b07220aab96/nil/src/main/java/com/unascribed/retroemi/RetroEMI.java#L334)):

<img alt="image" src="https://github.com/emilyploszaj/emi/assets/11802133/acd216d1-fb28-4d9b-b3d8-8bbb99be43e1">

I'm not sure how applicable it is to modern EMI.

**Comment by emilyploszaj** [comment]
"Discrete Scrolling" is the option in minecraft that specifically ignores magnitude in scrolling, which EMI inherits from vanilla. Scrolling 3 pages at once, while weird, is "correct behavior" according to how minecraft defines scrolling events.

**Comment by unilock** [comment]
I guess that makes sense, but it does make EMI's various scrollable menus (the index, as well as recipe categories) difficult to navigate without manually clicking the arrow buttons - and Minecraft's own menus (the chat HUD, creative mode inventory, etc.) seem to move "too fast" with "Discrete Scrolling" enabled - all in my own opinion...

I would suggest that EMI have its own separate "Discrete Scrolling" option, but that's probably too niche a feature. (maybe I should just backport it to 1.4.7, sob)
