### ISSUE TITLE
Create Sequence Crafting

### ISSUE THREAD

**Issue by Groundcrafter** [emilyploszaj/emi#514]
When a Create Sequence has more than a single run, it calculatetes only 1 times all needed Items, but in this exaple it needs 5 runs, that means it needs 1 Golden Plate and 5 small cogwheels 5 Large Cogwheels and 5 Iron Nuggets.
![image](https://github.com/emilyploszaj/emi/assets/52048738/d6825a87-fad3-4976-9114-d6117a322d4c)
![image](https://github.com/emilyploszaj/emi/assets/52048738/431127bb-c08e-4064-8bf0-0f10242be8bf)

**Comment by emilyploszaj** [comment]
Create exposes what you see in the recipe tree. For it to be correct, create would need to add first party EMI integration.
