### ISSUE TITLE
Incorrect Item Count in Machine Recipe

### ISSUE THREAD

**Issue by ArchEzekiel** [emilyploszaj/emi#515]
In GregTech, many recipes will require multiple of an item in a single craft, like this Circuit
![image](https://github.com/emilyploszaj/emi/assets/66336623/0cc481a6-687e-441d-adc9-20db0d085007)
In the specific case of the machine it thinks I need 2 diodes for each of the diodes in the recipe
![image](https://github.com/emilyploszaj/emi/assets/66336623/aa264766-09c5-444a-84f5-f6c6b2ea7df3)
This isn't an issue for regular crafting table recipes
![image](https://github.com/emilyploszaj/emi/assets/66336623/7d5e728c-3ab8-4dc7-99dc-73521db2ff80)
This is a really odd issue, and it feels like something that would have been fixed by this point considering how likely people would have run into this issue already, so if this is user error than I would appreciate some guidance on how to avoid this

**Comment by ArchEzekiel** [comment]
More info: Even though the tree itself has the incorrect quantities, the "Total Cost" is actually correct, as well as the helper functionality to track progress, so I guess this is a tree specific issue
![image](https://github.com/emilyploszaj/emi/assets/66336623/5a67f8fa-2703-465b-b39a-ce9d00fd82ca)

**Comment by emilyploszaj** [comment]
Gregtech makes several annoying and invasive mixins and incorrect implementations in EMI to the extent I can't debug this issue because it's impossible to know to what extent I'm even responsible. You'll have to bring it up with them.
