### ISSUE TITLE
Emi cheat mode can trigger UWRAD and kick player

### ISSUE THREAD

**Issue by liangmoe** [emilyploszaj/emi#516]
I tested both fabric and forge emi, and this would only happened with emi forge

Producs stepes: install forge emi and [UWRAD](https://modrinth.com/mod/uwrad/versions), cheat item from emi's tab and get kicked

lates.log: https://mclo.gs/pDR4D3P

https://github.com/emilyploszaj/emi/assets/135343248/50f24c5f-1a01-4644-9f7d-74f08a3c38df

**Comment by emilyploszaj** [comment]
I'm unclear how this could be possible, EMI's packet application is handled by Forge's executor which has docs that promise the code is executed on the "main thread". Is this a bug in forge?

**Comment by embeddedt** [comment]
The call to `handler.accept` [here](https://github.com/emilyploszaj/emi/blob/02eb1d636d6cb3f6ffcc1348599dd4ce32aba479/forge/src/main/java/dev/emi/emi/platform/forge/EmiPacketHandler.java#L43) is not wrapped in an `execute` call.

**Comment by emilyploszaj** [comment]
Oh this does not extend to neo. Why does forge have distinct read and application events if it's not going to wrap your application in an execute??

**Comment by emilyploszaj** [comment]
This was fixed in 1.1.7
