### ISSUE TITLE
[FEATURE REQUEST] Hide effects on EMI overlay

### ISSUE THREAD

**Issue by Jadan1213** [emilyploszaj/emi#517]
As stated in the discord, would you be able to include an option for the effects to be hidden in the EMI overlay. Since I use InventoryHUD+, I have these effects in another location on screen. Thank you so much.

![2024-04-18_14-49_Capture_365](https://github.com/emilyploszaj/emi/assets/68805162/61c6e230-4182-4e7f-b960-29a801a7b7ef)

**Comment by emilyploszaj** [comment]
Implemented in 1.1.16, thanks for the suggestion
