### ISSUE TITLE
Recipe Tree Enhancements

### ISSUE THREAD

**Issue by ChloeDawn** [emilyploszaj/emi#522]
**Mod version:** 1.1.4+1.20.1+fabric

I would love to be able to favourite/pin recipe trees, either in the sidebar, or in the tree interface with tabs or something similar, so that I can have multiple active at one time. I would also love to be able to screenshot a recipe tree much like a recipe.

**Comment by emilyploszaj** [comment]
This is tracked in #125 and planned
