### ISSUE TITLE
EMI doesnt work with gamephases

### ISSUE THREAD

**Issue by hellwolf95** [emilyploszaj/emi#523]
the main issue with it is emi doesnt really update and hide/unhide mods and items when unlocking gamephases

**Comment by emilyploszaj** [comment]
EMI does not currently support live editing of registered recipes and stacks or the visibility of them, however gamephases could have integration by using vanilla datapack reloads. Either way, EMI can't provide this integration, only adding features to make it more convenient.

**Comment by hellwolf95** [comment]
yeah doing a datapack reload is far more inconvenient then not having the mod installed. so sadly guess it will have to be
