### ISSUE TITLE
Tag translation key doesn't behave as expected for custom registry types

### ISSUE THREAD

**Issue by pupnewfster** [emilyploszaj/emi#529]
Emi: 1.1.6
MC: 1.20.6
NeoForge: 20.6.22-beta

For custom registries (which mekanism has for its chemicals) it seems `EmiTags#getTagTranslationKey` does not behave the same as `net.neoforged.neoforge.common.Tags#getTagTranslationKey `. This is because if the registry is not in the vanilla namespace, EMI just ignores the registry and doesn't include it in the translation key, whereas neo adds both the namespace and path of the registry to the translation key.

**Comment by emilyploszaj** [comment]
I've adjusted my implementation in 1.1.7 to adhere to the implementation neo has gone with
