### ISSUE TITLE
EMI crashes when hovering item with minecraft:hide_tooltip component (1.20.6, Fabric)

### ISSUE THREAD

**Issue by Patbox** [emilyploszaj/emi#530]
EMI crashes when ItemStack with hide_tooltip component is hovered in inventory, if option for appending mod name enabled.

You can create this item with `/give @p minecraft:sculk[minecraft:hide_tooltip={}]`

It happens due to https://github.com/emilyploszaj/emi/blob/1.20.5/xplat/src/main/java/dev/emi/emi/mixin/ItemStackMixin.java#L25 being injected at both returns, one that uses List.of() for disabled tooltips and the old/regular one that uses ArrayList.

**Comment by emilyploszaj** [comment]
Should be fixed in 1.1.7
