### ISSUE TITLE
Option to move keybinds into regular keybinds UI

### ISSUE THREAD

**Issue by ryleu** [emilyploszaj/emi#533]
I would like to see an option to move the keybinds into the vanilla keybind UI so that it can be used with Controlify and other mods that rely on the regular keybinds system.

**Comment by emilyploszaj** [comment]
EMI cannot do this, its keybind system is much more advanced than vanilla, each input can have multiple binds, it uses modifier keys, it supports layering binds intelligently rather than conflicting, and more.
