### ISSUE TITLE
Interaction with Mouse Button 4 and higher - Disabled JEI Interaction

### ISSUE THREAD

**Issue by PurpleDeving** [emilyploszaj/emi#538]
Hey, as talked about in the discord:

Here a "official" Issue for my Feature Request.

Current Intraction:

* Jei Enabled
* JEI Keybind "Show Uses" set to Mouse Button 5
* EMI "View Uses" set to Mouse Button 5

Expected Behaivor:

Hovering over any item. In a crafting recipe, in an inventory, in EMI or in the inventory + pressing Mouse Button 5.
- > Should show the uses of the given item.

Curent Behaivor:

If the EMI Keybind is set: It shows the recipes if clicked while hovered in EMI + in the recipe View.
In the Inventory/Chests/Machines: Even if booth Keybinds are set: Clicking Mouse Button 5 while hovering over the item does nothing.

I attach our discord communication if any Information are missing.

Thanks already ! 
![grafik](https://github.com/emilyploszaj/emi/assets/111588944/c926785a-8dfa-46d8-a2b5-c3aad9eec090)
![grafik](https://github.com/emilyploszaj/emi/assets/111588944/e5d8ab7c-15b7-4dc7-b2c3-51110a89fdbe)

**Comment by emilyploszaj** [comment]
This has been implemented in 1.1.7
