### ISSUE TITLE
When installed with REI overlaps search bar and right pane

### ISSUE THREAD

**Issue by lospejos** [emilyploszaj/emi#54]
When installed with `Roughly Enough Items` (**REI**) mod  overlaps search bar and right pane.

IMHO mod may detect if REI is present and warn user about this with suggestion to uninstall one of these mods.
Another option would be  adding REI to a `breaks` section of `fabric.mod.json` like this:
```
...
"breaks": {
    "roughlyenoughitems": "*"
  },
...
```

**Comment by emilyploszaj** [comment]
EMI and REI can function together and some people prefer to run both mods at the same time, toggling between them for compatibility. There is no reason to break this setup, and really, if someone installs both mods, they know what they're doing.
