### ISSUE TITLE
[question] How to re-enable EMI without modifying configuration files?

### ISSUE THREAD

**Issue by bling-yshs** [emilyploszaj/emi#543]
I made a video introducing the features of EMI, but some people asked me, "I accidentally disabled EMI. How can I re-enable it?"

Honestly, I don't know either. I only know that modify the `enabled` option in `emi.css` (but beginners might not know how to do that), or simply delete `emi.css`.

So, I want to ask, can you consider adding a shortcut key to open the in-game EMI settings?

**Comment by fzzyhmstrs** [comment]
Ctrl + o is an existing shortcut to re-enable EMI, or use mod menu to get to the in-game config screen, if you have mod menu installed

**Comment by bling-yshs** [comment]
> Ctrl + o is an existing shortcut to re-enable EMI, or use mod menu to get to the in-game config screen, if you have mod menu installed

thank you!
