### ISSUE TITLE
Automatically support c:hidden_from_recipe_viewer for custom stack types

### ISSUE THREAD

**Issue by pupnewfster** [emilyploszaj/emi#545]
It would be useful if instead of just the builtin types EMI also would also check the hidden from recipe viewer tag for custom stack types when there is a corresponding registry adapter added so that EMI knows how tags of that type work.

**Comment by emilyploszaj** [comment]
This is implemented for stack types whose `key`s match an existing registry adapter as of 1.1.7, thanks for the suggestion!
