### ISSUE TITLE
Crash at search edit box, maybe due to IME chatting mod

### ISSUE THREAD

**Issue by zecheki** [emilyploszaj/emi#552]
There is an issue with CaramelChat (the mode for input IME chats) in the search edit box.

I think a simple null check code could be added to fix this.

If not, let me know. I will ask to the caramelchat mods.

crash log: https://mclo.gs/fmNi2af

**Comment by emilyploszaj** [comment]
If this issue is caused by another mod changing vanilla behavior it should be reported to them.
