### ISSUE TITLE
calling EmiIngredient.of(tag, amount) with a conflicting tag makes an empty ingredient instead of one referencing the vanilla one

### ISSUE THREAD

**Issue by screret** [emilyploszaj/emi#554]
the loading system is checking for tag collisions and preferring the MC tag, but the getRawValues method doesn't do that, so it ends up returning an empty tag. This is then passed down the call chain to `EmiIngredient.of(TagKey<Item>, long)` and creates an empty ingredient with only an amount.

`EmiTags#reloadTags` calls `EmiTags#consolodateTags` -> `EmiTags#betterTag` which ends up picking the MC tag over the duplicate forge one, but `EmiTags#getRawValues` doesn't do this.

originally at https://github.com/emilyploszaj/emi/issues/534#issuecomment-2133441042 .

**Comment by emilyploszaj** [comment]
This has been adjusted in 1.1.7 and should no longer occur.
