### ISSUE TITLE
[Suggestion] Deeper Crafting Tree

### ISSUE THREAD

**Issue by HoodBlah** [emilyploszaj/emi#559]
Sometimes when I am looking at the crafting tree for a recipe only the immediate crafting components are shown, not the components of those components. 

For example:
Immersive airships hot air balloon needs sails and other components, but the crafting recipe of the sails won't show when looking at the crafting tree of the hot air balloon.

(Also, I do play on a server mainly and as far as I know the server uses jei not emi so that may be part of the problem, but some other items do show the full tree.)

**Comment by emilyploszaj** [comment]
Please read the help tooltip in the crafting tree screen, you can manually break down recipes and set your own defaults.

**Comment by HoodBlah** [comment]
I thought it was automatic :'(

If I get emi on the server will it help?

**Comment by emilyploszaj** [comment]
There is no reasonable heuristic for when EMI should and should not expand recipes. Mod and modpack makers can set their own defaults to make it work better, but as a user you will have to expand the tree as much as you want.

**Comment by HoodBlah** [comment]
Alright, guess I'll start making one.
Will there be a feature in the future that will do it automatically?

**Comment by emilyploszaj** [comment]
It does do it automatically based on the defaults.
