### ISSUE TITLE
Ad Astra's planet screen not scrolling when EMI is installed

### ISSUE THREAD

**Issue by AveryHazel** [emilyploszaj/emi#561]
For some reason it seems like when EMI and Ad Astra are both installed the planet selection screen doesn't scroll, likely because it's where the favorites screen is. I believe this might be able to be fixed by disabling EMI in the planet selection screen, but I am not sure. EMI doesn't show up over the selection screen, and it's underneath. If you need more information I can be reached on Discord (dyl_the_pill), since I don't check github often.

**Comment by emilyploszaj** [comment]
This seems to be related to the structure of Ad Astra's planet screen being counted as an inventory. I'm unsure why it would behave like this and not specify either exclusion areas or a large area for EMI to not inhabit. I'm unsure if there's a reasonable solution on my end.

**Comment by AveryHazel** [comment]
alright, thanks!
