### ISSUE TITLE
emi rendering screen crash

### ISSUE THREAD

**Issue by loti1234** [emilyploszaj/emi#562]
[latest.log](https://github.com/user-attachments/files/15525402/latest.log)

[crash-2024-06-02_14.58.59-client.txt](https://github.com/user-attachments/files/15525413/crash-2024-06-02_14.58.59-client.txt)

**Comment by loti1234** [comment]
further context: this crash happens with the new immediatelyfast item rendering

**Comment by emilyploszaj** [comment]
Have you reported this to immediatelyfast?

**Comment by loti1234** [comment]
imma also do that since immediatelyfast is also having crash and bug issues recently for some reason
