### ISSUE TITLE
Could you add dark mod?

### ISSUE THREAD

**Issue by Immortal-Sty** [emilyploszaj/emi#564]
This is REI. I think EMI is more useful than REI, but EMI does not have dark mode, which is not quite compatible with my current MC interface. Could you please add dark mode to EMI?

![图片](https://github.com/emilyploszaj/emi/assets/94347641/acad95b8-5ac8-461e-9cba-1db0fc2f7c23)

![图片](https://github.com/emilyploszaj/emi/assets/94347641/e7fdfb7f-1bf1-427b-8a43-2230f319c9e9)

**Comment by emilyploszaj** [comment]
This is something better suited to a resource pack, you should check curseforge.
