### ISSUE TITLE
[1.20.6][Compatibility]There may be some bugs in the GUI section of EMI when installing Iris to enable shaders

### ISSUE THREAD

**Issue by bbz-233** [emilyploszaj/emi#565]
**Description**
When installing Iris and EMI in the game, Opening the shader can cause some abnormalities in EMI's GUI rendering

**Images**
![image](https://github.com/emilyploszaj/emi/assets/92072976/4d05a02b-8468-4fa5-82a4-f810a9c42c45)
![image](https://github.com/emilyploszaj/emi/assets/92072976/f89a9b82-d52d-4cb1-baf4-9f2caa19033e)
![image](https://github.com/emilyploszaj/emi/assets/92072976/eeacaee8-f1d9-4a9b-8221-e21f59b0ff3d)

**Remarks**
When adding resourcepacks with modified block/item models, this situation becomes more severe
If additional information is needed, I will provide it as soon as possible

**Version**
MC: 1.20.6+Fabric 0.1.5.11+Fabric API 0.100.0
EMI:  1.1.6+1.20.6+fabric
Iris: 1.7.0+mc1.20.6
Sodium: 0.5.8+mc1.20.6

**Comment by fzzyhmstrs** [comment]
This is known, and open issue with Iris for a *long* time, unfortunately. It is an issue on their end. You can disable "Batched Rendering" in the EMI config to work around it. Feel free to leave a comment on the Iris issue to push the point: https://github.com/IrisShaders/Iris/issues/1779

**Comment by bbz-233** [comment]
Thanks, This is actually an older bug 😨
