### ISSUE TITLE
[incompatibility / crash] EMI crashes with Lunar Client

### ISSUE THREAD

**Issue by noawx** [emilyploszaj/emi#566]
Crash Log: https://mclo.gs/eobxo5i
Game Log: https://mclo.gs/P7WPf7f

Lunar Client has a feature where you can install third-party fabric mods in any version above 1.16.5

When using EMI with Lunar Client, a crash occurs; Lunar Client seems to crash some heavier mods, but not some lighter mods?

I have noticed that:
**Mods that crash with Lunar Client:** Create Fabric, EMI
**Mods that do not crash with Lunar Client:** JEI, JourneyMap, Litematica, MaLiLib, Mod Menu

If this is an issue mostly on Lunar Client's end or not worth resolving, feel free to close this issue.

**Versions:**
Minecraft: 1.20.6
Fabric Loader: 0.15.11
Fabric API: 0.100.0+1.20.6
EMI Version: 1.1.6+1.20.6+fabric

**Comment by emilyploszaj** [comment]
This is on lunar.

**Comment by N0aW** [comment]
Ok. Thanks for the clarification
