### ISSUE TITLE
IGuiContainerHandler#getGuiClickableAreas from JEI Not Work

### ISSUE THREAD

**Issue by Sleepwalkerx** [emilyploszaj/emi#574]
mezz.jei.api.gui.handlers.IGuiContainerHandler#getGuiClickableAreas - does not work on any version of the mod.
As I understand it, it simply has not yet been implemented in EMI. Is it possible to implement it?

**Comment by emilyploszaj** [comment]
EMI does not have an analog of this behavior, the lack of implementation is intentional at the moment.
