### ISSUE TITLE
[1.21] Error logs

### ISSUE THREAD

**Issue by NielsPilgaard** [emilyploszaj/emi#577]
Hi!

I'm not seeing any actual issues, I just thought it might be nice for you to know that these things are logged 😄

[latest.log starting at emi](https://gist.github.com/NielsPilgaard/3959b3c1b5898e8e26f2e845e299634c#file-gistfile1-txt-L603)
[full latest.log](https://gist.github.com/NielsPilgaard/3959b3c1b5898e8e26f2e845e299634c)

---

- emi-1.1.7+1.21+neoforge
- jei-1.21-neoforge-19.0.0.3

**Comment by emilyploszaj** [comment]
These were blocked by arch loom updating, which it finally did today, resolved in 1.1.9
