### ISSUE TITLE
[1.21 Neo] Crash when fluid still texture is null

### ISSUE THREAD

**Issue by TelepathicGrunt** [emilyploszaj/emi#579]
> if a fluid returns null for its still texture, it'll crash EMI. Maybe it should just skip trying to render the fluid instead? Found that the hard way when Resourcefullib had a bug that caused my fluid to return null still texture to JEI and EMI. JEI did a fix to not render the fluid if null.

Log: https://pastebin.com/raw/exxEjCCs

**Comment by emilyploszaj** [comment]
This behavior was adjusted in 1.1.8
