### ISSUE TITLE
Tab selections do not expire.

### ISSUE THREAD

**Issue by AmyMialee** [emilyploszaj/emi#58]
When selecting a button using the tab button, it will never stop being selected unless toggled off with tab manually.
This leads to overlap with other elements, and confusion for those who didn't realise tab was an option.

![image](https://user-images.githubusercontent.com/10999535/183230856-c61ea47a-d5bb-453b-834d-af1a957229ac.png)
![image](https://user-images.githubusercontent.com/10999535/183230861-2be41d7f-9c7f-4a39-b078-b47a72910b3a.png)

**Comment by emilyploszaj** [comment]
Fixed in 0.3.2
