### ISSUE TITLE
[Bug] Item group has no page Crash

### ISSUE THREAD

**Issue by diconix4k** [emilyploszaj/emi#580]
Hello, the game functions normally in survival mode, but it crashes whenever you switch to creative mode and open the inventory.

[crash-2024-06-20_11.14.46-client.txt](https://github.com/user-attachments/files/15911627/crash-2024-06-20_11.14.46-client.txt)

**Comment by NovaLynxie** [comment]
I have been experiencing the same issue. Same error message as well.
This mod does load normally in creative menus with some of the mods I have but not others, it seems inconsistent with which mods it flags missing item group pages for. I've not experienced this issue with other versions prior to 1.21.
Running Fabric 0.15.11 for 1.21 with EMI 1.1.7 for 1.21

**Comment by emilyploszaj** [comment]
I believe this was fixed in 1.1.8
