### ISSUE TITLE
Fluid EmiStacks lose their component changes when converting into FluidVariant

### ISSUE THREAD

**Issue by Sollace** [emilyploszaj/emi#582]
I was trying to figure out why all of the fluids displayed in EMI were using their base colour for all their variants.

It appears the problem is due to this:
https://github.com/emilyploszaj/emi/blob/615d816a81de7627292934c1c3d99b4b6931cfd1/xplat/src/main/java/dev/emi/emi/api/stack/FluidEmiStack.java#L59

**Comment by emilyploszaj** [comment]
This was fixed in 1.1.8
