### ISSUE TITLE
EMI experienced a critical exception while reloading, check log

### ISSUE THREAD

**Issue by DragonlordRozza** [emilyploszaj/emi#585]
[EMI reloading error.txt](https://github.com/user-attachments/files/15945117/EMI.reloading.error.txt)
 
I start up the game and enter a world. When the world finishes loading, I open the inventory screen and see "EMI experienced a critical exception while reloading, check log" in the bottom corner after a minute of loading. JEI never appears, just the error message. is sadly not the same as issue #555.

**Comment by emilyploszaj** [comment]
This is a crash in EMI Trades, I believe they've fixed it
