### ISSUE TITLE
Crash rendering screen (1.20.1)

### ISSUE THREAD

**Issue by lolpowerluke** [emilyploszaj/emi#591]
crash log: https://bytebin.lucko.me/CRZTcLQbyO
emi and jei get blamed, if the issue lies with jei, I'll move the issue there

what I did prior to the crash:
joined multiplayer world
opened recipe for netherite upgrade
hover "+" icon for adding it in the crafting grid (idk if important, but this is to add it to the sophisticated backpack crafting interface)
crash

versions:
emi 1.1.7
jei 15.3.0.8
forge 47.2.17

**Comment by emilyploszaj** [comment]
This is a crash in the mod destroy's mixins to JEI.
