### ISSUE TITLE
Cannot enter world twice for each game launcher

### ISSUE THREAD

**Issue by Nejtherry** [emilyploszaj/emi#592]
Game version: 1.20.4
NeoForge 20.4.237
Mod version: 1.1.7

When the game first launched you can create and enter world, but after you quit world and want to enter again you cannot and showing this message.

![image](https://github.com/emilyploszaj/emi/assets/150878519/6ec116dc-062f-4c57-aef3-0b5e011d7cfc)
[debug.log](https://github.com/user-attachments/files/15993345/debug.log)
[latest.log](https://github.com/user-attachments/files/15993346/latest.log)

**Comment by emilyploszaj** [comment]
This seems unrelated to EMI
