### ISSUE TITLE
[1.20.1 Forge] When fetching certain recipes from JEI (such as create cutting recipes), the amount required isn't shown and neither is the amount produced

### ISSUE THREAD

**Issue by DakotaPride** [emilyploszaj/emi#597]
Example 1: Recipe that produces 6 planks doesn't show 6 planks as the result
![Screenshot 2024-06-29 120746](https://github.com/emilyploszaj/emi/assets/82760983/ef4f19d5-8a24-4a5f-80e8-2fb81335d7c3)
![image](https://github.com/emilyploszaj/emi/assets/82760983/820c25ed-eb4a-451a-8a0d-46c69b823424)
Example 2: Recipe that requires 250mb of Lava only shows that it requires 1mb
![image](https://github.com/emilyploszaj/emi/assets/82760983/54f9a3b4-1de1-4f19-82b0-b9b2bfb1fea5)
![image](https://github.com/emilyploszaj/emi/assets/82760983/719c9b20-d32b-41f5-9458-341a8cb3e3ee)

**Comment by java-jambalaya** [comment]
Can confirm, is replicable with just EMI (1.1.8+1.20.1+forge), JEI (15.3.0.8), and Create (1.20.1-0.5.1f).
Looks to have been brought about by EMI 1.1.8 as 1.1.7 seems to be free of this bug.

**Comment by emilyploszaj** [comment]
This is an error with specifically 1.1.8 and will be fixed shortly

**Comment by emilyploszaj** [comment]
Fixed in 1.1.9
