### ISSUE TITLE
Mouse buttons don't work for moving items from creative inventories to your hotbar

### ISSUE THREAD

**Issue by ShadowTech99001** [emilyploszaj/emi#598]
Steps to reproduce:
1. Change any hotbar slot keybind to a mouse button such as mouse button 4
2. Go into any creative tab
3. Use the mouse button which would normally put the item you are hovering over into the hotbar slot that you set the mouse button to.
4. Nothing happens

This bug does not happen with just JEI installed, it starts with EMI added

Please ask if you have any questions

I am using the side buttons of the Logitech G Pro X Superlight Wireless, although I don't think it matters

Edit: All custom mouse button keybinds don't work in the inventory, not just from creative menus.

**Comment by emilyploszaj** [comment]
This behavior was adjusted in 1.1.9 and should no longer conflict

**Comment by ShadowTech99001** [comment]
Perfect thank you very much
