### ISSUE TITLE
[1.1.8 for 1.21 Fabric] "Exception serializing stack" spam when hovering over enchanted item in anvil repair recipe

### ISSUE THREAD

**Issue by pajicadvance** [emilyploszaj/emi#599]
1. Open up EMI
2. Bring up usages for any enchantable item (eg. axe, sword)
3. Go to Anvil Repairing tab
4. Find any recipe that results in an enchanted item (eg. sword + smite 1 book = enchanted sword)
5. Hover over enchanted item with the mouse cursor
6. Observe continuous error spam in the log

https://mclo.gs/qmPh7ci

**Comment by emilyploszaj** [comment]
@embeddedt this is similar to the other issue I pinged you about, is this the serializer you wrote not having access to dynamic registries?
