### ISSUE TITLE
On Reload Opening Fullscreen Map Defaults to Spawn

### ISSUE THREAD

**Issue by digitaltrucker** [emilyploszaj/emi#60]
When opening the fullscreen map after loading an existing single player world the map is centered on spawn instead of player's position.

**Comment by emilyploszaj** [comment]
Do you have the right mod? EMI doesn't have any maps of the world.

**Comment by digitaltrucker** [comment]
Pardon me, a minor and temporary case of cerebral flatulence.  I was intending to take this issue to Journeymap.

EMI works fantastic, btw!
