### ISSUE TITLE
Items can be deleted even with no cheats enabled

### ISSUE THREAD

**Issue by PeglinX** [emilyploszaj/emi#601]
EMI: 1.1.8-1.20.1-Forge

Even without cheats enabled items say they can be deleted. If you click to delete them they will become invisible but won’t actually disappear. Upon reopening the inventory UI they become visible again. In case you inventory is full the item will drop immediately. 

Ultimately the issue is visual and can be misleading as the UI lies about deleting the items

Expected:    The legend should not appear without cheat mode and drop the items instead of causing them to become invisible

**Comment by emilyploszaj** [comment]
I can't reproduce this with just EMI, the delete stack tooltip doesn't appear unless cheat mode is on, and stacks don't get deleted when clicking. Can you reproduce this in a minimal environment and provide more info, like a video or log of the behavior you're describing?

**Comment by PeglinX** [comment]
I’ll try to later as i’m unable to now. Thanks
