### ISSUE TITLE
Crash when Opening Creative Inventory - "Item group has no page"

### ISSUE THREAD

**Issue by KxttyKxt** [emilyploszaj/emi#602]
| | |
| --- | --- |
| Minecraft Version: | 1.21 |
| Fabric Loader Version: | 0.15.11 |
| Fabric API Version: | 0.100.4+1.21 |
| EMI Version: | 1.18+1.21+fabric |

I am using a version of Fabulously Optimized (version 6.0.0 beta) with some added client mods of my choice. A zip for the `.mrpack` is available [here](https://www.dropbox.com/scl/fi/h0fxplqs0snsismpfkqe2/KxttyKxt.mrpack?rlkey=s16u38ywfo4a0nqt148ut5mre&st=5dox38ko&dl=0) in my DropBox.

I am not quite sure when the crash began happening. I have no mods running that add contents, so all of the creative tabs were vanilla.
Whenever I went to open the creative inventory, the game would instantly crash. I have pasted the crash log [here](https://gist.github.com/KxttyKxt/8bb907ca548f2cd987b6665eb79db512).
Speaking of the crash, it is worth noting that EMI was not ever in the stacktrace. I discovered EMI was the culprit by going down the list of mixins involved, eventually leading to disabling EMI, which stopped the crash. I apologize for not having more information.

It is worth noting that this crash first appeared as I was playing with a controller via Controlify, a mod in Fabulously Optimized. This mod *did* show up in the stacktrace, but the crash persisted with it disabled; its presence was likely due to me using a controller button to open the inventory. You can find an "issue" report about that below after I mention this issue.

Thanks for all your work. This really is a wonderful mod.

**Comment by emilyploszaj** [comment]
This looks like a bug in fabric api, I'm unclear what assumptions they are making and how I can work around them, but this needs to be reported to the fapi repo and I can reopen this if they have reasonable resolution suggestions.
