### ISSUE TITLE
Some items are listed twice

### ISSUE THREAD

**Issue by Partonetrain** [emilyploszaj/emi#603]
![image](https://github.com/emilyploszaj/emi/assets/19861808/af894e58-a659-4004-a0ab-b6b2a0f4aaae)

(image by Ernand on VMcord, but I am having the same issue)

**Comment by ffuentesm** [comment]
It also varies by mod load order. 
So in different profiles, it will be a different mod that gets duplicated at the end of the list. In this case was Easy Villagers and Easy Piglings, but sometimes is Occultism.

**Comment by emilyploszaj** [comment]
EMI will not allow strict duplicates, so these "duplicates" are varying by nbt/components, and are present in the creative tabs. I'm unclear on what mod is causing this, but it doesn't seem like something EMI can resolve

**Comment by ffuentesm** [comment]
Strange since when I checked Creative Tab, there were no duplicates of said items.

**Comment by Partonetrain** [comment]
I had the same issue in latest EMI and backdating fixed it.

**Comment by Boshigiri** [comment]
same issue

the traveler backpack will show twice in index, i submitted this issue to traveler backpack but no solution

version: emi-1.1.18+1.21.1+neoforge
travelersbackpack-neoforge-1.21.1-10.1.6

Tiviacz1337/Travelers-Backpack#1088

**Comment by embeddedt** [comment]
I think this will be properly fixed by the same change as https://github.com/emilyploszaj/emi/pull/813; while testing that, I did notice that without the fix I could get duplicate items sometimes.

**Comment by ffuentesm** [comment]
currently I am getting duplicates on Silent's Gear, where the Tool/armor list gets duplicated. 
![image](https://github.com/user-attachments/assets/3c7dd265-8313-466a-bbc6-60b5ab6d19fb)
![image](https://github.com/user-attachments/assets/435b0b6b-4031-4920-a00b-d5e4849eab6c)
