### ISSUE TITLE
EMI not working with datapack recipes.

### ISSUE THREAD

**Issue by Mostovm** [emilyploszaj/emi#604]
Fabric [1.21]

I looked around in your configs and all. Minecraft registers the recipes but this mod doesn't please fix this 🙏. I do like the customization this offers and the other loot tables and such but this issue doesn't add up

The recipe shows AFTER obtaining the items not anytime your indexing for the registered item.

**Comment by Bluberry-Kat** [comment]
EMI does support datapack recipes because all recipes are datapack recipes.  
Please give more information about your environment (modlist, enabled datapacks, server environment, anything more than what you've provided which is literally nothing) so we can help figure out the actual bug and fix it.

**Comment by Mostovm** [comment]
I thought the client side didn't need the datapack downloaded just now seen the folder
I put all of the content into my datapack folder and still isn't registering only when I have the acquired items to craft the item. Despite disabling all mods and only having EMI enabled it still doesn't work. I even tested in singleplayer.
I thought the issue was fixed but I realized it was just showing the ammo because I had the items. I have datapack on both server and client, I even triple checked their status they are working recipes are registered by minecraft not EMI.

Could you happen to have an idea of the problem so I could look into it ?

[FABRIC 1.21]
Backslot Addon Globox
CameraOverhaul
CC API
Chunky
Cloth API
Collective
Distant Horizons
Do a Barrel Roll
EMI
Explorers compass
FabricAPI
FerriteCore
GLitchCore
Guard Villagers
Indium
Iris Shaders
Lios Overhaul Villages
Lithium
Mod Menu
Physics MOd
Shulker Box Tooltip
SIMPLE VC
SOdium
Travelers Backpacks
Tree Harvester
Village SPawnPOint
Xareos World Map
YAConfig
EMF
ETF

These had no effect as I only enabled EMI and still didnt work in multi and single. Same way for JEI. I unlocked all recipes and crafted them too still didn't make a difference.

**Comment by Mostovm** [comment]
Base item of a recipe im looking at is the firework star and when I click on it, EMI does show the recipe in its pages but it doesnt show it seperately in the index as its own respective item.

Another base item is the disc_fragment having 17 recipes for the same item but it doesnt respect the item individualy.
![image](https://github.com/emilyploszaj/emi/assets/147961246/722e52ac-b2f4-4b83-96cc-ae3f9be8dd17)

Is there a config setting im missing to fix this? I think the items should be seperated based on difference of components basically same way of how can't stack same items together in mc despite having same id just diff data.

The datapack introduces items that are meant to be different from its base item is the issue here. It did register not the way it should be meant to it looks like

**Comment by fzzyhmstrs** [comment]
There are 29.6 *quintillion* possible firework stars. So, not feasible to display separately "by component".

The music disc thing I'm really not sure what you are showing. Normally there is one recipe for disc fragment 5: 9 fragments = 1 music disc 5. You have a datapack which is adding custom recipes for music discs?

**Comment by Mostovm** [comment]
I have a datapack adding in new recipes for new items by altering the base items. Not much wiggle room with adding in new items from datapacks as far as I know, you have to alter existing base items if you want a new item introduced.

Maybe not seperate every item by each component but the components that should seperate items by is their custom_model_data or custom_data as its the main differential in many datapacks using textures for their items. Better yet just their group tag in minecrafts recipe.json file similiarly shown in the vanilla recipe book

The item shown is supposed to be a total new item called "fragment piece" altered from a disc_fragment_5 but as they aren't seperated they are categorized as an alternative recipe for the base item

**Comment by emilyploszaj** [comment]
There is no reliable way to be able to detect when items should be considered separate for datapacks like this, there are too many situations where it'll disconnect items that *should* be the same thing, like a renamed item for example. Custom model data is a decent heuristic but it still will run into cases where people are using it unlike you are. This is not really resolveable without a plugin.

**Comment by Mostovm** [comment]
How about the recipe grouping in their json files? wouldnt that be something to consider when seperating items as such
It works fine in vanilla with it being seperate, im wondering if that recipe grouping could be the method.

In JEI when turning off the menu the vanilla recipe menu loads the items just fine im thinking a method similiar to what mojang already has or its not possible with how your mod is?
