### ISSUE TITLE
[Bug] [1.21] [Neoforge] High Rate Log Spam of "TODO implement JEMI support for fluids again"

### ISSUE THREAD

**Issue by SirWoofie** [emilyploszaj/emi#607]
There appears to be a TODO item that's been left in the code. It fills the log at a worryingly high speed, leading to the logs becoming useless once in-game. Log viewers that display while the game is open will then cause a noticeable performance impact or fail to even display the log due to this error.

This is what shows in the log, constantly:
[02Jul2024 16:54:43.938] [Thread-20/ERROR] [EMI/]: [EMI] TODO implement JEMI support for fluids again

You can find it in the logs posted here with limited context:
https://github.com/emilyploszaj/emi/issues/577#issue-2360408485

**Comment by emilyploszaj** [comment]
Arch loom finally updated so I was only able to get to this today, resolved in 1.1.9
