### ISSUE TITLE
[1.21] Struggling with Recipes for Iron Bookshelves Mod and Bronze Mod

### ISSUE THREAD

**Issue by makumaku1974** [emilyploszaj/emi#608]
Bronze Bookshelf requires bronze from 2 mods

*Ingotcraft
*Bronze

The problem is that the recipe is not integrated with Bronze mod, only Ingotcraft. Hence, game breaking inconsistency.

**Comment by emilyploszaj** [comment]
This does not seem to be a bug? What is the incorrect behavior? I will close the issue unless there is an actual bug.
