### ISSUE TITLE
[1.19.2 Forge] 1.1.9 breaks Tinkers Construct melting and casting recipes

### ISSUE THREAD

**Issue by NyanMC** [emilyploszaj/emi#609]
The most recent version of EMI on 1.19.2 causes all fluid stacks in Tinkers Construct recipes to be displayed as 1mb, regardless of their actual value. This may also be the case with other mods, but I did not test this. Downgrading to 1.1.7 fixes this issue.

Image of the faulty behavior in 1.1.9:
![image](https://github.com/emilyploszaj/emi/assets/44331238/77ce7e6d-2a65-4961-a34a-8d52b32d0a40)

After downgrading to 1.1.7:
![image](https://github.com/emilyploszaj/emi/assets/44331238/767ac153-bd05-4395-a4d4-5bf80d1c9f7f)

Reproduced with an instance containing the following four mods:

EMI version 1.1.9+1.19.2+forge
JEI version 11.6.0.1020
[Mantle](https://modrinth.com/mod/mantle) version 1.10.36
[Tinkers' Construct](https://modrinth.com/mod/tinkers-construct) version 3.8.3.39

**Comment by emilyploszaj** [comment]
Can you drop a 1.1.9 log?

**Comment by NyanMC** [comment]
https://mclo.gs/vLfb9H8

**Comment by emilyploszaj** [comment]
Properly fixed in 1.1.10
