### ISSUE TITLE
[1.20.1 (Neo)Forge] EMI 1.1.9 + JEI + Mek process dont get right material

### ISSUE THREAD

**Issue by fuyn101** [emilyploszaj/emi#610]
NeoForge:47.1.106
EMI:1.19+1.20.1 from curseforge
JEI:15.3.0.8
Mek:10.4.8

i got :
![image](https://github.com/emilyploszaj/emi/assets/151902446/c956b613-2278-4fe1-ba07-c5be50236128)

it should:
![image](https://github.com/emilyploszaj/emi/assets/151902446/93eff77e-ac4a-47f9-94b7-8e7a62c5393c)

This also shows up in mek other recipes, basically all of them have the wrong numbers:

is 1 raw gold → 1gold shade
should 3 rwa gold → 8 gold shade
![image](https://github.com/emilyploszaj/emi/assets/151902446/365b99c2-a861-4bec-8868-f986046da519)

just like https://github.com/emilyploszaj/emi/issues/597 but in EMI1.1.9

**Comment by emilyploszaj** [comment]
Should be resolved in 1.1.10, made a mistake in my 1.1.9 fix
