### ISSUE TITLE
[Bug, Forge] Farmer's Delight cooking pot craftables never shows anything

### ISSUE THREAD

**Issue by Roadhog360** [emilyploszaj/emi#618]
# Info
EMI 1.1.8
JEI 15.3.0.8
Farmer's Delight 1.2.4
Forge 47.3.4

# The bug
Here we can see EMI's "craftables" mode never shows anything. A valid recipe is present. I have 3 beetroots and even the bowl, so it should be showing the beetroot stew recipe.
![Screenshot_20240706_002931](https://github.com/emilyploszaj/emi/assets/11903511/d3deee8b-8691-41ff-b314-8e3c991ac7df)

Farmer's Delight works with the stock recipe book in the same instance. Heck, I don't even need the bowl!
![Screenshot_20240706_003450](https://github.com/emilyploszaj/emi/assets/11903511/3e6aa90c-848f-47d3-98f6-0ab9e9de86e8)

**Comment by emilyploszaj** [comment]
Farmer's delight doesn't have dedicated EMI support, so it can't show craftables. The dev would need to add it

**Comment by Roadhog360** [comment]
> Farmer's delight doesn't have dedicated EMI support, so it can't show craftables. The dev would need to add it

Why can't EMI just show what the recipe book would? Why is dedicated support needed?

At the very least could there please be an option to fall back to the vanilla recipe book on the book button without disabling that as a whole, *only* not have the craftables option for unsupported recipe books? This is unclear to the player and I thought I was doing something wrong.

**Comment by emilyploszaj** [comment]
EMI's recipes do not correlate with the recipe book in a reasonable way to transfer information and cannot even trust the underlying system continues to exist, as mods remove it for performance reasons. You can use the config to adjust what the recipe book button does, you can switch to craftables manually and have the recipe book actually use the vanilla recipe book.

**Comment by Roadhog360** [comment]
But I like the new system. I don't want to turn it off by default because then most people won't use it because they won't see the tiny craftables button on the top of the screen.

One of the main reasons why I used this version. Back to JEI, I guess...

I know you can't trust the underlying system to exist, but it doesn't it hurt to at least *try* to grab its information? At worst, you still have nothing like in the picture.

In the meantime, I'm going to go ahead and make a feature request over on FD for support for this. But the point is, I feel like there's a better fallback than just displaying nothing. Like if no system is detected to then use the vanilla recipe book then and only then. This inconsistency makes it unclear to the player, so even if they choose to turn the EMI craftables over book button back on, it just isn't clear why it's not working and they may think they are doing something wrong, like I did at first.

**Comment by Roadhog360** [comment]
Continued @ https://github.com/vectorwing/FarmersDelight/discussions/930

**Comment by Roadhog360** [comment]
"EMI's recipes do not correlate with the recipe book"

To be honest, I still don't quite understand this or what exactly is preventing you from just taking the recipe book information by default.

**Comment by Kevin-Marsh** [comment]
You are incorrect. It would be a simple matter if it was a case of simply a craftable information. The display of custom categories such as the cooking pot isn't just a crafting recipe. It is an entirely new recipe category. This wouldn't even work in JEI except that farmers delight added custom support for it to be able to show up. This is the same with every single mod that adds recipes that aren't crafting table, smithing etc. Farmer's delight would have to add EMI support for this to ever show up.

**Comment by Roadhog360** [comment]
I really am having a hard time believing that.
