### ISSUE TITLE
EMI misunderstands cooking pot and cutting board

### ISSUE THREAD

**Issue by The-furf-of-July** [emilyploszaj/emi#622]
![image](https://github.com/emilyploszaj/emi/assets/20565740/49471b51-0626-40e8-851c-d5aca02a5a9d)
In the example above, only one leather substitute is created. However, due to how the station looks, EMI interprets this as making 2 of the item, and will only instruct the player to make half as many as they should for a crafting tree.

![image](https://github.com/emilyploszaj/emi/assets/20565740/796726da-9427-4586-9f1a-7f7f5c0350cf)

A smaller issue occurs with the cutting board that is nonetheless frustrating, where it takes the cutting tool used as if it were a consumed ingredient, and will thus instruct the player to make 6 axes to craft tree bark, for example. This can be ignored by the player but it would improve the system if it were to be corrected to interpret the input as reusable, or treat it as part of the crafting station. The same applies to Create: Central Kitchen
![image](https://github.com/emilyploszaj/emi/assets/20565740/4491a861-4d97-46c1-8e99-816f00c7bd1d)

**Comment by emilyploszaj** [comment]
EMI can support chance and visual only ingredients, but Farmer's Delight does not specify them. It would needed dedicated EMI integration instead of only JEI integration, and the dev has not implemented it.

**Comment by The-furf-of-July** [comment]
I'm guessing something similar applies to Create's sequenced recipes not accounting for how many times the sequence needs to be repeeated?

Also, is there some client side workaround or edit method so I can have it calculate correctly in the meantime?

**Comment by emilyploszaj** [comment]
No, the mods need to add first party integration.
