### ISSUE TITLE
[1.1.10+1.21+fabric] Incompatible with Better Statistics Screen

### ISSUE THREAD

**Issue by luciobortoletto** [emilyploszaj/emi#629]
### What happened?

Minecraft crashes when opening inventory on Quilt (I haven't tested on Fabric). This doesn't happen when only one of the 2 mods (Better Statistics Screen or Emi) is installed.

### Steps to reproduce

1. Enter in a world
2. Press E to open the inventory
3. Minecraft crashes.

### Relevant log output or crash report

Log: https://mclo.gs/pRFCsFM
Crash report: https://mclo.gs/CZVRfwI

### Other installed mods

- Better Statistics Screen 3.12.3+fabric-1.21
- EMI 1.1.10+1.21+fabric
- Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL) 11.0.0-alpha.3+0.100.7-1.21
- TCDCommons API 3.12.1+fabric-1.21  
  
I also opened the issue on Better Statistics Screen's repository: https://github.com/TheCSMods/mc-better-stats/issues/133

**Comment by emilyploszaj** [comment]
This item group concurrency issue should be resolved in 1.1.11
