### ISSUE TITLE
[Feature Request] configurable recipe viewer size

### ISSUE THREAD

**Issue by AmberGoop** [emilyploszaj/emi#63]
i'd like to be able to set the recipe viewer size to a consistent size from which it won't change - current behaviour is that it grows for recipes that are too big, but shrinks back down for recipes that aren't. i'd like to be able to make it more consistent across all recipes big and small, so the window size doesn't change.
i hope this is reasonable!

**Comment by emilyploszaj** [comment]
An implementation note: this will likely take the form of selecting width based on max width in all tabs, instead of the current behavior, which is just the current tab.

**Comment by emilyploszaj** [comment]
You can set the minimum recipe screen width in 0.6.0 to your desired size now
