### ISSUE TITLE
1.20.1 EMI Error

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#632]
Forge 47.3.5

emi-1.1.10+1.20.1+forge.jar
jei-1.20.1-forge-15.8.0.13.jar

Sometimes EMI crashes, but I don't really understand what the error is related to.

![image](https://github.com/user-attachments/assets/6fd6b2a3-5b70-4313-8644-327defb57789)
Although in general it works.

> 
> [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] Exception thrown when reloading subtype comparison step in JEMI plugin
> --
> 19983 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.ItemStack (net.minecraft.world.item.AirItem and net.minecraft.world.item.ItemStack are in module minecraft@1.20.1 of loader 'TRANSFORMER' @256aabbe)
> 19984 | at TRANSFORMER
> 19985 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 19986 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] mezz.jei.api.constants.VanillaTypes$1.getBase(VanillaTypes.java:16)
> 19987 | at TRANSFORMER
> 19988 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 19989 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] mezz.jei.library.ingredients.subtypes.SubtypeInterpreters.contains(SubtypeInterpreters.java:39)
> 19990 | at TRANSFORMER
> 19991 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 19992 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$registerItemSubtypes$1(JemiPlugin.java:99)
> 19993 | at TRANSFORMER
> 19994 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 19995 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:378)
> 19996 | at TRANSFORMER
> 19997 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 19998 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$register$6(JemiPlugin.java:199)
> 19999 | at TRANSFORMER
> 20000 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 20001 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.safely(JemiPlugin.java:432)
> 20002 | at TRANSFORMER
> 20003 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 20004 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:199)
> 20005 | at TRANSFORMER
> 20006 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 20007 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
> 20008 | at java.base
> 20009 | [05:50:33] [Thread-642/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Unknown Source)
> 
> 
> </body>
> </html>

**Comment by Krimatoria** [comment]
> 
> [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] Exception thrown when reloading subtype comparison step in JEMI plugin
> --
> 4216 | java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.ItemStack (net.minecraft.world.item.AirItem and net.minecraft.world.item.ItemStack are in module minecraft@1.20.1 of loader 'TRANSFORMER' @474619d9)
> 4217 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.api.constants.VanillaTypes$1.getBase(VanillaTypes.java:16)
> 4218 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.ingredients.subtypes.SubtypeInterpreters.contains(SubtypeInterpreters.java:39)
> 4219 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.lambda$registerItemSubtypes$1(JemiPlugin.java:99)
> 4220 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:378)
> 4221 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.lambda$register$6(JemiPlugin.java:199)
> 4222 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.safely(JemiPlugin.java:432)
> 4223 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:199)
> 4224 | at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
> 4225 | at java.base/java.lang.Thread.run(Unknown Source)
> 4226 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.ItemStack (net.minecraft.world.item.AirItem and net.minecraft.world.item.ItemStack are in module minecraft@1.20.1 of loader 'TRANSFORMER' @474619d9)
> 4227 | at TRANSFORMER
> 4228 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 4229 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] mezz.jei.api.constants.VanillaTypes$1.getBase(VanillaTypes.java:16)
> 4230 | at TRANSFORMER
> 4231 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 4232 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] mezz.jei.library.ingredients.subtypes.SubtypeInterpreters.contains(SubtypeInterpreters.java:39)
> 4233 | at TRANSFORMER
> 4234 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4235 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$registerItemSubtypes$1(JemiPlugin.java:99)
> 4236 | at TRANSFORMER
> 4237 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4238 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:378)
> 4239 | at TRANSFORMER
> 4240 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4241 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$register$6(JemiPlugin.java:199)
> 4242 | at TRANSFORMER
> 4243 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4244 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.safely(JemiPlugin.java:432)
> 4245 | at TRANSFORMER
> 4246 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4247 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:199)
> 4248 | at TRANSFORMER
> 4249 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] emi@1.1.10+1.20.1+forge
> 4250 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
> 4251 | at java.base
> 4252 | [02:13:52] [Thread-35/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Unknown Source)
>

**Comment by emilyploszaj** [comment]
These JEMI issues should be resolved in 1.1.11

**Comment by Krimatoria** [comment]
> These JEMI issues should be resolved in 1.1.11

Is JEMI a part of JEI? 
It's just that there is no separate JEMI mod 
Or am I confused)))

**Comment by emilyploszaj** [comment]
this is EMI's integration with JEI

**Comment by Krimatoria** [comment]
> These JEMI issues should be resolved in 1.1.11

Updated the version like the same error again @emilyploszaj 

> [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] Exception thrown when reloading subtype comparison step in JEMI plugin
> 16282 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.ItemStack (net.minecraft.world.item.AirItem and net.minecraft.world.item.ItemStack are in module minecraft@1.20.1 of loader 'TRANSFORMER' @37b0a724)
> 16283 | at TRANSFORMER
> 16284 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 16285 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] mezz.jei.api.constants.VanillaTypes$1.getBase(VanillaTypes.java:15)
> 16286 | at TRANSFORMER
> 16287 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] jei@**.**.**.**
> 16288 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] mezz.jei.library.ingredients.subtypes.SubtypeInterpreters.contains(SubtypeInterpreters.java:39)
> 16289 | at TRANSFORMER
> 16290 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16291 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$registerItemSubtypes$1(JemiPlugin.java:99)
> 16292 | at TRANSFORMER
> 16293 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16294 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:378)
> 16295 | at TRANSFORMER
> 16296 | java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.ItemStack (net.minecraft.world.item.AirItem and net.minecraft.world.item.ItemStack are in module minecraft@1.20.1 of loader 'TRANSFORMER' @37b0a724)
> 16297 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.api.constants.VanillaTypes$1.getBase(VanillaTypes.java:15)
> 16298 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.ingredients.subtypes.SubtypeInterpreters.contains(SubtypeInterpreters.java:39)
> 16299 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.lambda$registerItemSubtypes$1(JemiPlugin.java:99)
> 16300 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:378)
> 16301 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.lambda$register$6(JemiPlugin.java:199)
> 16302 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.safely(JemiPlugin.java:432)
> 16303 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:199)
> 16304 | at TRANSFORMER/emi@1.1.11+1.20.1+forge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
> 16305 | at java.base/java.lang.Thread.run(Unknown Source)
> 16306 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16307 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.lambda$register$6(JemiPlugin.java:199)
> 16308 | at TRANSFORMER
> 16309 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16310 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.safely(JemiPlugin.java:432)
> 16311 | at TRANSFORMER
> 16312 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16313 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:199)
> 16314 | at TRANSFORMER
> 16315 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] emi@1.1.11+1.20.1+forge
> 16316 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
> 16317 | at java.base
> 16318 | [16:44:23] [Thread-119/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Unknown Source)
> 16319
> 
> <br class="Apple-interchange-newline">
> </body>
> </html>
