### ISSUE TITLE
Applied Energistics 2 - Open Guide issue

### ISSUE THREAD

**Issue by CaptnLucid** [emilyploszaj/emi#636]
**Describe the bug**
When using JEI, AE2 has a function built in, connecting to addon mods as well, that allows you to view an in-game guide by holding "G", however with EMI, it stutters when holding G, not filling up the bar to trigger the guide.

**To Reproduce
Steps to reproduce the behavior:**

1. Open Inventory
2. Search up anything regarding AE2
3. Hold G on an item that has a tool tip listed with "Hold [G] to open guide"

**Comment by emilyploszaj** [comment]
This is an issue with ae2's functionality and should be reported with them instead.
