### ISSUE TITLE
Forge 1.20.1 constant reloads lagging game

### ISSUE THREAD

**Issue by HoodBlah** [emilyploszaj/emi#637]
For some reason, whenever a mod is added or removed from the pack emi will get stuck in a loop of reloading the game and freezing it with lag. the have chat will be spammed with "server reloading" "reloading".

The only fix I found is to remove emi, launch game and go into world, close game, and then enable emi and play.

(The log gets spammed so much that the debug log is over 118MB, although that is also because the reloads mess with DH.)

[latest.log](https://github.com/user-attachments/files/16325663/latest.log)
[debug.zip](https://github.com/user-attachments/files/16325667/debug.zip)

**Comment by HoodBlah** [comment]
[debugfilters.log](https://github.com/user-attachments/files/16325683/debugfilters.log)
Heres the debug log without the DH stuff. (had to use a script to clean up the file)

**Comment by emilyploszaj** [comment]
EMI cannot make the server reload, for some reason the server keeps reloading and sending EMI recipe and tag packets and is failing somewhere.

**Comment by HoodBlah** [comment]
Hmm, alright. I thought it was emi since the problem was fixed when I got rid of it and then added it back. Thx anyway

**Comment by Barerock** [comment]
It really seems like EMI is causing this. It _only_ occurs with EMI and not with anything else, ever, out of hundreds of mods. Using EMI seems to be the trigger.

**Comment by HoodBlah** [comment]
@Barerock I found out that if you open the player inventory and keep it open the problem will fix itself and the reload spam will stop after a bit. Of course, the problem will come back if you change the mods again.
