### ISSUE TITLE
Long recipe IDs push tooltip offscreen

### ISSUE THREAD

**Issue by Nataly171** [emilyploszaj/emi#64]
When show recipe IDs is enabled, any long ID will cause to tooltip to become very large, and no longer able to fit inside the screen, as shown in the screenshot. I can't propose a specific solution to this problem because I have no idea what would be a good solution haha.

Example:
![image](https://user-images.githubusercontent.com/109003930/184996597-3f418b67-3719-415d-acc7-96647b76bcb0.png)

**Comment by LemmaEOF** [comment]
the world if tooltip auto-wrapping was in vanilla

for now, see if [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix) helps

**Comment by emilyploszaj** [comment]
Fixed in 1.0.0
