### ISSUE TITLE
Current workstation does not support recipe

### ISSUE THREAD

**Issue by Honza572** [emilyploszaj/emi#640]
Soo I got this bug, I'll later try to figure out what mod caused it, but for now I'll at least send the Console log from Prism Launcher. At the beginning you can see what mods I have enabled, I am just messing with anything that looks interesting
https://mclo.gs/gci5UHJ

**Comment by emilyploszaj** [comment]
It is not clear what bug you are experiencing, if the current workstation does not support a recipe, it's just what it says on the tin.

**Comment by Honza572** [comment]
but...it does not support ANY recipe. not even vanilla ones

**Comment by emilyploszaj** [comment]
Can you provide screenshots and information? I have no information to use to debug here.

**Comment by Honza572** [comment]
sorry I just realized I was tired... I need the items and crafting table... I was expecting creative mode to take care of that, my bad
