### ISSUE TITLE
[Feature Request] Add support to synthetic favorite detects workbench with storages

### ISSUE THREAD

**Issue by jw910731** [emilyploszaj/emi#641]
The synthetic favorite currently only detects item stacks in player inventory, if an item is in Applied Energistics 2 or Refined Storage system (generally speaking, any crafting bench that includes a storage space), the synthetic favorite cannot detect whether the item exists or not, it informs player the ingredient is absent. This is inconvenient when crafting items with complex recipe.

I want EMI to be able to detect item in crafting workbench in an efficient way.
I think an API for third party mod maker to provide whether the required item is in the internal buffer of crafting bench might work?

P.S. Though I am not senior in writing Minecraft mod, I am willing to contribute to either EMI or AE2 for this feature.

**Comment by emilyploszaj** [comment]
This API exists, if mods are not exposing their inventories, it's for performance concerns or lack of integration.

**Comment by Geometer1729** [comment]
It looks like for AE2 they want more features in the API, specifically refreshing the list of craftables in order to make the performance better.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8074
