### ISSUE TITLE
Stuck when joining world due to "Search Items" item group throwing

### ISSUE THREAD

**Issue by DmitriBogdanov** [emilyploszaj/emi#642]
# Environment

| Variable | Value |
| - | - |
| Fabric | 0.15.11 for 1.20.1 |
| Mod version | 1.1.10, but happens with earlier versions too |
| Mod list | Large custom modpack (315 mods), see logs at line **19** for the full list |

# Issue

When joining world the game gets stuck at 'Joining world...', this happens *randomly in about 1 in 3 launches*.

# Logs

**Full log:** [emi_crash_log.log](https://github.com/user-attachments/files/16435435/emi_crash_log.log)

Whenever this happens logs stop at EMI after the "Baking Search" step and there is an error present:
```
[Thread-45/ERROR]: [EMI] Creative item group Search Items threw while EMI was attempting to construct the index, items may be missing.
[Thread-45/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
   <long stack trace>
   <EMI loading plugins>
   <EMI begins baking index>
[04:40:58] [Thread-45/INFO]: [EMI] Baked 43383 recipes in 551ms
[04:40:58] [Thread-45/INFO]: [EMI] Baking search
[04:40:59] [Thread-46/INFO]: [EMI] Baked recipes after reload in 494ms
   <logs stop here>
```
(the error can be found on line **2730** in the attached log)

# Notes

This only happens if EMI index source is set to `Creative` or `Creative + Registered`, it **doesn't** seem to happen when index source is `Registered`.

What I've tried so far and had no success:
- Trying different EMI versions
- Disabling EMI plugins
- Disabling JEI
- Disabling Not Enough Recipe Book, CraftTweaker, KubeJS

Doing binary search on mods proved quite challenging due to intertwined dependencies of mods + long launch times + random nature of the bug. While it's probably not an issue on EMI's side, it would be great to have a more educated guess on what could be causing that and if there is a workaround that doesn't involve disabling `Creative` index source (since without it items with custom NBT like potions and enchanting books only show up as a single base item).

**Comment by emilyploszaj** [comment]
Creative querying is now on thread in 1.1.11 and this should be resolved.
