### ISSUE TITLE
Indicator/Warning for when EMI+JEI aren't installed server-side

### ISSUE THREAD

**Issue by CodeF53** [emilyploszaj/emi#644]
I ran into an issue where I wasn't able to use `fill recipe` while in multiplayer for mods that require advanced integration, but could while in singleplayer.

In my case, it was [sophisticated backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks). Which threw a weird error every time I tried to use `fill recipe` server side.
```
Received invalid discriminator byte 14 on channel sophisticatedcore:channel
```

Anyways, I spent like 3 hours looking over this before realizing the server didn't have JEI so didn't know what the client was talking about.

**Comment by emilyploszaj** [comment]
If this is a JEI recipe fill handler, the onus is on JEI to detect this. EMI can generally handle being not installed on the server itself.
