### ISSUE TITLE
Show Recipe/Uses keybind issue

### ISSUE THREAD

**Issue by ExplosiveBunny** [emilyploszaj/emi#645]
Mouse buttons four and five do not work when attempting to query items within the inventory's recipes or uses.
(apologies if i have done this incorrectly...)

**Comment by emilyploszaj** [comment]
Sorry, poking at extra mouse buttons again seems to have broken it, should be resolved in 1.1.11, tested on a mouse I dug out of a box.

**Comment by ExplosiveBunny** [comment]
thank you!
