### ISSUE TITLE
1.21 crash when mod has clickable areas in jei plugin

### ISSUE THREAD

**Issue by JaisDK** [emilyploszaj/emi#647]
https://0x0.st/XOOT.txt

https://github.com/JDKDigital/productive-bees/blob/dev-1.21.0/src/main/java/cy/jdkdigital/productivebees/compat/jei/ProductiveBeesJeiPlugin.java#L316

**Comment by mezz** [comment]
Can you please include a full client log? Something may have broken the recipe category earlier and logged some errors.

**Comment by JaisDK** [comment]
[debug.log](https://github.com/user-attachments/files/16489103/debug.log)
[latest.log](https://github.com/user-attachments/files/16489106/latest.log)

**Comment by mezz** [comment]
Thanks for the extra info!
It looks like productive bees tried to optimize their JEI plugin when they added EMI support, so it skips a step:
https://github.com/JDKDigital/productive-bees/commit/5b05f03602c0ef479a2ddb88e0b0e9d60e6cc7d2#diff-3a7973f566b89a4b4d15b7c9a8493a403b40531493df9e246c1d94ec6b49694aL112-R117

Unfortunately this unintentionally breaks things, because the `BEE_INGREDIENT` is no longer registered and everything that depends on it later is crashing.
Please report this problem to productive bees and link back to this issue.

@emilyploszaj is there some deeper integration we can work on to support this kind of loading optimization in a way that works safely?

**Comment by JaisDK** [comment]
It's not an optimization, if I don't disable the ingredient registration for JEI when EMI I added I get double the ingredients showing up.

**Comment by emilyploszaj** [comment]
Really I should just be disabling clickable area registration full stop when EMI is present, JEI doesn't give any runtime handler control to it and EMI has no analog.

**Comment by JaisDK** [comment]
![image](https://github.com/user-attachments/assets/a140fcd8-1757-4658-9c48-3ed3bf839946)
this is with both plugins registering ingredients

I can now click the area but it will display recipes using JEI not EMI which looks fine but it's inconsistent from what you see when you interact with the bee ingredient in the ingredient list. Also the ingredient registered with JEI is not usable, it doesn't do anything if you looks up uses or recipes for it.

**Comment by JaisDK** [comment]
Disabling the clickable area would be the correct solution.

Is there a way to implement the same with EMI?

**Comment by JaisDK** [comment]
For now I can register an empty list of ingredients, it stops the crash and won't duplicate the ingredients. However it gives access to the underlying JEI plugin :shrug:

```
        if (!ModList.get().isLoaded("emi")) {
            Collection<BeeIngredient> ingredients = BeeIngredientFactory.getOrCreateList(true).values();
            registration.register(BEE_INGREDIENT, new ArrayList<>(ingredients), new BeeIngredientHelper(), new BeeIngredientRenderer());
        } else {
            registration.register(BEE_INGREDIENT, new ArrayList<>(), new BeeIngredientHelper(), new BeeIngredientRenderer());
        }
```

**Comment by mezz** [comment]
Looking at the log, unfortunately a lot more was breaking and crashing than just the clickable areas.
For now, registering an empty list of ingredients seems like the right solution.
I'd like to figure out if there's something better we can do here though.

**Comment by emilyploszaj** [comment]
JEI plugins for mods with dedicated EMI integration are now properly suppressed by EMI and this issue should no longer occur, broadly.
