### ISSUE TITLE
[issue] bad handling of fluid in tree recipe crafting mode

### ISSUE THREAD

**Issue by jonatjano** [emilyploszaj/emi#649]
# issue

When using EMI tree recipe crafting mode with fluid and looking into a machine with the requested fluid, it is not detected and EMI says that I can't craft any batch of the item

In the below screenshot using Modern Industrialisation to illustrate the issue, the recipe asks for 1mb of lubricant and the machine currently holds 3909mb of lubricant

![image](https://github.com/user-attachments/assets/cae56f55-91c6-4aa1-833f-9fe091d5c7df)

# expected behavior

I expect that the liquid in the machine is detected and that EMI tells me I can use it to craft the recipe

# version 

Neoforge : 21.0.148
EMI : 1.1.10+1.21+neoforge
Modern Industrialization : 2.2.16-beta

# additional information

I also opened an [issue on Modern Industrialization's github](https://github.com/AztechMC/Modern-Industrialization/issues/816), thinking their side had to allow EMI to read that slot and they told me the issue is EMI lacking an handling of fluid

**Comment by emilyploszaj** [comment]
MI is not exposing their input slots as part of their inventory, as is necessary for EMI to assume you have lubricant and assume this is craftable.

**Comment by Technici4n** [comment]
@emilyploszaj how am I supposed to expose fluid slots?

**Comment by jonatjano** [comment]
@emilyploszaj sorry to bother, but I'll allow myself to send you a ping so you know Technici4n is waiting for an answer

**Comment by emilyploszaj** [comment]
You need to override `getInventory` to expose your inputs inside the inventory. You can use a similar approach of collecting your slots and getting their contents and additionally add all fluid contents. @Technici4n

**Comment by Technici4n** [comment]
That does not actually work for `#craft`. `EmiRecipeFiller#getStacks` will try to find fluid ingredients in the input sources, and of course that will fail. Interestingly, `#canCraft` does however succeed. 😓

This is what I tried: https://github.com/AztechMC/Modern-Industrialization/commit/10a356a8b0e031e6ebd2ef1d6fb260a5d4c0030f.

**Comment by emilyploszaj** [comment]
Well, yeah, any complex (non-standard) recipe filling will require manual work, MI is going to need to handle moving items for crafts. I assumed you already had this since you handle + filling yourself.

**Comment by Technici4n** [comment]
Could EMI maybe move items only and ignore fluids? I'd prefer not to reimplement the whole thing myself 😅

**Comment by emilyploszaj** [comment]
It's very hard for EMI to know how to handle non-standard ingredients and what is desirable to a developer. I'll think about it but I really feel like non-standard use cases should be handled explicitly

**Comment by xxhertz** [comment]
sorry for the necropost but funny enough this is exactly the mod and block that made me google if there was a way to "ignore fluids" or to specify some parts of a recipe will *always* be fulfilled and to just ignore with EMI, and i think that would be a great solution overall because this isn't the only mod with this kind of trouble (see: chemicals via mekanism's metallurgic infuser)

i would submit my own pr/patch but i'm really unfamiliar w/ java and minecraft modding in general
