### ISSUE TITLE
Make miscraft prevention also work when you run out of ingredients

### ISSUE THREAD

**Issue by Nataly171** [emilyploszaj/emi#65]
Miscraft prevention is an incredibly useful feature, creating a "phantom item" under your cursor while crafting, so that as more or fewer recipes become available, the thing you're crafting doesn't get moved around while you're clicking a lot. However, if you run out of ingredients for that recipe, such that it is no longer craftable, the "phantom item" goes away, meaning you're now clicking whatever ends up behind it.

I suggest making it so that when the item you're crafting becomes uncraftable, the "phantom item" stays in place, highlighting in red the missing ingredients in the tooltip, just as the favorites work.

**Comment by emilyploszaj** [comment]
Lovely suggestion, never encountered this, I'll patch it up

**Comment by emilyploszaj** [comment]
![image](https://user-images.githubusercontent.com/14813658/185057709-835eea5e-2c09-469a-b0cc-3725354f06e0.png)

I can't seem to reproduce this, in my case I started with 2 sticks and 12 planks, crafted a sign twice, and the miscraft prevention continued showing up.

Are you crafting only a single batch? As it stands, miscraft prevention only occurs either if you craft something multiple times, or if you craft something and remain able to craft more. The rationale behind this is that it is likely desirable behavior to craft a lot of similar and nearby recipes. For instance, crafting botania flowers into petals quickly after growing a bunch, you probably just want to keep your cursor still and craft 16 recipes, one at a time.

**Comment by Nataly171** [comment]
You are correct, the miscraft prevention behaves as you described. I suppose my suggestion then, would be to have it show up when you can and do craft only one batch, but your botania scenario also makes sense. Sometimes, for example, I might have some iron nuggets from a shipwreck chest, and want to craft as many into ingots as I can, but I don't really pay attention to how many there are. In this example, let's say there are 16 nuggets, so only on ingot can be crafted. Then I think it would make sense to have the miscraft prevention show up when I craft the one ingot. Although, realistically, I'd probably just use the "craft entire stack" hotkey, I think the miscraft prevention would be worth considering.

Speaking of quick crafting entire stacks, I think if my idea is ever implemented, it should also apply to crafting entire stacks, since that operates on similar behavior. Perhaps later down the line, more customization could be added to the miscraft prevention feature in the config? But that might be something for an entirely different feature request.

**Comment by emilyploszaj** [comment]
Tweaked in 0.4.0, "craft 1" will always trigger miscraft prevention
