### ISSUE TITLE
Maven repository fails to add - unsure if on my end or not

### ISSUE THREAD

**Issue by DiamonDoughnut** [emilyploszaj/emi#650]
following the getting started guide for fabric, gradle fails to build claiming no existence of 
'dev.emi/emi-fabric/1.1.10+1.20.1+fabric"
same result with the api specification. When I remove the '+fabric' it loads, but launching the client throws an incompatible mods error, requesting the version with +fabric. unsure what's going on with this, maybe it's just on my end.

**Comment by emilyploszaj** [comment]
`+fabric` is not a real artifact, please use the one you were able to use in the past. It does not seem very likely to me that fabric loader would be telling you to use an artifact that does not exist.

**Comment by DiamonDoughnut** [comment]
ok i was thinking that might be the case, if I get the error again, i'll attach a sc.

**Comment by DiamonDoughnut** [comment]
ok yeah, thanks for the clarification, it was entirely on my end as I suspected :)
