### ISSUE TITLE
Hide slots that don't contain searched text - check for Slot#isActive

### ISSUE THREAD

**Issue by raoulvdberge** [emilyploszaj/emi#654]
Hello,
I'm hiding slots that are included within a scrollbar or hidden in a different page.
It seems like the "hide slots that don't contain searched text" functionality ignores `Slot#isActive`.

![image](https://github.com/user-attachments/assets/35570a90-42db-4f8a-9235-994c66f4bda4)

It doesn't make sense to render the highlight for non-interactable slots.

(NeoForge 1.21 - EMI 1.1.10+1.21)

**Comment by emilyploszaj** [comment]
Peculiar oversight, resolved in 1.1.11
