### ISSUE TITLE
[Feature Request] Ability to add favorites on the AE2 crafting plan

### ISSUE THREAD

**Issue by forteen14desu** [emilyploszaj/emi#657]
EMI is currently unable to use the cursor and A to save fav on this screen. with JEI installed still cant :(
![QQ20240809-091036](https://github.com/user-attachments/assets/d5ed3ced-19a3-4eb6-8558-fe07bd98fc14)
JEI it self
![QQ20240809-091222](https://github.com/user-attachments/assets/4eb7f2bf-fcb4-40b1-b9eb-70972e9d0b32)

**Comment by emilyploszaj** [comment]
This is a mod integration issue, not an EMI issue
