### ISSUE TITLE
[Feature Request] ability to view block recipes and add fav in the multi-block info

### ISSUE THREAD

**Issue by forteen14desu** [emilyploszaj/emi#658]
EMI is currently unable to click below blocks to view the recipe, or use R to view it. also cant add fav :(
![QQ20240809-091639](https://github.com/user-attachments/assets/15d33066-e577-4dec-831f-bedc1f11466a)
JEI
![QQ20240809-091310](https://github.com/user-attachments/assets/fbeca7ce-0e6d-45ad-8b8b-49ae99fecaaa)
![QQ20240809-091319](https://github.com/user-attachments/assets/2676f83a-ddc1-44d0-90bc-7dd7a7d386bd)

**Comment by emilyploszaj** [comment]
Please contact gregtech if their integration is not showing up properly, they use invasive coremods on libraries like EMI and I cannot really help debug because of it.

**Comment by screret** [comment]
I didn't manage to make the scrollbar work with EMI slots so I didn't.
