### ISSUE TITLE
Error rendering AE2 In-World Transformation recipes

### ISSUE THREAD

**Issue by JuiceyBeans** [emilyploszaj/emi#659]
Minecraft Version: 1.20.1
AE2 Version: 15.2.11
EMI Version: 1.1.10
JEI Version: 15.3.0.4

![image](https://github.com/user-attachments/assets/2be8ba53-60c2-456c-b66c-0834d65ba208)

**Comment by emilyploszaj** [comment]
Please report this to ae2.
