### ISSUE TITLE
[Bug][1.20.1][NeoForge] EMI version 1.1.11 does not display brewery block in Botania properly

### ISSUE THREAD

**Issue by PTALTS-LK** [emilyploszaj/emi#660]
Its use is obtained by pressing the "U" key on it

EMI 1.1.10:
![image](https://github.com/user-attachments/assets/c10c05d3-a0b1-44ab-b4af-734e693be4d6)
![image](https://github.com/user-attachments/assets/2412bd07-53e5-40b3-97ea-92b118785a68)
[latest.log](https://github.com/user-attachments/files/16568577/latest.log)
EMI 1.1.11:
![image](https://github.com/user-attachments/assets/706e07c4-50a2-4f66-b3b3-a4dd299398dc)
![image](https://github.com/user-attachments/assets/4bacb1be-79ec-4eb7-a92e-c7baf8e6560f)
[latest.log](https://github.com/user-attachments/files/16568584/latest.log)

**Comment by emilyploszaj** [comment]
This should be fixed in 1.1.12
