### ISSUE TITLE
After creating 2 tags with the same list of items, EMI will only show one of them when you view the recipe that contains them.

### ISSUE THREAD

**Issue by TheDreamsCreator** [emilyploszaj/emi#661]
### 1.Introduction

- Recently I've been experimenting with adding missing recipes to the ExtraDelight using Kubejs.
- However, when I added two tags missing from the recipe to mutton and mutton chops, I found that the EMI recipe showed only one of the tags. (1.#forge:mutton/ribs 2.#forge:goat/stew)
- It appears that one of the tags overrides the other's EMI recipe display.
![2024-08-10_23 31 34](https://github.com/user-attachments/assets/1e3c0933-d15c-4cf1-b8e8-06b9dc9edd63)
![2024-08-11_00 56 46](https://github.com/user-attachments/assets/4b853c30-5814-4c80-9ab5-26de9e3f047d)
![2024-08-11_00 56 37](https://github.com/user-attachments/assets/a40d0f6f-544d-4501-b51c-9ce6367f6095)

- After I removed one of the tags (forge:goat/stew), it was like this...

![2024-08-10_23 55 45](https://github.com/user-attachments/assets/04c7f1ce-112a-41f8-9707-2d0a8d24b946)
![2024-08-11_00 53 44](https://github.com/user-attachments/assets/54ad7a5c-7617-4aff-92b2-0ade951c7424)
![2024-08-11_00 27 52](https://github.com/user-attachments/assets/86839fb5-d53e-4617-874b-fc6381dfbe34)

- Perhaps because they contain the same list of items? O.o

**Comment by TheDreamsCreator** [comment]
By the way, Minecraft is version 1.19.2, Forge version 43.3.8, and EMI version 1.1.6+.

**Comment by emilyploszaj** [comment]
This is intentional, EMI cannot display the underlying tag because the network protocol erases it and only sends a list of items. EMI assumes a tag based on contents, and because having tags with identical contents are not distinguishable, it will pick one based on a handful of heuristics to use.
