### ISSUE TITLE
Recipe tree compatibility

### ISSUE THREAD

**Issue by Industrial15** [emilyploszaj/emi#664]
I will come to the example of refined storage with which the problem is actually observed. Let's say there is a component in the craft which has a lot of "painted versions" and also includes a normal version. In the recipe tree, and in the tooltip craft no "continuation" craft, it stops at the object which has several versions, I will attach a photo. Need a function to select 1 of the options to continue the recipe for crafting
![image](https://github.com/user-attachments/assets/3101e8ca-bca1-4ced-980f-eae99b3b1e83)
![image](https://github.com/user-attachments/assets/42e14773-dc72-494a-81e8-baba09b55a3c)

**Comment by emilyploszaj** [comment]
If you encounter this, you simply need to pick which of the tag you want to use, this is normal and how EMI functions.

**Comment by Industrial15** [comment]
> Если вы столкнулись с этим, вам просто нужно выбрать, какой тег вы хотите использовать, это нормально и соответствует принципу работы EMI.

Is it possible to get more information on how to do this?

**Comment by emilyploszaj** [comment]
Click on any item in the recipe tree you want to pick a recipe for.
