### ISSUE TITLE
Item help compatibility problem with RefinedStorage

### ISSUE THREAD

**Issue by Industrial15** [emilyploszaj/emi#665]
With normal chest-type storages everything happens fine, the items needed for crafting are highlighted. But in the case of terminal in refined storage it does not work for some reason
![image](https://github.com/user-attachments/assets/d4a039ac-bc38-4849-a988-d866d36e6bac)

**Comment by emilyploszaj** [comment]
EMI's item highlighting can only work with vanilla slots, and RS uses a custom solution, I'm not sure there's a resolution either party can make at the moment.
