### ISSUE TITLE
Visual bug with Gregtech modern multiblock visualisation

### ISSUE THREAD

**Issue by jaaaco-j** [emilyploszaj/emi#666]
(reposted from GTM's github, they said they cant fix this on their side)

First encountered in monifactory, but managed to replicate with just GTM installed
tested with latest 1.20.1 version of EMI and GTM as of now which is 1.1.12 and 1.3.1-build_950 respectively

### Expected Behavior

ingredients, possible components for given block and the multiblock controlers GUIs and the visualization not overlapping each other
![2024-08-12_22 04 29](https://github.com/user-attachments/assets/0c2756e9-0371-4a86-a0c8-a8e17f083870)
this is with JEI instead of EMI

### Actual Behavior

multiple GUIs are overlapping and the visualization is out of bounds
![2024-08-12_22 00 38](https://github.com/user-attachments/assets/e8c989af-2aa3-4219-be33-3dca966e5c29)

the case in monifactory is even worse since the ingredients decided to be entirely cut off by another GUI
![image](https://github.com/user-attachments/assets/31bcbbf0-cdbb-481e-af8d-f3fa697a6a16)

### Steps to Reproduce

1) Download Gregtech Modern CEu
2) Right click any multiblock controller in the recipe browser
3) Click on the "multiblock info" tab

**Comment by emilyploszaj** [comment]
This is caused by having a particularly small screen and gregtech not respecting the height provided by EMI. They could be designing their recipes responsively for it, though in general I don't think that's a hard requirement and it's somewhat reasonable to say "we don't support this screen size" is their conclusion.

**Comment by screret** [comment]
our (currently kind of sucky) GUI library sadly cannot *do that*.
