### ISSUE TITLE
There is no display of Spartan Weaponry Weaponry oil recipe (already installed jei)

### ISSUE THREAD

**Issue by fszsxcylcyl** [emilyploszaj/emi#667]
There is no display of Spartan Weaponry Weaponry oil recipe (already installed jei)

Uploading 2024-08-15 17-27-28.mp4…

**Comment by emilyploszaj** [comment]
Did you forget to upload a video?

**Comment by fszsxcylcyl** [comment]
Uploading 2024-08-15 17-27-28.mp4…

**Comment by fszsxcylcyl** [comment]
https://github.com/user-attachments/assets/d0124c54-7e4d-4241-982b-0bdf405995a8

**Comment by fszsxcylcyl** [comment]
The recipe for the brewing of weapon oil is not shown.

**Comment by fszsxcylcyl** [comment]
The recipe for the brewing of weapon oil is not shown.

**Comment by emilyploszaj** [comment]
This video is unplayable, but if this is about brewing recipes, this is a duplicate of #557
