### ISSUE TITLE
1.20.1 Stargate Item not Show Recipe

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#669]
EMI does not show recipes for creating items from the Stargate mod. I found only one recipe. Is this a stargate or EMI problem, JEI?

1. Minecraft 1.20.1 47.3.5
2. https://modrinth.com/mod/jsg 
3. emi-1.1.12+1.20.1+forge.jar
4. jsg-1.20.1-5.0.4.1-Beta.jar

![image](https://github.com/user-attachments/assets/ffb8fee2-a673-4996-89cc-bc2f75affa40)

**Comment by emilyploszaj** [comment]
The mod you linked does not appear to be open source so I can't investigate further. The response on the bug seems to imply this is intentional? You'll have to take it up with them.

**Comment by Krimatoria** [comment]
> The mod you linked does not appear to be open source so I can't investigate further. The response on the bug seems to imply this is intentional? You'll have to take it up with them.

I wrote to them on GitHub, they didn't respond. apparently this is how it should be.
