### ISSUE TITLE
{1.19.2} EMI Fill recipe does not accept Gregtech tools unless they are full durability

### ISSUE THREAD

**Issue by illythesilly** [emilyploszaj/emi#670]
When trying to craft a part that requires GT tools (bolts need a steel file for example), pressing fill recipe will put the steel rod required but the tool will not be placed in the crafting GUI unless it is full durability.

**Comment by AerYareli** [comment]
I know this is a bit of a band aid fix, but a third party mod called GregTechCEu Modern, fixes this issue and a bunch of others! <3

**Comment by RiaTheFae** [comment]
Heya! Are you by any chance using "Tom's Simple Storage Mod"? I've tested AE2 and Vanilla crafting guis and they work as intended, however Tom's STM does NOT work as intended and instead acts as you describe.

**Comment by emilyploszaj** [comment]
Yeah, as far as my testing goes, catalysts work correctly in EMI for standard recipe handlers, this would be something going wrong with an implementation.

**Comment by illythesilly** [comment]
It was indeed Tom's Simple Storage, thank you for the reply!
