### ISSUE TITLE
[Bug] 1.20.1 Create specific recipe's don't display with jeb_wool installed

### ISSUE THREAD

**Issue by JLUsr** [emilyploszaj/emi#671]
When the mod [jeb_ Wool](https://modrinth.com/mod/jeb_-wool) is installed alongside [Create](https://modrinth.com/mod/create-fabric) any create specific recipe's (those involving mechanical crafters/pressing/crushing etc.) won't display. There are no special logs or information relevant to the issue thus I have not included such files (there are rare launches when they will still work; but, the large majority of the time the game will refuse to display them).

**Comment by emilyploszaj** [comment]
This mod is not open source so I can't investigate why their plugins may be failing or their recipes inconsistent, I have to assume that it is on their and ask you to find resolution with them.
