### ISSUE TITLE
1.20.1 forge - The game crashed whilst rendering screen Error: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1

### ISSUE THREAD

**Issue by MindBrain27** [emilyploszaj/emi#673]
When hovering the mouse over any fluid the game will crash with "The game crashed whilst rendering screen
Error: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1".

I have both JEI and EMI installed with their newest versions, another culprit may be GTCEU Modern as I believe they alter most fluids tooltips. At first I thought it was GregTech fluids but it does happen with Lava and Water as well as all of GregTech fluids too.

With EMI disabled this no longer happens.

The modpack in question is Sky Greg.

A crash log can be given upon request.

**Comment by screret** [comment]
GT modern. Fixed issue.
