### ISSUE TITLE
1.21.1 render crash with Xycraft + Stellaris

### ISSUE THREAD

**Issue by Saereth** [emilyploszaj/emi#674]
I'm running 
mc: 1.21.1
Neoforge: 21.1.22
JEI: jei-1.21.1-neoforge-19.8.4.113
EMI: emi-1.1.11+1.21+neoforge
Stellaris: stellaris-1.21-neoforge-1.0.5
Xycraft: xycraft_core-0.7.45-all
xycraft_machines-0.7.45
xycraft_world-0.7.45

So what happens is when you search for oil in EMI the game crashes. If I remove stellaris it's fine but I dont have any other mods that add a liquid to know if its related to stellaris at all (I suspect not as we've had a similar crash searching for tritium with mekanism in the pack). Adding the xycraft mods along with EMi causes the crash to occur. Without Xycraft the crash doesnt occur and using JEI alone without EMI will cause the crash not to occur. 

Here is the crashlog, I'm really unsure which mod is at fault here so if I need to open this issue with one of the other developers let me know. Thank you!

https://mclo.gs/NlmXqzM

**Comment by Soaryn** [comment]
This is a Stellaris (and likely an Architectury) bug:
![image](https://github.com/user-attachments/assets/53a578f0-30a7-46d1-986c-fb5dbcabf2cd)
A fluid texture SHOULD be present as per the documentation. 

![image](https://github.com/user-attachments/assets/ca670fdc-0340-4c80-bad5-c0393e3bf8b5)

**Comment by emilyploszaj** [comment]
Thanks for looking into this Soaryn

**Comment by Soaryn** [comment]
No problem! :) I was mostly thinking "I don't think either XyCraft or Emi have an issue with each other at the moment, it just has some quirks in regards to needing JEI currently" (Waiting on Gander before reimplementing any integrations at least)
