### ISSUE TITLE
doesn't render icons in inventory

### ISSUE THREAD

**Issue by MehanikTMYT** [emilyploszaj/emi#677]
version: 1.1.12+1.20.6+neoforge. Description to bug: after open inventory only names of recipes avialable and after use 'ctrl + t' i can see icons.  JEI installed - jei-1.21.1-neoforge-19.12.0.134.jar

https://github.com/user-attachments/assets/23fdb37b-f2d3-42b3-a62e-c6461dd7b0bf

**Comment by MehanikTMYT** [comment]
or ctrl + y

**Comment by emilyploszaj** [comment]
This is related to some of the mods you have installed, please try toggling mods that affect performance, rendering, and guis, and figure out where the conflict is. I'm going to close the issue but will reopen it if you can find out what to look into.
