### ISSUE TITLE
Status effects overlap with creative mode tabs

### ISSUE THREAD

**Issue by peanutbutter144** [emilyploszaj/emi#68]
Using EMI 0.3.3+1.19 on Minecraft 1.19.2 with Quilt Loader 0.17.3 and QFAPI 4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2

![2022-08-18_17 22 07](https://user-images.githubusercontent.com/43531981/185446020-deeaf7d1-bd71-41b1-baa1-88120cb10eed.png)

**Comment by emilyploszaj** [comment]
Fixed in 0.3.4
