### ISSUE TITLE
1.20.1 The error is back in the new version

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#682]
emi-1.1.12+1.20.1+forge.jar

https://github.com/emilyploszaj/emi/issues/632
https://gist.github.com/Krimatoria/6456a737fa363726795ca66cd8a5c547

**Comment by Ar5chK3ks** [comment]
Not sure If this is related but I get the same Error:
 I am currently playing ATM9 in Version 0.3.2.
I recently updated ATM9 from 0.3.0 and am using some additional mods for graphical features. JEI is the Default recipe Viewer of the pack.
After the Update (JEI and ModernFix got updated in 0.3.2) EMI is throwing some Errors when joining my server and I found some interesting problems ...
If I lookup the uses for honeycombs (ex. uraninite combs) from productive bees, it shows me all recipes for comb blocks (over 140 Pages).
I also noticed that the recipes for the soul lanterns ist missing. And for some reason the "configurable_comb" and "configurable_honeycomb" are visible in EMI (with JEI installed) but Not in JEI (after removing EMI and Addons from my Client).
I can provide server and client logs if needed.

**Comment by Ar5chK3ks** [comment]
Probably related to #683.
Seems like newer versions of JEI causes this because of some incompatiblity

**Comment by Ar5chK3ks** [comment]
https://mclo.gs/SgXu4QU
Log when joining my server

**Comment by Krimatoria** [comment]
I wonder if it could be because I haven't updated JEI? I just stayed on the old version, since for the new update, JEI is needed at Forge 47.3.6. I'm using 47.3.0

**Comment by shigure32** [comment]
> Probably related to #683. Seems like newer versions of JEI causes this because of some incompatiblity

Yes. I have tested every recent JEI version for 1.20.1 and find out the update between `15.4.0.9` and `15.8.0.10` is to be blamed.
Here are screenshots of emi 1.1.12 with jei 15.4.0.9 and 15.8.0.10 
![bees_emi_1 1 12_jei_15 4 0 9_01](https://github.com/user-attachments/assets/670b9bec-7ff4-4f00-a194-1cf029226afd)
![bees_emi_1 1 12_jei_15 8 0 10_01](https://github.com/user-attachments/assets/9b909e85-8c15-47f3-9577-b333df58f6e0)

Also I found JEI doesn't have this configurable combs problem, so I guess they might just change something on the tag representation?

**Comment by Ar5chK3ks** [comment]
Furthermore, the recipes for the spawn eggs of the configurable bees are completely missing.
I also noticed that with JEI the configureable_comb and configurable_honeycomb are not displayed unless they have an NBT tag, but in EMI the two entries without any NBT tag are also displayed.

**Comment by Ar5chK3ks** [comment]
Not having this issues anymore in 1.1.13
