### ISSUE TITLE
Scrolling on a tab in Sophisticated Backpacks scrolls the EMI item list instead

### ISSUE THREAD

**Issue by minghinshi** [emilyploszaj/emi#685]
Version Information:

- Minecraft 1.20.1
- Neoforge 47.1.106
- EMI 1.1.12+1.20.1+forge
- Just Enough Items 15.17.0.74
- Sophisticated Backpacks 3.20.6.1064
- Sophisticated Core 0.6.25.632

Steps to Reproduce:
1. Get any backpack.
2. Upgrade it with the Experience Pump Upgrade.
3. Open the Experience Pump tab.
4. Scroll on the box that says "10 lvls". 
5. Bug: Item list in EMI scrolls instead.

Expected Behaviour:
When I have a Backpack with an Experience Pump Upgrade installed, I can change the "Level at which Pump Stops" by scrolling.

Actual Behaviour:
When only EMI is installed, the list of items covers the Experience Pump tab. 
So far, this is correct behaviour because Sophisticated Backpack only sends UI data to JEI. So, I install JEI as well.
![image](https://github.com/user-attachments/assets/7e919252-f83d-4c1e-9f74-285efe26418c)

With both EMI and JEI installed, the items no longer cover the tab.
But scrolling doesn't change the level, because it still scrolls the item list.

https://github.com/user-attachments/assets/62277da0-220c-4317-b344-52adef456c15

With only JEI installed, the scrolling works. This is why I think EMI instead of Sophisticated Backpacks is causing the bug.

https://github.com/user-attachments/assets/c8f6a148-7e7a-4619-a9da-5763473c0008

**Comment by emilyploszaj** [comment]
This should be fixed in 1.1.13

**Comment by minghinshi** [comment]
Can confirm, thank you!
