### ISSUE TITLE
(1.1.12+1.20.1+forge) Ex Deorum recipes are not showing

### ISSUE THREAD

**Issue by rcfox2** [emilyploszaj/emi#687]
Self-explained, video shows more detail. This is ATM9 To The Sky 1.1.1. Recipes do show in JEI, but restarting the game over and over to look at recipes is a painful process. 

Not sure if this will be helpful, but I found a page explaining how they manage recipes on their wiki: https://exdeorum.readthedocs.io/en/latest/datapack/

https://github.com/user-attachments/assets/30ea4cea-37a5-475e-9ba2-45138e64a184

**Comment by rcfox2** [comment]
For reference here is what the recipe I was looking for looks like in JEI
![2024-09-06_07 28 44](https://github.com/user-attachments/assets/e6614987-ff1e-41fd-8be7-2cb62dade55c)

**Comment by emilyploszaj** [comment]
Make sure JEI is installed alongside EMI. Besides that, EMI has recently resolved JEI compat issues in 1.1.13

**Comment by rcfox2** [comment]
Issue still persists on 1.1.13, yes I have JEI installed.

**Comment by emilyploszaj** [comment]
I've checked, this is an Ex Deorum issue, the implement partial EMI support disabling the JEI forwarding. Not a bug in EMI
