### ISSUE TITLE
Entering the map, I'm stuck and don't understand. Is it this mod

### ISSUE THREAD

**Issue by zc1108aaa** [emilyploszaj/emi#688]
![image](https://github.com/user-attachments/assets/63449c4d-6d93-4bc5-a74c-e5fe1b5ebd2f)
0
![image](https://github.com/user-attachments/assets/aed42544-b8bf-406b-b4a6-d3603aec16ce)
[latest.log](https://github.com/user-attachments/files/16918454/latest.log)

**Comment by emilyploszaj** [comment]
This map is unrelated to EMI. The error in your log is non-lethal.
