### ISSUE TITLE
[Feature Request] Ability to hide/move EMI/Recipe Tree buttons in the bottom left

### ISSUE THREAD

**Issue by swiffyjk** [emilyploszaj/emi#689]
Forgive me if this is already an option, but it would be great if you could hide the two buttons in the bottom left or align them to a different part of the screen. We can hide the Recipe Tree button per-item but not in the EMI menu itself. Thanks!

**Comment by jacklollz2** [comment]
Would love this too, I prefer minimal UI

**Comment by emilyploszaj** [comment]
No alignment options, but the config and recipe tree buttons now have 3 visibility options, including being always visible and never visible, as of 1.1.18. This will allow you to hide the buttons if you do not want them.
