### ISSUE TITLE
How to use EMI with IC2C mod?

### ISSUE THREAD

**Issue by neQwerty** [emilyploszaj/emi#693]
I am playing on my modpack on version 1.19.2 Forge which has Industrial Craft 2 Classic (IC2C) mod and EMI does not show the craft recipes in most of the blocks from this mod, but I want to use EMI because of the quick craft function and craft history. Can I make to have only these two functions of the mod and use JEI to view the crafts?

_(I apologize for my English and the structure of the text, this is the first time I use the Issues button and I used a translator)_

**Comment by emilyploszaj** [comment]
No. You can install both mods at the same time and have JEI give recipes to EMI.
