### ISSUE TITLE
1.20.1 IE EMi Conflict Recipe

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#694]
ImmersiveEngineering-1.20.1-10.1.0-171.jar
emi-1.1.13+1.20.1+forge.jar

> [12:13:43] [Thread-59/ERROR] [immersiveengineering/]: IRecipe#getRemainingItems was called with an inventory that does not match the recipe

**Comment by emilyploszaj** [comment]
This error is non-lethal, there's no way to work around it EMI's side.

**Comment by Krimatoria** [comment]
> This error is non-lethal, there's no way to work around it EMI's side.

And what does the error say, I don't quite understand?
