### ISSUE TITLE
ME Crafting terminal synthetic favourite (BOM) support

### ISSUE THREAD

**Issue by jeytee84** [emilyploszaj/emi#696]
Forge - 47.2.21
emi-1.1.12+1.20.1
[Monifactory-Beta 0.8.1](https://www.curseforge.com/minecraft/modpacks/monifactory)

I was wondering if there is a way to get the same EMI functionality in the crafting terminal as in the crafting station.

![2024-09-09_01-34-36_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/a226bb67-465d-4bd9-bedd-bbace0f97d4e)
(EMI finds the already crafted items in the crafting stations connected inventories)

![2024-09-09_01-31-29_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/6873f43f-2810-4223-a8fb-403facc1b692)
(EMI does not see the ME system's content)

The ME system is hooked up to the exact same two barrels via storage buses

[Found the mod fixing this issue](https://modrinth.com/mod/ae2-emi-crafting/changelog) in the latest update. only problem that it's for fabric only:
It seems like [a forge port is in the works](https://github.com/blocovermelho/ae2-emi-crafting/issues/5#issuecomment-2094964813), but I was wondering if there's any plans for official support

**Comment by emilyploszaj** [comment]
EMI supports this, AE2 does not

**Comment by Spongman** [comment]
bidirectional finger pointing continues. maybe we can stop the blame game and progress to an actual solution?

from https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8074:

> @shartte: I actually tried this at some point, the issue is that this killed performance, and EMI does currently not offer a way for us to "refresh" the list of craftables. I think the functionality you are refering to is using the known list of craftables in the background.
If we can't fill the craftables (and cannot refresh them), we sadly cannot actually offer the other functionality :-|

**Comment by emilyploszaj** [comment]
EMI's existing solution is having the recipe handler return an `EmiInventory` with stacks present. This is necessary for synthetic favorites to know if items are present, and EMI only refreshes craftables when the inventory changes. AE2 can maintain an instance of this and only construct a new one when they receive updates (off thread, even), and EMI will handle the rest. If the raw craftable checking starts taking a performance hit past this optimization, EMI would have to look into supporting off thread craftable checking or incremental batched craftable checking on thread. If inventory construction itself, even with possible threading, is becoming a performance bottleneck, it would be necessary to approach a sort of mutable EMI inventory.

**Comment by theboo** [comment]
i think shartte may have been mixing up synthetic favorites and craftables there... Craftables would be insane to try to do with ae2 lol... i do not remember them ever attempting synthetics, i could be mistaken.. 

also i built a version for 1.21.1 neo against the open PR mentioned in that issue(https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/8215) and i have had no noticeable slowdown on my family enigmatica 10 server, and i am using it *heavily* because synthetic faves are so awesome lol... i do wish the craft all/one/to inventory EMI hotkeys worked within the ae2 terminals, but just having synthetics working makes manual crafting an absolute joy lol

**Comment by theboo** [comment]
looks like i mistook which issue was being referenced here... i assumed from the title of this issue and the similar message shartte sent there that it was referencing https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8214.. whoops
