### ISSUE TITLE
[1.20.1 Fabric] Boolean operators in search bar (similar to JEI/REI)

### ISSUE THREAD

**Issue by FoxySophie** [emilyploszaj/emi#697]
In JEI or REI it is possible to search for multiple entries using boolean operators & and | for AND and OR operations respectively. So you could do something like "log|plank" to search for all entries that match either "log" or "plank". This does not seem to be possible in EMI yet? Would be very nice to have, to look up multiple items in one search.

![image](https://github.com/user-attachments/assets/85f44746-5c8b-4c38-aa19-d512a8630a77)

**Comment by Abbie5** [comment]
simply add a space between the `|` and search terms like so
![2024-09-13_14 45 14](https://github.com/user-attachments/assets/ea88a431-720a-41ba-8de9-6ece11e7e601)

**Comment by FoxySophie** [comment]
Thank you!
