### ISSUE TITLE
Mark EMI as optional on server instead of unsupported

### ISSUE THREAD

**Issue by Einhornyordle** [emilyploszaj/emi#700]
Some addons like EMI Loot require EMI as dependency. On Modrinth, EMI seems to be marked as unsupported* since server installers like AT Launcher or the Docker Container for Minecraft Servers will not download EMI when installing  a modpack which causes the servers to crash during startup due to missing dependencies (see https://github.com/fzzyhmstrs/EMI_loot/issues/81 ).

While EMI doesn't provide anything if installed on server side (afaik) it doesn't seem to hurt either so making it optional instead of unsupported should fix this issue for all addons.

*Sadly it's no longer possible to see directly if a mod is set to required, optional or unsupported on client/server side so I can only assume that this is the case.

**Comment by fzzyhmstrs** [comment]
Following you over from my issue. Just FYI EMI technically does add some minor functionality on the server. It makes recipe transferring "smoother" (at least, there might be more I'm not aware of).

Also there may be something Modrinth-sided going on? EMI shows as supported on both server and client in the version window:
![image](https://github.com/user-attachments/assets/30614e8d-2bc1-43d2-8427-408f946ad3ed)

**Comment by emilyploszaj** [comment]
I changed this earlier today, modrinth keeps resetting my selection for some reason. Resolved for now at least
