### ISSUE TITLE
crash with neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [emilyploszaj/emi#701]
https://mclo.gs/Pqjyi5O

**Comment by emilyploszaj** [comment]
This is EMI crashing after the rest of your game crashed, you'll have to look deeper at the log.

**Comment by VaporeonScripts** [comment]
ur right, i found out the reason, the crash was caused by "FancyChicken" mob from earth2java mod, i disabled the spawn for it in the config and removed the mod then joined the world, then readded, now works fine.
