### ISSUE TITLE
[Crossmod] [Fabric] Replace `MouseMixin` with `ScreenMouseEvents` 

### ISSUE THREAD

**Issue by Phoupraw** [emilyploszaj/emi#703]
`ScreenMouseEvents` are events which allow modders to adjust the order of listeners, making addons more robust.

(I am writing a mod to capture hovered stack when ctrl + middle click, but it always fails until I found emi uses a dependent injector to cancel mouse input. Currently I `@WrapMethod` `EmiScreenManager#mouseClicked`. If emi changes to `ScreenMouseEvents`, I will use the event too and adjust the order.)

**Comment by emilyploszaj** [comment]
EMI can't use these events, they're too late and are bypassed by some mods. EMI needs to work on 100% of screens and there were too many issues in the past to revert, sorry.
