### ISSUE TITLE
Freeze when opening inventory for the first time

### ISSUE THREAD

**Issue by Oregano1963** [emilyploszaj/emi#704]
After entering a world, I get a freeze when first opening my inventory. This freeze doesn't happen when opening a chest--rather the following text is in the bottom left of the screen:
EMI searching
EMI reloading

Rather than having the screen freeze, would it be possible to have the same happen when opening the inventory like what happens with opening chests?

I've had this issue on 1.20.1 forge.

**Comment by emilyploszaj** [comment]
EMI doesn't freeze the inventory, if this is happening it's some other mod, potentially JEI or modernfix.
