### ISSUE TITLE
[ BUG ] Not showing a full recipe from Valhelsia Furniture

### ISSUE THREAD

**Issue by Xelbayria** [emilyploszaj/emi#705]
DETAILS: 
- Minecraft 1.20.1
- JEI v15.19.0.88
- Valhelsia Core v1.1.2

RELATED TO ISSUE:
- EMI v1.1.13
- Valhelsia Furniture v1.1.3 

Below will explain what's the problem. This is applied to both FORGE & FABRIC because the recipes in **Valhelsia Furniture** has a sort of "if statement" for TAGS or ITEM to use depends on loader.

FORGE: use TAGS - `"tags": "forge:rod/wooden"` IIRC 
FABRIC: use ITEM - `"item": "minecraft:stick"` 

I recommend that you take a look at the json of _oak_chair_'s recipe or other recipes

---

1) Install: 
- JEI 
- Valhelsia Furniture
- Valhelsia Core

Create a world, then check the recipe of _oak_chair_. You will see there are sticks in the recipe. 

---

2) Install:
- EMI
- Valhelsia Furniture
- Valhelsia Core

Do the same action above. You'll find that there is no stick in the recipe. Just as the title is self-explanatory. 

---

I also tried to use both JEI & EMI (I know they can work together). I checked the recipe and it's still missing the sticks. 

isn't this a problem on **Valhelsia Furniture**'s side? 
No, it's not a problem. I can craft the block using the recipe. First example above is clearly showing that JEI is working fine with the mod but not EMI.

**Comment by emilyploszaj** [comment]
I can't reproduce this on 1.21.1 or 1.20.1 (both Fabric). If there's a bug it has to be on Valhelsia's custom ingredient implementation on Forge.
![image](https://github.com/user-attachments/assets/59c99141-ae65-4ba1-ae19-a5a50320e0a6)

**Comment by Xelbayria** [comment]
have you tested it on FABRIC? what about FORGE? 

you should mark this as "not planned". well it's not really a bug. looks like it's just me. I'll need to dig deeper to find out what's going on

EDIT: 
Did you use just EMI? no JEI?

**Comment by emilyploszaj** [comment]
Yes, I tested Fabric 1.21.1 and Fabric 1.20.1, the screenshot is from the latter. With just EMI.

**Comment by Xelbayria** [comment]
I see. You should try out FORGE 1.20.1. I'll check FABRIC on my side, too. 

### UPDATED: 
Ok the FABRIC side is working fine. but FORGE is not working on my side. Let me know if you get the same result on your side. 

### DETAILS:

```json
{
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "group": "valhelsia_furniture:chair",
  "key": {
    "#": {
      "item": "minecraft:birch_planks"
    },
    "X": {
      "type": "valhelsia_core:platform_dependent",
      "fabric:type": "valhelsia_core:platform_dependent",
      "fabric_value": {
        "item": "minecraft:stick"
      },
      "forge_value": {
        "tag": "forge:rods/wooden"
      }
    }
  },
  "pattern": [
    "X  ",
    "###",
    "X X"
  ],
  "result": {
    "count": 2,
    "item": "valhelsia_furniture:birch_chair"
  },
  "show_notification": true
}
```

both FORGE & FABRIC has the exactly same recipe as above. Like i said it has a sort of "IF statement". It looks like `fabric_value` come first before `forge_value`. that may be why the sticks are not showing itself in EMI but did show itself in JEI.

**Comment by Xelbayria** [comment]
Please let me know if you got the same problem on FORGE as I do

**Comment by Xelbayria** [comment]
Haven't heard from you. Have you tested the mod on FORGE.

**Comment by emilyploszaj** [comment]
I have no clue why this issue only occurs on forge, but there is clearly an issue with the developers conditional ingredient implementation, EMI does not directly read json and both would not and could not interpret this conditional.

**Comment by Xelbayria** [comment]
yeah it's strange. I also tried with JEI using EMI, doesn't solve the problem.
