### ISSUE TITLE
[Crash :boom: ] EMI and Apothic Enchanting `LegacyRandomSource` crash

### ISSUE THREAD

**Issue by pietro-lopes** [emilyploszaj/emi#709]
Some interaction is going on there that is causing crash.

https://mclo.gs/00RRUFl (captured with BetterRandomSourceConcurrencyCrash mod)

Also, Apothic Enchanting dev said the following:
`"EMI should not be supplying the Level to the tooltip context if resolving it offthread"`

This crash is happening very frequently on ATM10

**Comment by ghost** [comment]
Adding a log from a second user on the ATM discord that has this issue, it is just about identical to the already supplied one
https://mclo.gs/2QkUF8N

**Comment by emilyploszaj** [comment]
Resolved in 1.1.14
