### ISSUE TITLE
EMI not checking items inside Integrated Dynamics terminal(logic cable) 1.20.1

### ISSUE THREAD

**Issue by VozDeOuro** [emilyploszaj/emi#714]
here you can see that I have the tin plate 

![image](https://github.com/user-attachments/assets/5840e2a3-c7d5-4b0a-b637-7e36ab0749b9)
![image](https://github.com/user-attachments/assets/d92c70ca-bfbf-4812-b2ef-44dc44633f6b)

**Comment by emilyploszaj** [comment]
This is Integrated Dynamics lacking proper integration
