### ISSUE TITLE
create recipe not appearing/ not loading 1.20.1

### ISSUE THREAD

**Issue by VozDeOuro** [emilyploszaj/emi#715]
Some recipes that don't use the crafting table are not loading like the crushing wheel on the image 
If you want to provide some logs just tell me what logs to send :) 
![image](https://github.com/user-attachments/assets/427447dc-f2bd-43c6-9760-2d782a5f1473)

**Comment by emilyploszaj** [comment]
Create doesn't have native EMI support. Make sure to install JEI alongside EMI to forward all recipes.
