### ISSUE TITLE
Refined storage pattern grid saying current workstation does not support recipe

### ISSUE THREAD

**Issue by veritsi** [emilyploszaj/emi#717]
refined storage pattern grid should be able to add recipe patterns no matter the workstation but it doesnt work with this mod please fix this.

![image](https://github.com/user-attachments/assets/8c1452e4-2d4b-4c2d-92ce-16ea74005001)

**Comment by emilyploszaj** [comment]
Make sure JEI is installed to forward the support.

**Comment by veritsi** [comment]
> Make sure JEI is installed to forward the support.
still doesnt work?
