### ISSUE TITLE
EMI uses outdated JEI custom Ingredient Type API

### ISSUE THREAD

**Issue by petrolpark** [emilyploszaj/emi#719]
The deprecated method `getTooltip` is referred to [here](https://github.com/emilyploszaj/emi/blob/2df533755f8d03cef9beaf1a2b8193eaeb08af10/xplat/src/main/java/dev/emi/emi/jemi/JemiStack.java#L87).

Mods which use the new, replacement API (with TooltipBuilder) therefore don't supply a tooltip.

**Comment by emilyploszaj** [comment]
Resolved in 1.1.14
