### ISSUE TITLE
[Feature Request] Centered one-item recipes

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#723]
Why so line recipes are centered, but single-item ones are not?

![image](https://github.com/user-attachments/assets/afc29127-a81f-4c76-8bc3-12e8d1cba1c0)
![image](https://github.com/user-attachments/assets/daafe814-3141-4dbb-bd50-523c002477e6)

**Comment by emilyploszaj** [comment]
Shaped recipes are centered, shapeless are not, this is consistent to EMI's design language
