### ISSUE TITLE
EMI adds persistent background tint and breaks Flow config options

### ISSUE THREAD

**Issue by Spazer-Prime** [emilyploszaj/emi#727]
Weird background tint with EMI installed. It moves with Flow's animation rather than fading in and out. Tried changing Flow's blur strength and background tint options to see if it'd help but they also seem to be broken. Disabling EMI ingame doesn't fix it, but uninstalling it completely fixes the issue and allows Flow's config options to work. I ran the game with only Flow, MRU, and EMI installed to make sure there wasn't another mod causing it.

MRU Version: 1.0.2 - 1.20.1 - Fabric

Flow Version: 2.1.2 - 1.20.1

EMI Version: 1.1.13 - 1.20.1 - Fabric

https://github.com/user-attachments/assets/4f50418c-f5d9-4833-8e46-ab08622fb34a

**Comment by emilyploszaj** [comment]
This is an issue with Flow, please report it to them.

**Comment by Fireeyeeian** [comment]
Sadly, flow won't be updating 1.20.1, would it be possible to disable the Background tint in EMI? I tried looking through emi code here and didn't see anything related to the background tint (I never learned java so it's not my strong suite) and I tested with only EMI installed, so the darkened screen seemed to be from EMI as far as I can tell.
