### ISSUE TITLE
EMI 1.1.14 for Forge having problems showing GTCEu Multiblock structure diagrams for custom GTCEu Modern multiblocks and GTCEu Modern recipes.

### ISSUE THREAD

**Issue by AncientShotgun** [emilyploszaj/emi#728]
For reference, I am running EMI 1.1.14-1.20.1 for Forge.
JEI version 15.20.0.101
KubeJS version 2001.6.5-build.14
Rhino version 2001.2.3-build.6
GTCEu Modern version 1.4.4
Here is a log, with personal details obfuscated, that illustrates the problem.
[latest_obfuscated.log](https://github.com/user-attachments/files/17235870/latest_obfuscated.log)
As you can see, EMI does not display GTCEu Modern Multiblock structure diagrams for custom Multiblocks defined via KubeJS, instead throwing errors. GTCEu recipes that are done in machines, both custom and native, are also not displayed, and also have errors thrown. It also has trouble loading the EMI Loot plugin but I believe that isn't related to this issue.
Note that all recipes still work in their respective machines, it is purely EMI having display issues. Crafting table recipe display is unaffected, with the exceptions of those using GTCEu Modern tools. 
I reiterate, all recipes still work, and I assume that all Multiblocks will still form correctly, they are just not displayed. 
Incidentally, Multiblocks that are native to GTCEu Modern have their structure diagrams correctly displayed.
If required, I can also provide a sample multiblock definition to test against.

**Comment by emilyploszaj** [comment]
Please open this bug on GTCEu
