### ISSUE TITLE
[Minecraft 1.21.1] [EMI 1.1.14] Recipe Tree does not expand fully.

### ISSUE THREAD

**Issue by spinodal23** [emilyploszaj/emi#729]
(No game crash.)
There may be similar issues, but I could not find one because there are too many issues.

Minecraft version: 1.21.1
Fabric Loader: 0.16.5
Fabric API: 0.102.1
EMI: [1.1.14](https://modrinth.com/mod/emi/version/1.1.14+1.21.1+fabric)
+) Refined Storage 2: [v2.0.0-milestone.4.7](https://github.com/refinedmods/refinedstorage2/releases)
+) Refined Storage - EMI Integration: [v0.4.1](https://github.com/refinedmods/refinedstorage-emi-integration/releases/tag/v0.4.1)

Recipe Tree does not expand fully. Some vanilla items do show recipe tree on their own but do not show when it is part of other recipe tree.
.
.
.
Images below for: End Crystal, Glass, Glass Pane, Crossbow, Potion of Harming, (Refined Storage 2) Controller

Tree of End Crystal - According to the Modrinth page, recipe of Glass(smelting) should be shown.
![image](https://github.com/user-attachments/assets/9c545ec0-8642-45f5-ad7e-4b66cb2caf90)

Tree of Glass - There is a recipe tree of Glass, but it does not show it is part of other tree, e.g. Glass Pane.
![image](https://github.com/user-attachments/assets/c43081ae-a8c4-45a8-ba12-0ed432de6277)

Tree of Glass Pane
![image](https://github.com/user-attachments/assets/e1f0903a-e9d6-4a2a-825f-423cf157f1ef)
.
.
.
Tree of Crossbow - recipe of Stick(crafting) should be shown.
![image](https://github.com/user-attachments/assets/1ad90ad6-6dbc-411b-86fe-c2ecc8e74a67)

Tree of Potion of Harming - recipe of Water Bottle should be shown.
![image](https://github.com/user-attachments/assets/7df34758-83c1-4727-9b8a-c719419ff926)
.
.
.
for Refined Storage 2 mod

Tree of Controller - Most of the subtrees are not shown.
![image](https://github.com/user-attachments/assets/0686c757-6090-40e2-aa7c-14f12ea52e67)

**Comment by fzzyhmstrs** [comment]
This is expected behavior for recipe trees. If there is more than one crafting mode and a "default recipe" hasn't been defined by the recipe creator, and the heart icon hasn't been clicked on the recipe screen, that node of the tree won't be expanded. 

If you want to expand it, either of the ways above will "permanently" cause it to be expanded, or you can click on the item in the tree and then click the output of the recipe you want to see in the tree and it will temporarily expand to that recipe.

**Comment by spinodal23** [comment]
Oh I see.
What is heart icon? And How can I set the default recipe?

**Comment by fzzyhmstrs** [comment]
Look at any recipes in the viewer, you'll see a little heart on the right side. There is an overview of recipe defaults on the wiki : https://github.com/emilyploszaj/emi/wiki/Recipe-Defaults

**Comment by spinodal23** [comment]
Thank you for your answer. :)
I think you can close this now.
