### ISSUE TITLE
[Crash] [1.21.x] [Neoforge]: JEI updates cause EMI incompatibility

### ISSUE THREAD

**Issue by ffuentesm** [emilyploszaj/emi#732]
Steps to Reproduce the Crash
The game crashes when I try to shift-click a recipe into the crafting table.
This never happened before, but is starting to do it now. I am using polymorth and JEI alongside.
I tried to remove Polymorph, but the crash still happened.

https://github.com/mezz/JustEnoughItems/issues/3793

Extra Notes
polymorph-neoforge-1.0.6+1.21.1
jei-1.21.1-neoforge-19.19.6.233
emi-1.1.14+1.21.1+neoforge
Neoforge:21.1.65

Crash Report
https://pastebin.com/U3qrLkvz

**Comment by ffuentesm** [comment]
Also, there might have problems with Caelus API too.

[Thread-20/ERROR] [EMI/]: [EMI] Critical error occured during reload: java.lang.NoClassDefFoundError: top/theillusivec4/caelus/api/CaelusApi

**Comment by emilyploszaj** [comment]
Should be resolved in 1.1.15
