### ISSUE TITLE
Issues with EMI mod loading

### ISSUE THREAD

**Issue by Gui1803** [emilyploszaj/emi#733]
Hello. I'm having an issue with EMI and the Nature's Aura mod during EMI loading. I get the message "EMI experienced a critical exception while reloading, check log," and in the log, I receive a bunch of data, but I'm only posting the part where the problem occurs since it seems to work normally otherwise.

I tried different versions of both mods, but it didn't work. The log is specifically from the test with both mods in their latest versions (emi-1.1.14+1.20.1+forge; emiffect-forge-1.1.2+mc1.20.1; NaturesAura-39.4). By the way, it's from the ATM9 Modpack, but I manually added EMI.

I'm also reaching out to the Nature's Aura mod creator, but I haven't gotten a response yet.

One detail is that, sometimes, even with the error, EMI still loads, but I couldn't find any difference in the log between when it loads or when it fails and stops. I would also like to know if there's any command to force a reload without having to leave and rejoin the map (private server)

https://pastebin.com/hYbVTVMW

**Comment by emilyploszaj** [comment]
This exception is non fatal, related to Nature's Aura's compat with JEI, and not the reason you're experiencing any critical exceptions, the real reason is not even visible in your log.

**Comment by Gui1803** [comment]
Okay, so here's the full log from one loading session (starting from the moment I joined the server, as the log size is huge and MultiMC limits it). This time specifically, EMI didn't load (even after 20 minutes).

https://mclo.gs/ElUWXAy
