### ISSUE TITLE
[Mod Compat] JEI API not up to date 

### ISSUE THREAD

**Issue by mxnmnm** [emilyploszaj/emi#734]
Basically just this issue on 1.20.1: https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/17

Tested with EMI 1.1.14

**Comment by ffuentesm** [comment]
This is also on 1.21.1
JEI made some major API changes, and EMI still need up add the compat layer for that

**Comment by emilyploszaj** [comment]
Resolved in 1.1.15
