### ISSUE TITLE
(Sometimes) EMI does not load

### ISSUE THREAD

**Issue by Gui1803** [emilyploszaj/emi#736]
As the title says. This time, I managed to organize the log into a single file. There is both the client log and the server log (which is localhost). In this specific log, EMI did not load even after 20 minutes. I mention this because sometimes it still shows me the message "EMI experienced a critical exception...", but it still loads afterwards.

Client log: https://mclo.gs/WImpRUk

Server log: https://mclo.gs/opOkag4 (sending this because I don't know if it might be useful. The times don't match because the server has been open for some time).

**Comment by emilyploszaj** [comment]
I believe this is due to either a self mutating item, or a bug in Nature's Aura which throws exceptions in its JEI subtype interpreter, please report this to Nature's Aura.

**Comment by LordPINE** [comment]
This issue seems to be on EMIs side, as the subtype handling code assumes there's a subtype with no NBT data to set as a default comparison. This works for most items, but not for Nature's Aura ItemEffectPowder, as all subtypes have some NBT to mark which specific type they are.
