### ISSUE TITLE
[Bug] Enchantment acceptable items show on only with last-tier enchantment

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#738]
Efficiency V:
![image](https://github.com/user-attachments/assets/27e42b16-e655-4002-90a2-365da719a3f2)

Efficiency I:
![image](https://github.com/user-attachments/assets/1755d548-b0c7-4f4f-9087-c62d4d06954b)

**Comment by emilyploszaj** [comment]
#444
