### ISSUE TITLE
Item tag default resolution cannot be cleared

### ISSUE THREAD

**Issue by Possseidon** [emilyploszaj/emi#739]
While you can specify a default item to use for tag resolution, I can't find a way to remove the default again.

For normal recipes this is done by clicking the heart button, but the tags page (rightfully) does not have a heart button.

I think the most intuitive approach would be if ctrl-clicking the current default item just clears it again; this would actually also be useful for normal recipes with multiple outputs where you currently have to clear all using the heart button and then start selecting which outputs you want to use as default.

**Comment by Possseidon** [comment]
~~Ah, I did find a way to clear it, but it's not ideal:~~

~~If the tag resolution is actually used in a recipe tree, clicking on the tag resolution icon will show a little box at the bottom to clear the default recipe.~~

~~This is a bit hidden though and only works for tags that are actually used in a recipe.~~

Nevermind, that only clears it for the current recipe tree, not globally.

**Comment by emilyploszaj** [comment]
This is a weird hole in the default stack bind behavior, in 1.1.15 using the bind on a defaulted stack will *remove* the default, letting you clear tag resolutions.
