### ISSUE TITLE
[Mod Compat] [1.19.2 Forge] EMI fails to detect ingredients to Fill Recipe if crafting within Crafting Station that has an adjacent container.

### ISSUE THREAD

**Issue by Geekerandy** [emilyploszaj/emi#746]
Forge Version: _43.4.0_ (Latest *stable* version as of this post, bug was also reproduced in the bleeding latest Forge version of _43.4.4_)
EMI Version: _1.1.16+1.19.2+forge_ (latest build as of this issue)
JEI Version: _11.8.1.1033_
Crafting Station Version: _1.19.2-6.0.3_

In the attached video, I demonstrate EMI working as intended, correctly detecting ingredients in the inventory to Fill Recipes with a normal Crafting Table, and a Crafting Station.

The Crafting Station has the ability to display the inventory of adjacent containers to assist in crafting. However, when this feature is used, EMI fails to be able to detect ingredients within the adjacent container or in the inventory, thus being unable to Fill Recipes. 

https://youtu.be/v9FiaeYkdFM

**Comment by emilyploszaj** [comment]
Please upload a log so I can make sure this isn't just improper integration by the crafting station mod
