### ISSUE TITLE
Left Sidebar, Align Bottom does not appear to do anything

### ISSUE THREAD

**Issue by eSonOfAnder** [emilyploszaj/emi#749]
### Describe the bug, attach relevant log files, and describe what environment the issue occurs in
Using as part of the BCG modpack: https://www.curseforge.com/minecraft/modpacks/bcgnc

Installed version of mod is: 1.1.12+1.20.1+Fabric

Repro steps:
Open EMI Config
Go to Left Sidebar
Set the Align value to Left and Bottom

Expected results:
Left sidebar is now aligned to the bottom of the screen

Actual results:
Left sidebar remains aligned to the top of the screen

**Comment by emilyploszaj** [comment]
Please provide screenshots of your config and the effects in game

**Comment by eSonOfAnder** [comment]
![EMI Config](https://github.com/user-attachments/assets/5a6f24ce-5835-44a7-9869-14f9da6a6c90)
![EMI display](https://github.com/user-attachments/assets/4ae63fa7-3ad0-4b59-800d-09da7c620429)

**Comment by emilyploszaj** [comment]
You have your sidebar side to 100 rows. If you enabled a background, you'd be able to see that the sidebar is aligned to the bottom of the screen. If you want your header lower, you need to have fewer rows.
