### ISSUE TITLE
Crash when middle clicking and scrolling at the same time on the favorites bar

### ISSUE THREAD

**Issue by snowtest-sled** [emilyploszaj/emi#75]

**Comment by emilyploszaj** [comment]
Do you have a crash log I can look at? I'm unable to reproduce this

**Comment by snowtest-sled** [comment]
https://0.0g.gg/?f4df25c5426c20e7#FyDN67hsF4Djw4GSgosmKGc6Q5Mpep6gHKk7EXSZpqVr

**Comment by snowtest-sled** [comment]
https://0.0g.gg/?b7c0ff0fec085571#2wpKQJcU2B3sXbvLrHususvT5MGHqWWgm3wigsrufMdL

**Comment by emilyploszaj** [comment]
Fixed in 0.4.0
