### ISSUE TITLE
Recipe Tree: GT Ghost Circuits not recognized

### ISSUE THREAD

**Issue by riking** [emilyploszaj/emi#751]
### Describe the bug, attach relevant log files, and describe what environment the issue occurs in

1. Establish a Recipe Tree that includes machine processing steps as intermediate steps, e.g. [Monifactory] the GregTech assembler recipe for Vacuum Tubes as a precursor to basic LV Circuit
2. Switch the recipe tree to Crafting Mode, so each step shows up in the favorites panel
3. Hold all inputs to the recipe in your inventory
4. Observe that the recipe target (here, the Vacuum Tubes) displays as red ("uncraftable") despite all of its inputs being satisfied and removed from the listing

### Desired Behavior

The recipe target is colored cyan or similar (green?) to indicate it's ready to start, even if it can't be done in a 3x3 crafting table.

When in a correct machine GUI, shift-clicking the recipe target dumps the items into any available input slots.

**Comment by emilyploszaj** [comment]
Please supply screenshots

**Comment by riking** [comment]
Okay for some reason this _just_ worked for me in game. Let me try to figure out why...

**Comment by riking** [comment]
Okay I think it's because of the Programmed Circuit configuration.

![image](https://github.com/user-attachments/assets/85d33bbe-d79e-4e5e-8a08-e96e27f2ba61)

<small> ignore the voltage mismatch, I swapped to a smaller recipe to take screenshots with </small>

![image](https://github.com/user-attachments/assets/ab6079d0-48fe-493e-ac33-75003cd0f307)

In the lower left is a "Free Ghost Circuit" which is counted as part of the recipe, but EMI can't see it in my or the machine's inventory to count it as satisfied.

**Comment by emilyploszaj** [comment]
This is a mistake on GT's end, circuits should be considered catalysts to not be counted in the recipe tree.
