### ISSUE TITLE
[Mod Compat] recipe view says "error rendering" when viewing recipe from Refined Storage mod's crafting grid

### ISSUE THREAD

**Issue by noobcoconut** [emilyploszaj/emi#753]
recipe view fails to render and show "error rendering" when viewing recipe from Refined Storage mod's crafting grid

Forge Version: 47.3.11
Minecraft Version: 1.20.1
EMI Version: 1.1.16
 - tested on 1.1.15 and 1.1.14, they don't have this issue

JEI Version: 15.20.0.104

couldn't find anything from the log
to reproduce, search any recipe from Refined Storage mod's crafting grid

**Comment by fzzyhmstrs** [comment]
If you are on the latest release version of JEI, try updating to the latest beta

**Comment by noobcoconut** [comment]
I was using the latest beta JEI which came out on Oct 8th

**Comment by emilyploszaj** [comment]
With no log there's no way to debug this, we've had similar errors with EMI, JEI, or other mods not being updated lately
