### ISSUE TITLE
[Mod Compat] JEI IRecipeCategory#getBackground() may return null

### ISSUE THREAD

**Issue by desht** [emilyploszaj/emi#755]
As of JEI 19.19.0, `IRecipeCategory#getBackground()` is deprecated, and returns null by default. The intention here is for plugins to do their own background drawing in `IRecipeCategory#draw()` (which is usually as simple as `drawable.draw(guiGraphics)`).

To account for this, `JemiRecipe.JemiWidget#render()` needs to be updated to check if `getBackground()` returns null, and if so, skip the `category.getBackground().draw(context.raw());` call.

**Comment by emilyploszaj** [comment]
Adjusted in 1.1.17
