### ISSUE TITLE
[Mod Compat] EMI is not grabbing unique JEI recipes for current Create Mod version 0.5.1i (Forge 1.20.1)

### ISSUE THREAD

**Issue by DizzyPrime** [emilyploszaj/emi#756]
Currently the newest version of Create, 0.5.1i will have it's recipes working fine in JEI but once EMI is added will no longer show unique create recipes (No pressing recipes, mixing recipes, sanding recipes ect.). This is specific to Create, tested with Botania and Mekanism both showing unique recipe types such as Mana Conversion.

Downgrading to Create 0.5.1h or lower or removing EMI and just using JEI fixes the issue.

It seems like it will not cache the recipes on a fresh install but upon downgrading and then reupgrading Create versions causes the recipes to suddenly appear as normal. (Tested in 2 instances, one where EMI was installed fresh, one where I had changed Create versions back and forth, recipes only appear in the ladder)

**Comment by DizzyPrime** [comment]
Forgot to mention the way I tested if it was working was looking at the uses for Rose Quartz (right click) and recipe for Sheets of any material

Fresh install:
![image](https://github.com/user-attachments/assets/219ebd2c-2e93-45d3-802f-3d314049534a)

Recipe Loaded in previous create version and then updated to current:
![image](https://github.com/user-attachments/assets/4498e616-b0f4-47c1-9175-d7420cd516d6)

All recipes will be loaded correctly in the second instance, even ones that were not originally looked at such as pressing and mixing recipes

**Comment by emilyploszaj** [comment]
![image](https://github.com/user-attachments/assets/01eb99ca-8f1a-4a69-98a4-a0659b56e644)
This is me testing on a fresh version of 1.20.1 with the latest Create, EMI, and JEI versions
