### ISSUE TITLE
[Mod Compat] Using JER and connecting to a server can hang the game with certain performance mods. 

### ISSUE THREAD

**Issue by GibrielS** [emilyploszaj/emi#759]
Mod list:
FerriteCore
Nvidium
Terralith
Mod Menu
Just Enough Effects Descriptions
ImmediatelyFast
Fabric Language Kotlin
ThreadTweak
Create
Noisium
EMI Loot
Enhanced Block Entities
No Chat Reports
Just Enough Breeding
EMI Ores
EMI
Very Many Players
Just Enough Resources
Extra Mod Integrations
Create: Numismatics
EMIffect
Concurrent Chunk Management Engine
EMI Enchants
Just Enough Professions (JEP)
BadOptimizations
EMI Trades
Lithium
Sodium
ModernFix
Fabric API
Fzzy Config
More Culling
Indium
EMI Enchanting
Cloth Config v11
Just Enough Items
EntityCulling

Several Mods are likely clashing, and EMI works fine if only paired with JEI and JER.

Modpack dependant mod list:
Simply Optimized 1.21.1-4.0.2
Create
Create Numismatics
EMI
JEI
JER

**Comment by emilyploszaj** [comment]
If this is working without performance mods, you need to figure out the specific mods causing the issue and report it to them.

**Comment by GibrielS** [comment]
Okay, https://github.com/RelativityMC/C2ME-fabric/issues/369
