### ISSUE TITLE
[Mod Compat] 1.21.1 Crash with Ars Nouveau item

### ISSUE THREAD

**Issue by Hiranus** [emilyploszaj/emi#760]
https://mclo.gs/49nzSqj

This crash happens when I'm searching `@ars` in EMI and switch to the second page in All The Mods 10 pack. This crash does not happen with JEI.

**Comment by Hiranus** [comment]
Issue in Ars Nouveau tracker https://github.com/baileyholl/Ars-Nouveau/issues/1453

**Comment by theboo** [comment]
This is actually an issue with the ars additions addon mod for ars nouveau.. it needs to be updated for compat with the most recent ars nouveau update.. is not an emi or jei issue

**Comment by Hiranus** [comment]
![image](https://github.com/user-attachments/assets/e2088768-1ab2-4591-ab83-dfd7822f530e)
