### ISSUE TITLE
[AE2] - Filling crafting Grid

### ISSUE THREAD

**Issue by rafael-ferreira3** [emilyploszaj/emi#762]
NeoForge - 21.1.72
Applied Energistics 2 - 19.0.23
EMI - 1.1.16

When I Shift + Click an item from EMI, it moves to the crafting grid when using a regular crafting table. However, when I use the AE2 crafting terminal, the items only move to the grid if they are in my inventory. If the items are stored in the AE2 drives, nothing happens.

**Comment by emilyploszaj** [comment]
Please report this to AE2
