### ISSUE TITLE
How to disabled or remove the "white arrow" when favoriting a recipe?

### ISSUE THREAD

**Issue by toastonrye** [emilyploszaj/emi#764]
### Describe the bug, attach relevant log files, and describe what environment the issue occurs in

Hi, I can't figure out what the little white arrow symbols are in the favourite screen, what they mean, and how to disable their functionality. I've browsed through the config but I don't even know what to call them.

I want to see all the recipes, not just the default one... If that makes sense?

![2024-10-26_08 30 19](https://github.com/user-attachments/assets/08c1fc6c-cd3d-400d-9fa5-8a3750d2114c)

**Comment by emilyploszaj** [comment]
When you favorite a recipe (or the output of a recipe), you save a recipe, which is indicated by the arrow. If you favorite stacks you look up in the index or as ingredients of a recipe, you will not save the recipe as shown.

**Comment by emorygg** [comment]
I guess the question is, Is there a way to only favorite the item? I don't want to favorite the current selected recipe
