### ISSUE TITLE
 game crashed 

### ISSUE THREAD

**Issue by INV-PLA** [emilyploszaj/emi#768]
[错误报告-2024-10-26_16.10.59.zip](https://github.com/user-attachments/files/17532478/-2024-10-26_16.10.59.zip)
The game crashed because the error log mentioned EMI, so I provided feedback. It may not be or not be caused by EMI alone, but I don't know, so I provided feedback once. I'm sorry

**Comment by emilyploszaj** [comment]
This is unrelated to EMI
