### ISSUE TITLE
[Mod Compat] 1.20.1 CREATE machanical crafting recipies, crushing wheel recipies, Sequenced Assembly recipies not showing up when clicking the blocks inside of the EMI menu

### ISSUE THREAD

**Issue by axtrough** [emilyploszaj/emi#769]
### If this issue is related to compatibility with other mods, such as missing recipes, make sure to follow these steps before reporting

- [x] Make sure the recipe exists in game and can be crafted
- [x] If the mod requires JEI, make sure both EMI and JEI are installed together
- [x] Report this issue to the mod if applicable

The mod may require jei. but when i have it installed next to emi it doesnt work. 
if i only have jei installed it works

**Comment by emilyploszaj** [comment]
![image](https://github.com/user-attachments/assets/6438f705-4d56-444e-bef4-93dff7f3c12e)
Recipes are showing up on the latest versions of EMI, JEI, and Create
