### ISSUE TITLE
Item Zoom (Feature or Compatibility)

### ISSUE THREAD

**Issue by Helimyne** [emilyploszaj/emi#770]
Making a 1.20.1 pack and found that the mod item zoom (made by mezz) is compatible with Jei, but does not work with Emi, since playing a pack with EMI I have not looked back, love it, hope you can add this feature.

PS. Can you add persistent search bars to extra index panels? or at least make a mod cycle mode?

Thanks! Helimyne

**Comment by emilyploszaj** [comment]
This is not something EMI can add compatibility for.

**Comment by Helimyne** [comment]
The reason I wanted this feature is I play on a ultrawide 1440p screen and my preferred gui scale leave mods like chipped/chisel really hard to see block textures.
I suppose this isn't a feature you interested in developing either?
If not, thanks for an awesome mod anyway !!
Maybe one day I'll make a custom scale per gui mod.
Have a great day!
