### ISSUE TITLE
(Feat) Revert to JEI from EMI

### ISSUE THREAD

**Issue by robertmaxton42** [emilyploszaj/emi#772]
Hi! I'm running a small-ish private modded server, and I'm currently having issues with some JEI-related addons that I'm trying to debug. (I don't actually know whether the bug is in JEI or EMI yet.) For that purpose, it'd be nice to be able to easily revert from EMI to plain JEI. 

Some of my EMI addons (specifically EMI Loot, I believe) have to be matched between client and server, so I can't just remove EMI client-side without also telling all my players to remove it as well. It would be nice if EMI could self-disable, ideally from within Minecraft itself, in a way that doesn't take down JEI entirely with it.

**Comment by emilyploszaj** [comment]
EMI is a mod separate from JEI, not an addon. There is no clean way for EMI's compat with JEI to be toggled live and this unfortunately isn't really a use case that the mod was designed for. Sorry.
