### ISSUE TITLE
BUG/FEATURE maybe? Removing favorites from tags

### ISSUE THREAD

**Issue by rhit-lindsekb** [emilyploszaj/emi#773]
Is there a way to Remove favorites in crafting recipes? Ran into an issue in a pack where I had a tag item selected as a favorite for all recipes and wanted to remove it to be the umbrella item. I ended up going into the emi.json and removing it from the tags 
![image](https://github.com/user-attachments/assets/d82688ed-9ca5-41c7-8018-946d7549f98c)
![image](https://github.com/user-attachments/assets/adb6bdb2-f7fd-44c4-b4ea-7a3282f1ff25)
![image](https://github.com/user-attachments/assets/c5d6f1c5-5285-45ea-b91b-ccc79d8ca49b)

when i clear the resolution it temporarily removes the favorite for that one craft but when I open up a new tree it goes back to whatever is selected as the favorite. It would probably be benefitial to be able to select the top item to be able to undo the favorite selection or some way to cancel it in general. Maybe i just missed it but i spend a while messing with it and couldn't figure it out intuitively.

![image](https://github.com/user-attachments/assets/403fda16-6da3-4065-8dda-2644d70b9617)

**Comment by emilyploszaj** [comment]
There's a "set default" keybind in the in the EMI config you can use, which will unset a default on a tag. It's a bit cumbersome but it works.

**Comment by rhit-lindsekb** [comment]
I do not see that keybind in any of the config files or in the in game config.
![image](https://github.com/user-attachments/assets/ab68edc3-92b8-41a9-bc5f-f070e00984a0)
@emilyploszaj

**Comment by rhit-lindsekb** [comment]
Can somebody tell me what I'm missing here.

**Comment by mason-dunn** [comment]
There is definitely a bug with this feature. The 'Default Stack' key bind doesn't seem to properly toggle the default item. Currently, if you select a tag as default for all recipes and then you activate the key bind again you would expect it to remove the item as the default for all recipes but it doesn't.

![emi-default-slot-before](https://github.com/user-attachments/assets/6b023d45-281b-4326-bfb5-6c5bbfbefc8a)

**Comment by emilyploszaj** [comment]
This was changed in the release yesterday to function as expected

**Comment by mason-dunn** [comment]
I see the change in the commit history that you changed, but I'm not seeing expected behavior.. or maybe I'm misunderstanding the expected behavior. The gif I recorded is using the latest release. I have made changes to do what I understand to be the expected behavior.
![emi-default-slot-after](https://github.com/user-attachments/assets/2ea3e6fb-45a1-4b9a-bb46-06c300798362)

**Comment by emilyploszaj** [comment]
Right you are, this should be properly fixed in 1.1.18, thanks for keeping an eye on it
