### ISSUE TITLE
Missing Set default Keybind

### ISSUE THREAD

**Issue by rhit-lindsekb** [emilyploszaj/emi#775]
I do not see that keybind in any of the config files or in the in game config.
![image](https://github.com/user-attachments/assets/ab68edc3-92b8-41a9-bc5f-f070e00984a0)

_Originally posted by @rhit-lindsekb in https://github.com/emilyploszaj/emi/issues/773#issuecomment-2444055487_

**Comment by emilyploszaj** [comment]
"Default Stack" is what you're looking for, ctrl left click by default

**Comment by rhit-lindsekb** [comment]
@emilyploszaj I do not want to set an item to a default, i want to be able to remove it from being the default item.

**Comment by emilyploszaj** [comment]
Using this bind in the tag screen will toggle
