### ISSUE TITLE
EMI crashes when baking recipies after joining a world (Singleplayer & Multiplayer)

### ISSUE THREAD

**Issue by Ealeex** [emilyploszaj/emi#776]
I'm currently working with a team of people to develop a new modpack for Minecraft 1.20.1.
Here is the [mod list](https://legacy.curseforge.com/minecraft/modpacks/covecraft/relations/dependencies).

Whenever someone boots into a world (SP and MP affected), there is a chance that the EMI will show the text "EMI experiences a critical exception while reloading, check log". This is not consistent, as it is not a 100% failure rate and is unpredictable of when it will fail. Sometimes it can be fine for an hour and then fail. In the latest incident that I've recorded, it seemed to crash multiple times and kept trying to reload, this seems to cause the user to freeze while it's reloading.

Attached is an latest showing the error.
[latest.log](https://github.com/user-attachments/files/17587372/latest.log)

Attached here is an excerpt from the log.
![{71AABD3A-29EA-4DF0-9C84-09F49337B022}](https://github.com/user-attachments/assets/342b8dfd-bb32-4aa5-b188-a562a5d9338c)

**Comment by Ealeex** [comment]
I'm mostly just confused as to why this would be happening. My best guess is an incompatible mod or too many mods.

**Comment by emilyploszaj** [comment]
This is caused by some mod with an illegally mutating stack... there's no defined way to handle this, but EMI has been changed to gracefully log the error rather than fail to load in 1.1.17

**Comment by Ealeex** [comment]
Is there an easy way to easily find which mod is causing it? It's very inconsistent, so trying individual mods would take forever.

**Comment by emilyploszaj** [comment]
On the latest version, the log will indicate the stack causing issues

**Comment by Ealeex** [comment]
Thank you so much for the quick fix. From my logs, I can see that it seems to be Nature's Aura causing an issue.
Is this something that they can fix? Do I need to open a issue with them?

Edit: I opened an [issue](https://github.com/Ellpeck/NaturesAura/issues/370) with the Nature's Aura mod repo.

![{37681CAC-6037-489C-A013-1BB1491C43F6}](https://github.com/user-attachments/assets/cfbd455f-79d2-4d35-9f15-ac3dc655a840)

**Comment by emilyploszaj** [comment]
I've seen nature's aura causing issues like this in the past, not sure exactly what they're doing, best to see if they can resolve it
