### ISSUE TITLE
Support 1.21.2/3?

### ISSUE THREAD

**Issue by CyanChanges** [emilyploszaj/emi#785]
I like this mod, it is amazing.
I want to use it in latest version of Minecraft.
When will it updated to 1.21.3?
It will be great if you can do this.

**Comment by DaemonDeathAngel** [comment]
I've touched base with EMI in the discord regarding this, the response I received was that there is currently some porting work completed, but seeing as with the update to 1.21.3 breaking a bunch of things regarding Rendering, specifically GUI, there's no solid timeframe of when it will be released. According to EMI, the NeoForge project has recommended people avoid 1.21.3 for the time being, and stay on 1.21.1 as far as a modding standpoint is concerned.

**Comment by emilyploszaj** [comment]
This response is basically what I would say. I can't give you a timeline as my time is limited and 1.21.3 is not a massive priority, but I do intend to update and will do so eventually. I don't consider version bumping a proper issue to track, so I will close this.
