### ISSUE TITLE
[1.21.1] Crafting Station renders in the wrong place

### ISSUE THREAD

**Issue by ALIAS-001** [emilyploszaj/emi#790]
### Describe the bug, attach relevant log files, and describe what environment the issue occurs in
EMI Renders crafting stations in a misplaced position
Version: 
EMI 1.1.18 1.21.1
NeoForge 21.1.77
![2024-11-18_17 50 48](https://github.com/user-attachments/assets/afe3b98e-97a1-4736-bd98-9c5fdadbad35)
Meka Suit Chest plate Recipe tree

**Comment by embeddedt** [comment]
Can confirm in a standalone 1.21.1 instance with EMI and Mekanism. Disabling the batched renderer in EMI's settings is a temporary workaround. 

While testing this, I also noticed the Mekasuit energy levels (seen below) are not rendered with batching active.

![image](https://github.com/user-attachments/assets/a798c07f-c206-495d-9264-f40f942cd2a2)
