### ISSUE TITLE
[Mod Compat - Bug] Incompatible with Sophisticated Backpacks/Core

### ISSUE THREAD

**Issue by IranMine123** [emilyploszaj/emi#791]
Hello. There is a bug when trying to Recipe fill using Sophisticated Backpack Crafting Upgrade (`sophisticatedcore:emi_fill_recipe`).
tell me if it should be fixed by the Sophisticated Core Developer.
log of error: https://mclo.gs/jnayaJX
video:

https://github.com/user-attachments/assets/617d1500-e0bd-41d5-b45b-0f754d73c375

**Comment by emilyploszaj** [comment]
Open this to Sophisticated Core Devs
