### ISSUE TITLE
[Mod Compat] 1.20.1 GregTech autocrafting not working with refined storage storage pattern grid

### ISSUE THREAD

**Issue by KeksNino** [emilyploszaj/emi#794]
when i try to fill the gregtech machine recipe in the refined storage pattern grid it says current workstation does not support recipe.

![grafik](https://github.com/user-attachments/assets/b04e21f1-0b86-4393-acfc-5780fe3a040c)

**Comment by emilyploszaj** [comment]
Gregtech has historically broken this, report it to them
