### ISSUE TITLE
[Request] TechReborn support

### ISSUE THREAD

**Issue by Trnrr** [emilyploszaj/emi#8]
I'm not sure if this should be suggested here or on their issue tracker.

I would like to request support for Tech Reborn machines. https://github.com/TechReborn/TechReborn

**Comment by LemmaEOF** [comment]
That would be on their issue tracker - Emi doesn't really have the time to add support for different mods herself, just like how Shedaniel doesn't have time to add REI support for different mods

**Comment by emilyploszaj** [comment]
Hi, yeah, as Lemma said, EMI does not provide support for mods natively, this is the responsibility of mods themsleves or third party plugins. If you're interested, opening an issue on their tracker may be a good idea, but be careful to not open duplicate issues, as a developer may have already decided against support.
