### ISSUE TITLE
Recipe Filling not filling slots properly on Modded Table

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#80]
Issue is in regard to plugin of my mod (but may affect others): [My Plugin](https://github.com/fzzyhmstrs/ai/tree/master/src/main/kotlin/me/fzzyhmstrs/amethyst_imbuement/compat/emi)

Version: emi-0.4.0+1.19, with emi-0.3.1+1.19 as cross ref

Sometime above version 0.3.1, the first version I developed my plugin with, recipe filling behavior has either changed or broken such that slots aren't quite filled properly. When I "Fill Recipe" into my grid in 0.4.0, the first slot is missed. In 0.3.1 all slots fill properly.

![recipe_issue_trimmed](https://user-images.githubusercontent.com/72876796/188769049-b215dba3-54cf-4fc6-b0e2-2fdf7d27b81b.gif)

A related issue I'm having is with filling certain recipes at all, that seems to be related to NBT data. Below I have a recipe that's fully ready to transfer as seen by EMI knowing and showing that I can "Fill Recipe" yet the button does not do anything when clicked. Clicking on the favorite also does not move any items, it simply opens the recipe viewer for that recipe. If not fully fixable, it would be nice if the recipe filler could do a "fuzzy" sort of transfer where it moves every item it can to the best of it's ability, since it knows that the inventory does have all the ingredients necessary.

Doing a bit of testing with a sword recipe seems to confirm NBT is at fault. When a plain sword is in the inventory, the recipe transfers (except slot 0). When I put Sharpness on the sword the recipe stops transferring completely.

![image](https://user-images.githubusercontent.com/72876796/188769117-fd838388-1fe4-4b92-b4d0-08356f049dce.png)

**Comment by emilyploszaj** [comment]
It's likely some comparison method is too strict for filling and I'll look into that. When it comes to the first case, it seems like you're *throwing* the first input? I'm kinda confused, I'll try to look into it more, sorry you keep running into issues with recipe handlers.

**Comment by fzzyhmstrs** [comment]
I don't think I'm throwing anything when transferring. You may be seeing the potion effect particle perfectly timed to look like a lapis flying off-screen? Thanks for taking a look! This item viewer mod is a lot easier to work with as a modder than others :)

**Comment by emilyploszaj** [comment]
Fixed in 0.4.3
