### ISSUE TITLE
[Mod Compat] Easy Mob Farm disables "Fill Recipe" Function

### ISSUE THREAD

**Issue by pewblaze** [emilyploszaj/emi#805]
Hi when im using the mod easy mob farm it disables the Fill Recipe function. Any recipe isnt working. Without the mod emi works fine.

Minecraft 1.21.1 

https://modrinth.com/mod/easy-mob-farm

**Comment by fzzyhmstrs** [comment]
This seems like an issue you should make with easy mob farm
