### ISSUE TITLE
Update 1.21.3/4

### ISSUE THREAD

**Issue by SuanOrange** [emilyploszaj/emi#806]
Update 1.21.3/4 version

**Comment by thatguymiki** [comment]
We need it asap

**Comment by HttpRafa** [comment]
Would be really nice

**Comment by emilyploszaj** [comment]
It will come with time, updates are not bugs I track

**Comment by thatguymiki** [comment]
Ok My lord, i shell wait

**Comment by SuanOrange** [comment]
> It will come with time, updates are not bugs I track

I don't think you want to release the 1.21.4 version of the mod, please don't find any other reason for your laziness👍

**Comment by screret** [comment]
> I don't think you want to release the 1.21.4 version of the mod, please don't find any other reason for your laziness👍

With attitude like that I don't think you *deserve* the update. 1.21.4 changed a lot about how recipes are sent to the client, which makes updating mods like EMI difficult. Have some patience. Calling someone "just lazy" because they haven't pandered to your needs immediately is... quite reductive and disingenous.

**Comment by E0x72-21** [comment]
> With attitude like that I don't think you _deserve_ the update. 1.21.4 changed a lot about how recipes are sent to the client, which makes updating mods like EMI difficult. Have some patience. Calling someone "just lazy" because they haven't pandered to your needs immediately is... quite reductive and disingenous.

It has been several months since you mentioned there was difficulty updating the mod to 1.21.4 or newer versions. I believe sharing some news about the current progress (or plans) for the update is a reasonable request. ：)

**Comment by imide** [comment]
> > With attitude like that I don't think you _deserve_ the update. 1.21.4 changed a lot about how recipes are sent to the client, which makes updating mods like EMI difficult. Have some patience. Calling someone "just lazy" because they haven't pandered to your needs immediately is... quite reductive and disingenous.
> 
> It has been several months since you mentioned there was difficulty updating the mod to 1.21.4 or newer versions. I believe sharing some news about the current progress (or plans) for the update is a reasonable request. ：)

I agree, however, OP decided to whine like a little bitch instead of being respectful and understanding this is an open source product being given for free. OP should learn how to port it themselves instead of being rude.
