### ISSUE TITLE
[Feature Request] Category Prioritization

### ISSUE THREAD

**Issue by fzzyhmstrs** [emilyploszaj/emi#81]
As recently discussed on the Discord, recipe categories show in some fixed alphabetical type order, which leave my category dead last most of the time. It would be nice if there was some sort of category prioritization.

Below is just spitballing; your mod your implementation at the end of the day ofc.

Possible ways I've brainstormed to handle this:

- Adding a priority directly to the category registration or class. This is a simple (sounding) approach, but has some potential for priority fighting. In the image I pasted in Discord for example (full pic below for ref), the "magehand:iron" is _not_ from my mod. The creator of the Mage Hand may very well want _their_ way of obtaining it to be first.
- Adding a json like the default recipes that assigns recipes a priority category. Like`"amethyst_imbuement:imbuing_table": ["amethyst_imbuement:garnet", "amethyst_imbuement:citrine".......]`. This obviously has the downside of being tedious, but allows a mod creator to select their category as priority on their items, while other creators that integrate with that category can put _their_ primary crafting/obtaining method as priority in their respective json.
- similar json concept with recipe namespace. This in theory vastly simplifies the above approach by letting a modder say something like `"amethyst_imbuement":"amethyst_imbuement:imbuing_table"`. Any recipe/item with the namespace "amethyst_imbuement" that is relevant to that listed category would then have Imbuing show up first as the priority category.
 
![image](https://user-images.githubusercontent.com/99366187/188792214-467818f8-a0b8-418b-bf3c-5bf5f51138ab.png)

**Comment by emilyploszaj** [comment]
Priority is now resourcepackable as of 0.6.0
