### ISSUE TITLE
Incompatible With Slight GUI Modifications

### ISSUE THREAD

**Issue by Puffadillo** [emilyploszaj/emi#82]
EMI's interface breaks when the "Slide In From Bottom" option is enabled in [Slight GUI Modifications](https://modrinth.com/mod/slight-gui-modifications). Scrolling to another page in EMI fixes the visual bug until the inventory is closed and reopened again.

![image psd](https://user-images.githubusercontent.com/108554062/190842422-3433b8ac-e910-4609-b756-a1a8510fca93.png)

- Minecraft version: `1.19.2`
- Quilt loader version: `0.17.4`
- EMI version: `0.4.0+1.19`
- Slight GUI Modifications version: `2.3.0`

**Comment by emilyploszaj** [comment]
AFAIK this was fixed (on accident) in 0.5.0 by fixing an unrelated bug
