### ISSUE TITLE
Using 'craft one' and then 'craft one to inventory' crafts 2 items

### ISSUE THREAD

**Issue by MeeniMc** [emilyploszaj/emi#84]
When using the mouse button to preload the crafting grid with 'craft one', and then using the (not set by default) mouse button (in my case, right click) to 'craft one to inventory', two items are produced (instead of one). 

## Possible solution

When using 'craft to inventory', the content of the existing crafting grid should be cleared.

**Comment by emilyploszaj** [comment]
Is this an issue? The way "craft one" works is by incrementing, and "craft one to inventory" is just "craft one, but then take the result". I think it's a bit of an intuitive interaction but I'm not sure special casing it is the right idea.

**Comment by MeeniMc** [comment]
Ok, I see the rationale and I think its use. I'll come whining again if I can't get used to it.
