### ISSUE TITLE
Enhancement: Smarter resolution for * recipes (like logs->planks->sticks) in synthetic favorites 

### ISSUE THREAD

**Issue by MeeniMc** [emilyploszaj/emi#85]
Synthetic favorites are an awesome feature!

They would be a lot more useful if, when for example crafting Sticks, the synthetic favorite would pick by itself the appropriate chain to produce Sticks from Planks,  Planks from Logs, based on what the player has in inventory. 

## Proposition 1: auto-select *item recipes by default

At the moment, selecting how to craft sticks from say, spruce planks, spruce logs, can be achieved by micro-managing the recipe tree to pick the correct association, which is not done by default. It would be great if that would all happen by default (and defaults remain changeable as it is today). 

## Proposition 2: Pick the *item with the shortest recipe chain (from current inventory)

If the player has the following items in inventory, the "shift-click" auto-pick action is not smart:  { "spruce plank" x2, "spruce log" x64, "acacia plank" x64 } results in the auto-pick "shift-click" on sticks to create a synthetic favorite for spruce planks when producing  repeaters x16.

Ideally, the algorithm should notice that there are enough "acacia planks" to satisfy the need (for example, by sorting the planks in inventory by total count), and favor the resolution that does not require crafting "spruce planks" from "spruce logs"

## Proposition 3: Multiple chain resolutions

Same scenario as above, but now I need to create more repeaters (to the point where both the "acacia planks" in inventory, and the potential "spruce logs" produces are insufficient to create enough "sticks". 

Currently, the player needs to shift-click, that resolves into either using spruce or acacia to create sticks. When the source item is exhausted (say, spruce logs->spruce planks->sticks), the player must go back to the recipe tree, undo the association (shift-right-click) and redo the association (shift click) to change to the new association (acacia planks->sticks), even though all these sources where present in inventory at the time of the first association. 

Ideally, the algorithm would satisfy the need for sticks from the count of items that are currently present, even if that requires satisfying the requirement from 2 different plank types.

**Comment by emilyploszaj** [comment]
EMI currently has a solution to this problem in the recipe tree, you can shift click a node to try and pick from defaults or from your inventory. I eventually want to add the ability to set recipe defaults for tag resolution, that's currently the only manual part.

**Comment by cplir-c** [comment]
I had no idea this was implemented; should the description be in the UI somewhere?

**Comment by emilyploszaj** [comment]
![image](https://user-images.githubusercontent.com/14813658/232259629-61dd678a-0eb3-4c02-9cbd-c9bd656d8044.png)
This is the description that's been in the recipe tree for a while. Some work could be done to make it more visible

**Comment by emilyploszaj** [comment]
Missed this resolution as time has gone on, EMI now has or had all the features asked for in this issue, going to mark as fixed.
