### ISSUE TITLE
Add config for universal menu scrolling

### ISSUE THREAD

**Issue by MysticcX** [emilyploszaj/emi#88]
You currently can only scroll the EMI menu when viewing recipes or uses for items but not when just wanting to search, you have to use the back and forth arrows. Its nice to have the ability to quickly scroll through the items.

**Comment by emilyploszaj** [comment]
This sounds like a bug, you should be able to scroll through the sidebar at any time. What situation are you running into this issue?

**Comment by emilyploszaj** [comment]
No update/response
