### ISSUE TITLE
Column Limit Option

### ISSUE THREAD

**Issue by sisby-folk** [emilyploszaj/emi#9]
To improve display performance and visual noise, it'd be great if there was a configurable limit value for the number of columns on both panes.

**Comment by emilyploszaj** [comment]
Hi! Thanks for the issue, this is planned for the near future for both the favorites and the index configurable separately, and usable for effective disabling either. I'll close this issue when it is released.

**Comment by sisby-folk** [comment]
Thanks Emi!

**Comment by emilyploszaj** [comment]
Fixed in 0.2.0
