### ISSUE TITLE
[1.18.2 FABRIC] EMI and entity banner lag

### ISSUE THREAD

**Issue by quentin452** [emilyploszaj/emi#90]
Is it possible to disable mod in the emi menu?

EMI : 

emi-0.4.0+1.18.2

Screenshot : 

![Capture d’écran_2022-10-21_12-10-48](https://user-images.githubusercontent.com/42176772/197171858-d08c18de-b2a8-4204-b7f4-692f9d9ad227.png)

![Capture d’écran_2022-10-21_12-10-54](https://user-images.githubusercontent.com/42176772/197171862-ded1a5e7-8529-4d43-9137-00ba6eb70588.png)

**Comment by emilyploszaj** [comment]
Not currently, but it's planned

**Comment by emilyploszaj** [comment]
Cleaning up old issues, items can be hidden by users and the lag mentioned in the title is unresolveable due simple to the cost of rendering items, so I believe this can be closed.
