### ISSUE TITLE
EMI not showing AE2 recipes

### ISSUE THREAD

**Issue by sayore** [emilyploszaj/emi#91]
![image](https://user-images.githubusercontent.com/6115966/199273261-8030ec00-618b-4c6f-b7b0-1a8d7fa69182.png)
Its only showing the recipes from Create to make the Inscriber recipes currently for me, not the Inscriber ones. (Engineering Processor right here as an example)

Using 1.18.2 - Fabric 0.14.9
appliedenergistics2-11.5.0.jar
emi-0.4.1+1.18.2.jar

**Comment by emilyploszaj** [comment]
Hi! EMI itself is not responsible for mod integration, the mods themselves are. AE2 has chosen to not support EMI, so it does not have first party support, however, you can install [this mod](https://modrinth.com/mod/emicompat) to get third party support for AE2, and some other mods that don't have native EMI integration.
