### ISSUE TITLE
Some items don't load

### ISSUE THREAD

**Issue by Aces-and-Jacks** [emilyploszaj/emi#92]
<img width="1512" alt="Screen Shot 2022-11-10 at 4 26 40 AM" src="https://user-images.githubusercontent.com/106651342/201052559-1021248f-f270-4f45-a158-64b087efa901.png">

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/FuLsAvv

**Comment by LemmaEOF** [comment]
Just in case - see if launching without Sodium Extra fixes it.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/TPr51Cz

**Comment by LemmaEOF** [comment]
Hm, I'm not personally sure what could be causing it. EMI has detection in place for if Sodium is loaded and accounts for it, so I don't think it'd be that.

You can make it work guaranteed if you disable EMI's batched item rendering, but be aware that might result in a slight performance hit.

**Comment by Aces-and-Jacks** [comment]
ok

**Comment by emilyploszaj** [comment]
Did this start happening after you installed a specific mod? Your modlist is quite large and I haven't been able to reproduce this.

**Comment by Aces-and-Jacks** [comment]
well I installed all the mods I had on fabric. then I installed emi

**Comment by Aces-and-Jacks** [comment]
I can try and look but it'd take a bit

**Comment by emilyploszaj** [comment]
If you can perform a binary search (remove half mods to see if present, repeat until you find a couple that may be the culprit) you could likely figure out pretty quickly.

**Comment by LemmaEOF** [comment]
Potential culprits I'm seeing:

- Reese's Sodium Options
- OptiGui
- CIT: Resewn

Try taking those out one at a time and seeing if removing any of them fixes it

**Comment by Aces-and-Jacks** [comment]
It was Auto HUD https://modrinth.com/mod/autohud

**Comment by emilyploszaj** [comment]
Could be useful to open a bug with them, they have to be doing something peculiar.

**Comment by Aces-and-Jacks** [comment]
Did that. It'll probably be a but till he responds. I'll close this when he fixes it

**Comment by Aces-and-Jacks** [comment]
It was Exordium https://modrinth.com/mod/exordium

**Comment by Aces-and-Jacks** [comment]
never mind not exordium

**Comment by Aces-and-Jacks** [comment]
turns out it's a mix of exordium and autoHUD that's the issue

**Comment by Aces-and-Jacks** [comment]
Well since it's likely never going to be fixed I'll close this

**Comment by emilyploszaj** [comment]
This may have been fixed by a recent commit on accident, I'll look into it

**Comment by Aces-and-Jacks** [comment]
oh yeah it got fixed

**Comment by Aces-and-Jacks** [comment]
forgot to say that

**Comment by Aces-and-Jacks** [comment]
got fixed on autoHUD's end
