### ISSUE TITLE
Incompatible with "Inventory Tabs"

### ISSUE THREAD

**Issue by Xoouu** [emilyploszaj/emi#94]
The status effect blocks the tabs.
![image](https://user-images.githubusercontent.com/73406225/201541894-82b561ba-e2d1-4aca-a317-9fa3930c18b3.png)
Having an option like REI to move the status effect to the left would be great.

**Comment by artemisSystem** [comment]
another incompatibility: when you have many tabs available, the arrow for switching between tab pages can overlap the EMI sidebar. this may be an issue to fix on their side instead though
