### ISSUE TITLE
Texture adjustment request:

### ISSUE THREAD

**Issue by CodeF53** [emilyploszaj/emi#96]
Can you add one more thing to `background.png` so I can differentiate between the main recipe panel and the inner recipe panel?

how it is currently:
![background.png](https://user-images.githubusercontent.com/37855219/202831309-5cb4b238-9052-49d3-9cc8-560507f4d414.png)
![example render](https://user-images.githubusercontent.com/37855219/202831301-e86a3346-577b-4df1-8ba4-1087432854eb.png)

how I would like it to be:
![background.png](https://user-images.githubusercontent.com/37855219/202831326-1795bbb2-1a03-485b-98fd-bb1d01f88c55.png)
![example render](https://user-images.githubusercontent.com/37855219/202831328-b25435a8-1d57-4417-8d48-f4349da03e24.png)

**Comment by emilyploszaj** [comment]
Also, the gray fill color should become a texture instead of hardcoded

**Comment by emilyploszaj** [comment]
This should've been completely fixed as of 0.6.0
